.TH HEY LOCAL Public-Domain
.ad b
.SH NAME
hey \- write to all terminals that a person is using
.SH SYNOPSIS
\fBhey\fR [\fB-n\fR] person message
.SH DESCRIPTION
.I Hey
writes a
.I message
to all terminals being used by the login
.IR person .
The
.I message
is broadcast via
.IR write (1),
which prints an initial banner identifying the sender.
If the
.I person
isn't logged in, the
.I message
is mailed.
.PP
The
.B \-n
option causes
.I hey
to track the person down across the local network.
By default,
.I hey
looks for the
.IR person 's
logins only on the local system.
.PP
Permission to write to a terminal is granted or denied by the
.IR mesg (1)
command.
.SH EXAMPLES
Assuming your own login is
.B me
and the other person's login is
.BR you :
.sp
.RS
(incredibly-long-running-command; hey me all done) &
.br
hey you Call your wife at home, she just called.
.br
hey root the console is out of paper
.RE
.PP
Note that multi-line messages can be sent via newlines within quotes (from
.IR /bin/sh )
as in:
.sp
.RS
.nf
hey you 'This
is spread
across
a few lines.'
.fi
.sp
.RE
The same effect is possible from
.I csh
by typing a backslash (escaped newline) at the end of the message lines.
.SH DIAGNOSTICS
\fIYou have write permission turned off\fR as printed by
.IR write (1).
.SH "SEE ALSO"
mesg(1),
talk(1),
wall(1),
write(1)
.SH BUGS
Denying write-access via
.I mesg
works only with local messages.
The
.B \-n
option handcrafts a faked
.I write
via
.IR rsh (1)
and
.IR cat (1),
which seems to be able to break through steel.
.PP
This command makes it easy for some people to be obnoxious.
