.TH TREK73 6 "04 Mar 1986"
.UC 4
.SH NAME
trek73 - A Star Trek simulation
.SH SYNOPSIS
trek73 [-tcsSECNHfrdyTnFl]
.SH DESCRIPTION
.PP
.I Trek73
is one of many Star Trek simulations now available.
In its time, it was considered one of the best.
.PP
The player takes on the role of a starship commander
who is involved in a battle against enemy alien ships.
.PP
Your starship can be one of four classes, or it can
even be a ship of your own design -- see shipyard(6).
.PP
At your control are the ships' massive warp engines,
its main weapons, the phaser banks and photon torpedos,
and its defensive set of shields.
Using these and your own ingenuity, you must form and
implement a strategy that will lead you to victory.
.PP
Also at your disposal are such tactics as the defenseless ruse,
and the corbomite bluff.
.PP
Reminiscent of
.I ls
(1),
.I trek73
has a large number of options:
.TP
.B \-t
Turns on terse mode.
No initial scenario description is given.
This is useful for terminals running at low baud rates.
This option is normally off.
.TP
.B \-c
Allows the specification of the Federation captain's name.
.TP
.B \-s
Specify the sex of the captain of the Federation vessel.
.TP
.B \-S
Specify the name of the Science Officer of the Federation vessel.
By default the Science Officer is Mr. Spock.
.TP
.B \-E
Specify the name of the Chief Engineer of the Federation vessel.
By default the Chief Engineer is Mr. Scott.
.TP
.B \-C
Specify the name of the Communications Officer of the Federation vessel.
By default the Communications Officer is Lieutenant Uhura.
.TP
.B \-N
Specify the name of the Navigator of the Federation vessel.
By default the Navigator is Ensign Chekov.
.TP
.B \-H
Specify the name of the Helmsman of the Federation vessel.
By default the Helmsman is Lieutenant Sulu.
.TP
.B \-f
Specify the name of the enemy commanding officer.
.TP
.B \-r
Specify the race of the enemy.
The race should be one of the following:
Klingon, Romulan, Kzinti, Gorn, Hydran, Lyran, Tholian, Orion,
or Monty Python.
.TP
.B \-d
Set the delay time for command entry.
Higher times can be useful for novices or for playing on very slow
terminals.
.TP
.B \-y
Silly option.
Adds the Monty Pythons as a possible enemy race.
This option is normally off.
.TP
.B \-T
Teletype option.
Causes certain parts of the output to come out as they did on the
original teletype implementation.
Doesn't do much for the game on crts.
This option is normally off.
.TP
.B \-n
Specify the name of the Federation vessel.
The default name for the Federation vessel is randomly chosen from a
set of names.
.TP
.B \-F
Specify the class of the enemy vessel(s).
Allowable classes are Destroyer (DD), Light Cruiser (CL),
Heavy Cruiser (CA), and Dreadnought (DN).
If the argument is none of the above, the program assumes that this is
the name of a file where a player-designed ship is stored.
.TP
.B \-l
Specify the class of the Federation vessel.
Classes available are the same as the enemy's.
.SH AUTHORS
William K. Char, Perry Lee, and Dan Gee 
wrote the initial TREK73 in BASIC.
Dave Pare and Chris Williams translated the BASIC into C.
Jeff Okamoto, Peter Yee, and others corrected and enhanced the code.
.SH SEE ALSO
Jeff Okamoto,
.I "The Star Trek Battle Manual"
.SH BUGS
Hopefully none.
Bug reports should be sent to: ..!ucbvax!okamoto and ..!ucbvax!yee.
