.TH ADJ 6 Local
.UC 4
.SH NAME
adj \- fill and adjust text lines
.SH SYNOPSIS
.B adj
[
.B \-h
] [
.B \-n
] [
.B \-p
] [
.B \-w
.I n1,...
] [ file ]
.SH DESCRIPTION
.I Adj
copies the given file (standard input if none is given) to the standard output,
filling lines and adjusting the right margin. Indentation and empty lines
are preserved.
.PP
Normally, words (uninterrupted sequences of non-blank characters) are not
broken, unless the
.B \-h
(hyphen) flag is given.
.PP
The
.B \-n
(no adjust) prevents
.I adj
from adjusting the right margin.
.PP
If the 
.B \-p
(paragraph) option is specified, indentation is preserved only on
the first line of a paragraph, assuming paragraphs are separated by empty lines.
.PP
The
.B \-w
.I n
(width) option sets the line width to
.I n
(default 65).
When given as
.B \-w
.I n1,n2,...
(a comma-separated sequence of numbers) the output lines will be
.I "n1, n2"
etc. characters long, respectively.
When the sequence is exhausted, it is restarted.
.SH "SEE ALSO"
ctr(6)
.SH BUGS
.B \-n
does not break words intelligently.
.PP
Change of indentation is done ungracefully.
.PP
There's probably a better way tp specify line lengths.
