.TH CTR 6 Local
.UC 4
.SH NAME
ctr \- center text lines
.SH SYNOPSIS
.B ctr
[
.B \-w
.I n
]
.SH DESCRIPTION
.I Ctr
copies its standard input to its standard output,
centering text in the output lines.
.PP
The
.B \-w
.I n
(width) option sets the output line width to
.I n
(default 65).
.SH "SEE ALSO"
adj(6)
.SH BUGS
