.TH POSTNM 1
.SH NAME
postnm \- post mail or news
.SH SYNOPSIS
.B postnm
[
.B \-ixw
]
[ header-options ]
[ file ]
.SH DESCRIPTION
.I Postnm
reads a message in ARPANET mail format from a file, or from the
standard input if no file is given.
It checks the message for validity.  If the message contains a
Newsgroups line, the message is posted to USENET.
If the message contains To, Cc, or Bcc lines, it is mailed to
the indicated addresses.
.P
Users who wish to invoke
.I postnm
directly should place their article in a file and then run postnm on it.
.I Postnm
makes no attempt to save an article when an error occurs, so if you try
to type an article directly into
.I postnm
from the terminal, you will be forced to start all over again if something
goes wrong.
Now that
.I postnm
exists, users should never invoke inews directly.
.SS options
.IP -i 6
Identify.  If the file $HOME/.signature exists, append it to the message.
.IP -x 6
Causes postnm to print out the generated command lines without
actually posting the message.
.IP -w 6
Causes postnm to wait for the postings to complete rather that running
inews and mail in the background.
.P
Certain header lines can be inserted into the header of the article
from the command line using the following options:
.sp
.nf
	-c	Control:
	-d	Distribution:
	-f	From:
	-n	Newsgroups:
	-R	References:
	-s	Subject:
	-t	To:
.fi
.P
The Command header is never passed to inews or mail.
``Command:\ reply''
causes
.I postnm
to ignore the Newsgroups and Distribution lines, and ``Command:\ followup''
causes
.I postnm
to ignore the To lines.
.P
If the environment variable NEWSARCHIVE is set, it specifies a file in which
copies of all news (but not mail) articles are to be placed.
.SH EXAMPLE
postnm -c 'cancel <123@hou3c.UUCP>' -n net.misc /dev/null
.in +5
Cancel article <123@hou3c.UUCP>.
.B /dev/null
provides an empty article body.
.in -5
.SH FILES
.nf
/usr/lib/news/active            list of newsgroups
/usr/lib/news/moderators        addresses of newsgroup moderators
/usr/lib/news/distributions     list of distributions (optional)
$HOME/.signature		signature file
.SH AUTHOR
Kenneth Almquist (ihnp4!hou3c!ka)
