.TH RCHECK 1 "18 Mars 1985"
.UC 4
.SH NAME
rcheck \- check for users logging in and out from systems on the local network
.SH SYNOPSIS
.B rcheck
[
.B username ...
] [
.B \-t tty ...
] [
.B \-h host ...
]
.SH DESCRIPTION
.I Rcheck
runs in the background and checks for
users logging in and out from machines
connected to the local network.
Every time
.I rcheck
finds out that somebody has logged in
or out, it will print a message on the
terminal screen,
telling the time,
the users login-name,
the host he is on,
the affected tty,
and the real name of the user, if it is
possible to find it in the local machines
/etc/passwd -file.
.PP
It can be very annoying receiving messages
all the time on the terminal screen, specially
when editing files... But if you specify one or
more
.B usernames
on the command line,
.I rcheck
will only tell you when the specified users log
in and out.
.br
The other flags works in a similar way.
The
.B \-t
flag takes arguments of tty-names and then it
will only tell you when any of the specified
ttys is affected.
The
.B \-h
flag accepts arguments which are names of remote
hosts connected to a local network. As with the
previous flags,
.I rcheck
will only print messages concearning the specified
hosts.
.PP
.I Rcheck
scans the local machine with an
30 second intervall, and the
remote hosts every
60 seconds.
.I Rcheck
terminates it self when the calling process is
terminated.
.SH FILES
.ta 1i
/etc/utmp
.br
/usr/spool/rwho/whod.*
.br
/etc/passwd
.SH "SEE ALSO"
sysline(1)
.SH AUTHOR
Anders Klemets
 (klemets@ttds.UUCP)
.SH BUGS
If there are two different users with the same
.B username
on the hosts in the local network, and one of
them has an account on the local machine,
.I rcheck
will tell you the name of this user even when
the other user logs in on "his" machine.
This, however, is not specially common.

