.TH SAFE 1L
.SH NAME
safe \- kill a process after specified time.
.SH SYNOPSIS
.B safe -d <delay> -w <warning> -b command_line
.SH DESCRIPTION
.I Safe
executes the given
.BR command_line ,
killing the process if it is still running after
.B delay
seconds.
If the -w option is specified, a warning will be given
.B warning
seconds before the process is to be terminated.
The -b option supresses the text of the warning message and only beeps the
terminal; this is useful if you are in a screen oriented program.
.PP
I wrote this program to make it easier to test a program that was doing
some strange ioctls.
However it seems to have many uses, including
controlling netnews addiction.
.SH AUTHOR
Mike Blackwell  -  USENET:  ...!ihnp4!aicchi!mdb
.SH NOTES
The program traps SIGINT and uses it to terminate the process.
I haven't run into any problems with this, but it could be a problem with
some programs.

