.TH TREK73 6 "18 Jun 1985"
.UC 4
.SH NAME
trek73 - A Star Trek simulation
.SH SYNOPSIS
trek73
.SH DESCRIPTION
.PP
.I Trek73
is one of many Star Trek simulations now available.
In its time, it was considered one of the best.
.PP
The player takes on the role of a starship commander
who is involved in a battle against enemy alien ships.
.PP
At your control are the ships' massive warp engines,
its main weapons, the phaser banks and photon torpedos,
and its defensive set of shields.
Using these and your own ingenuity, you must form and
implement a strategy that will lead you to victory.
.PP
Also at your disposal are such tactics as the defenseless ruse,
and the corbomite bluff.
.PP
For more information, see the document
.I "The Star Trek Battle Manual".
.SH AUTHORS
William K. Char, Perry Lee, and Dan Gee 
wrote the initial TREK73 in BASIC.
Dave Pare and Chris Williams translated the BASIC into C.
Jeff Okamoto, Peter Yee, and others corrected and enhanced the code.
.SH SEE ALSO
Jeff Okamoto,
.I "The Star Trek Battle Manual"
.SH BUGS
Hopefully none.
Bug reports should be sent to: ..!ucbvax!okamoto and ..!ucbvax!yee.
