
.TH INSULT 6
.SH NAME
insult \- print a random insult
.SH SYNOPSIS
.B insult
[
.I nn
]
.SH DESCRIPTION
.I Insult
prints a random insult.
The optional argument
.I nn
specifies the number of sentences in the insult.
.IR Insult \&'s
most common abuses are
being piped into
.IR mail (1)
or substituted for
.IR joke (6)
..IR fortune (6)
in another user's .logout file.
.SH "SEE ALSO"
kafka(6), mail(1), fortune(6)
.SH AUTHOR
Wayne Christopher
