.TH RANGE 1 local
.SH NAME
range \- generate loop values
.SH SYNOPSIS
.BI range " n1" " to" " n2"
[
.BI by " n3"
]
.SH DESCRIPTION
.I Range
writes the numbers from
.I n1
to
.I n2
one to a line on the standard output.
The increment
.I n3
defaults to
1
.RI ( n1 \(<= n2 )
or
\-1
.RI ( n2 < n1 ).
The command is often used with the Shell
.B for
statement.
.SH EXAMPLE
Set the Shell variable
.I a
to
the strings
.I 1
to
.I 10,
with the value increasing after each
execution of the loop.
.PP
.RS
.nf
for a in \`range 1 to 10\`
do
	echo $a
done
.fi
.RE
.SH SEE ALSO
apply(1), bc(1), sh(1)
.SH BUGS
There is no check for arithmetic overflow.
