.TH CALLME 1 
.SH NAME
callme \- appointment reminder program
.SH SYNOPSIS
.B callme
(time) (message)
.SH DESCRIPTION
.I Callme
is a program which will start appointment reminders running in
the background.  At the desired time the user will be reminded
that it is time for the appointment.  The time and message for the
call are entered on the command line.  The time must be entered in
24 hour time with no colon.
.SH AUTHOR
Mike Essex
.SH "SEE ALSO"
autocall(1), vcal(1), callme(1), lcal(1), appts(1), eappts(1)
