.TH FTIMES 1
.SH NAME
ftimes \- display access, change and modify times of a file
newer, older \- compare access, change and modify times of a file
.SH SYNOPSIS
.B ftimes
[
\fB\-acmv\fR
] file
.br
.B newer|older
[
\fB\-acmntvw\fR
] file1 file2
.SH DESCRIPTION
.I Ftimes
displays the access, change and modify times of a file in seconds
past the epoch (1 January 1970).
.PP
.I Newer|older
exit with
.I true
status if
.B "file1 relation file2"
is true.
.SH COMMAND LINE OPTIONS
.TP 8
.B \-a,c,m
Display the access, change or modify times of the file.
If none of the above are given, the default is modify time.
.TP
.B \-v
Display in human readable (ctime) format.
.PP
The following options apply to
.I newer|older
only:
.TP
.B \-n
Display the name of the first file if the relation was true.
.TP
.B \-t
Display the times of the first file if the relation was true.
The
.B a,c,m
flags can be used to choose a subset as for
.I ftimes
and the same default applies. The first type of
time specified is used in the comparison.
.TP
.B \-w
When used with the
.B "n or t"
flags, displays the winner of the comparison regardless
of the truth value of the relation.
.SH EXAMPLES
.br
.nf

.in +5
	ftimes -v foo.c
.in -5

.fi
displays the last modify time of foo.c.
.br
.nf

.in +5
	newer -cnw filea fileb
.in -5

.fi
prints the file that was created more recently.
.SH AUTHOR
Ken Yap (University of Rochester)
