.TH PWENTRY l
.UC 4
.SH NAME
pwentry, pwmakedir \- automatic account generator
.SH SYNOPSIS
.B /usr/bin/pwentry
[ -uUID -d -g ]
.PP
.SH DESCRIPTION
.I Pwmakedir
invoke an automated account entry program.  The system administrator
is prompted to enter four fields of information for the new user,
login name, full name, home directory, and group number.  From this 
information, an entry is inserted in 
.I /etc/passwd,
.I /etc/group,
and the users home directory with the appropriate dot files is created.
.PP
The following optional arguments are accepted:
.PP
.TP 8
.B -d   
Do not call
.I pwmakedir
to make the users home directory.
.PP
.TP 8
.B -gGID
Use GID as the group number for all entries.
.PP
.TP 8
.B -hDIR
Use DIR as the home directory for all entries.
.PP
.TP 8
.B -n   
Do not enter the user in the 
.I /etc/group 
file.
.PP
.TP 8
.B -uUID
The following user id is used to start the search in
.I /etc/passwd.
.PP
These routines rely on a free of marker
.I /etc/passwd 
file.  Upon completion of
.I pwentry,
the 
.I /etc/passwd
file will be sorted on the UID field.
The head of the home directory must exist, or
.I pwmakedir
will fail.  (if /uh/graphics/joe is the homedir, /uh/graphics must
exist previous to
.I pwmakedir's
invocation).
.I Pwentry
will not allow duplicate UID's or duplicate login names.
.PP
.I Pwentry
will loop, asking for another login name, until the string
.I exit
is entered.  The passwd file is then merged with the entries, and
pwmakedir is involed.  The 
.B -uUID
option is particularly useful if it is desired to arrange the
.I /etc/passwd
file in some home directory style order.
For example,
.PP
pwentry -u300 -g19 -h/uh/graphics
.PP
will prompt for login name and full name only, using the first UID >= 300.
.SH FILES
/etc/passwd	password file.
.br
/etc/group	group file.
.br
/etc/tempfile	stores user entries before merging with passwd.
.br
.SH AUTHOR
Lory Molesky
.SH BUGS
The search of the password file is slow if the UID supplied has
many sequential entries after it.  If the 
.I /etc/passwd
file has the ::0:0::: markers before it is sorted, these will be
placed in the first lines of
.I /etc/passwd
confusing the UNIX file system.
.br
