.TH BGREP 1 "Georgia Tech"
.SH NAME
bgrep \- search a file for one or more simple strings
.SH SYNOPSIS
.B bgrep
[ options ] string-list [ files ]
.SH DESCRIPTION
.I Bgrep
(Boyer\-Moore grep) is program patterned after
.IR fgrep (1).
It uses the Boyer\-Moore string searching algorithm, which actually gets
faster as the length of the pattern to be searched for increases.
.I Bgrep
searches for plain
.I strings\^
(separated by newlines in the
.I string-list\^
argument),
not regular expressions in the style of
.IR grep .
.PP
The following
.I options
are recognized:
.TP
.B \-v
All lines but those matching are printed.
.TP
.B \-x
(Exact) only lines matched in their entirety are printed.
.TP
.B \-c
Only a count of the matching lines are printed.
This is the total count, across all the input files.
.TP
.BR \-i " or " \-y
Ignore case when trying to match a line.
Both versions of this option are accepted for compatibility with
.I grep
on different versions of Unix.
.TP
.B \-l
Only the names of files with matching lines are printed (once),
separated by newlines.
.TP
.B \-n
Each line is preceded by its relative line number within the file.
.TP
.B \-s
Silent mode:  No output is generated (except error messages).
This is useful for just checking the exit status.
.TP
.BI \-e " string"
Same as a simple
.I string
argument, but useful when the string begins with a \-.
.TP
.BI \-f " file"
The strings to be searched for are read from
.IR file .
.PP
The arguments to the
.BR \-e " and " \-f
options
.I must
be given as separate program arguments, i.e. separated by white space.
.PP
.I Bgrep
catches conflicting arguments (e.g.
.BR \-v " and " \-x )
and complains.
.SH SEE ALSO
.IR ed (1),
.IR sed (1),
.IR grep (1),
.IR sh (1)
.SH DIAGNOSTICS
Exit status 0 if any matches were found, 1 if none, 2 for syntax
errors on the command, or if any files could not be opened (even if
matches were found).
.SH BUGS
Input lines and the strings to be searched for are limited to 256 characters.
Longer input lines are truncated.
.PP
.I Bgrep\^
will not search for any more than 120 different strings.
.PP
Uses the <stdio.h> package, which slows it down some.
Nonetheless, in the usual case,
it is 10% to 20% faster than
.IR fgrep (1).
.SH AUTHORS
Roy Mongiovi (gatech!gitpyr!roy) coded the guts of the Boyer\-Moore algorithm,
while Arnold Robbins (gatech!arnold) wrote the code to do all the rest of
the work, and the man page.
