.TH FORWARDMAIL 8 3/28/84
.UC 4
.SH NAME
forwardmail - mail forwarding service
.SH SYNOPSIS
/usr/lib/forwardmail
.SH DESCRIPTION
.s3
This utility is intended for users who have accounts on multiple
UNIX machines, and want mail they receive on all of them to be
forwarded to one site.
.PP
To use this service, if it has been installed and enabled on one's computer,
a user only needs to put the name of the account to forward his
mail to in a file ".forward" in his home directory (e.g. aplvax!dan).
.PP
Forwardmail is enabled by having it periodically
executed from 'crontab' (say: once an hour or day).  
When run, it checks to see whether users with pending mail 
in /usr/spool/mail have requested it to be forwarded to another account.  
If a .forward file exists in a user's home directory 
the mail is forwarded with the mail on the local machine being removed.
.SH FILES
/usr/lib/crontab
.br
/usr/spool/mail/*
.br
$HOME/.forward
.br
/usr/lib/uucp/L.sys
.SH AUTHOR
Daniel M. Sunday, JHU/APL (...umcp-cs!aplvax!dan)
.SH BUGS
There is no way to check whether a user has set up two machines to be
forwarding mail to each other.
.PP
The user should be able to set his own forwarding frequency in
his .forward file.
