'\" %W% - %E%
.TH DS 1 %I% %P%
.SH NAME
dt \- display tree
.SH SYNOPSIS
.B dt 
[
.B -vs
]
[
.B -i n
] dir ...
.SH DESCRIPTION
\fIDt\fR recursively descends a directory tree printing out only the
subdirectories.  If no directories are specified, then the current
working directory is taken as a default.
.P
The \fB-v\fR switch is used to specify verbose output (can't open a
directory, etc.).  Directories that are actually symbolic links are
not descended and marked by an "(s)" after their name 
unless the \fB-s\fR switch is specifed.
.P
Each level in the tree is separated with tabs unless \fB-i\fR is specified,
then \fBn\fR spaces are output instead.
.SH SEE ALSO
ls(1),du(1)
.SH BUGS
Currently, \fIDt\fR lists the directories in the order that they are
stored, not alphabetical.
