.TH APB I 75.07.29
.SH NAME
apb \- all points bulletin
.SH SYNOPSIS
.B apb
.I arg
\&...
.SH DESCRIPTION
.I Apb
attempts to print its
.IR arg s
on each terminal
which has a user signed on.
It prints ``apb from sender:'' at the beginning of its line,
and informs the user of any teletypes which could not be written.
``Sender'' is the login-id of the user issuing the
.IR apb .
.SH FILES
/dev/tty?
.SH "U of T INFO"
Written at U of T by Tom Duff.
Modified by Rob Pike to print sender name.
Modified by Ron Gomes to print sender name
as login name and not current userid.
Modified by Henry Spencer to put out a couple of newlines and bells
at the beginning of the message.
.SH BUGS
Tends to annoy people when used indiscriminately.
