.TH BANNER I Nov/76
.SH NAME
banner \- print in large type
.SH SYNOPSIS
.B banner
.RI [- font ]
.I text
\&...
.SH DESCRIPTION
.I Banner
prints its arguments,
one to a line,
in
.nf

 x                                   x
  x                                  x
  x    xxx  x xx   xx x  xxx        xxxx  x   x x xx   xxx
  x       x xx  x x  xx x   x        x    x   x xx  x x   x
  x    xxxx x     x   x xxxx         x    x   x x   x xxxx
  x   x   x x     x   x x            x  x x  xx x   x x       xx
   x   xxx  x      xxxx  xxx          xx   xx x xxxx   xxx    xx
                      x                       x x
                  xxxx                     xxx  x

.fi
Banners in other fonts
than the default can be produced by using
.RI - font
as the first argument to banner.
.I Font
must be a Versatec spooler format font.
Its name is looked up first in the current working directory, and then in
/usr/font, where the system font library resides.
The default
.I font
is called /usr/font/banner.v.
.I Text
is either a single sequence of characters with no intervening blanks,
or sequence of any characters enclosed in double quote marks (").
.SH FILES
/usr/font/*.v
.SH "U of T INFO"
Written at the University of Toronto by
Tom Duff
.SH BUGS
