.TH C I MAR/76
.SH NAME
c \- filter which splits output into columns
.SH SYNOPSIS
.B c
.RI [+ m ]
.RI [- n ]
.RI [ file ]
.SH DESCRIPTION
.I C
reads from the standard input (or
.I file
if the argument is given)
and writes to the standard output, splitting as many lines as possible
per line.
.RI - n
sets the line width
(default 80) and
.RI + m
sets the number of blanks to be printed
between input lines (default 2).
.SH EXAMPLES
ls ^ c
.br
nm /net/caltech/unix | c -130 | pr -h "Cal conf" | lpr
.SH "U of T INFO"
Written at the University of Waterloo.
.SH BUGS
It should break on lines terminated by a :.
This would allow ``ls dir1 dir2^c'' to work.
