.TH HOME I "7 July 1978"
.SH NAME
home \- print home directory of user
.SH SYNOPSIS
.B home
[
.I username
]
.SH DESCRIPTION
.I home
prints the full pathname of the home directory
of a user.
If no
.I username
is given, it is assumed to be the user running the program.
.PP
.I Home
is mainly useful in shell files,
where it is otherwise difficult
to use somebody else's files
without wiring in an assumption about where his directories are.
For example,
.sp 1
.ti +10
j=`home joeblow`
.fi
.sp 1
will place the pathname of joeblow's home directory into the shell
variable $j.
.nf
.SH FILES
/etc/passwd
.SH "SEE ALSO"
sh(I)
.SH DIAGNOSTICS
The obvious:  bad syntax or nonexistent user.
.SH "U OF T INFO"
Written at U of T by Henry Spencer.
