.TH MCV 1 U of T
.DA 3 Sept 1980
.SH NAME
mcv \- convert manual page to V7 format
.SH SYNOPSIS
.B mcv
[ filename ]
.SH DESCRIPTION
.I Mcv
takes a V6 manual page
and produces a version using the V7 manual macros.
Input is from \fIfilename\fR (default standard input) with output
on standard output.
.I Mcv
is implemented as a complex \fIsed\fR script.
.PP
Some things will still have to be checked (and perhaps fixed) manually.
The date on V6 manual pages is frequently wrong.
Many manual pages should have a
.I commentary
field added to the
.B .TH
macro that begins them.
Font usage should be checked carefully;  many old locally-written manual
pages are very careless about this.
.SH FILES
/usr/lib/mcv.script
.SH SEE ALSO
man(7)
.SH U OF T INFO
Local product, written by Henry Spencer.
.SH BUGS
Some uncommon V6 macros aren't really handled quite right.
.PP
Some of the heuristics used to catch common font-usage bungles could
conceivably screw up on unusual texts.
.PP
Unusual situations in general may expose oversimplifications.
