.TH PHONE 1 July/77
.SH NAME
phone \- find phone numbers
.SH SYNOPSIS
.B phone
.RI [ name ]
\&...
.SH DESCRIPTION
.I Phone
calls
.I grep
to search for the patterns
.RI ( name s)
passed to it,
looking in the files /usr/adm/phonebook
and $HOME/.phonebook (if it exists).
Thus, its effect is to look up phone numbers.
The system phonebook file is writable by anyone,
and system policy allows anyone to insert any
phone numbers in common usage into the file,
but please be discriminatory
in using phone as a database management system.
.PP
Due to the absence of dual case searching in an earlier version
of grep, all entries (at the time of writing) are only in lower
case.  This is no longer necessary, but it is recommended
that this practice continue.
.SH FILES
/usr/adm/phonebook
$HOME/.phonebook
.SH "SEE ALSO"
Ma Bell
.SH "U of T INFO"
Written at the University of Toronto by
Neil Kaden, Robert Pike & Alexander Graham Telephone
.SH BUGS
Can't dial the phone for you.
