.TH PO 1
.DA 26 January 1981
.SH NAME
po \- filter to add a page offset to text
.SH SYNOPSIS
\fBpo\fP
[ \fB\-\fP\fIx\fP[\fB.\fP\fIy\fP] ]
[ \fB-s\fP ]
[ file ... ]
.SH DESCRIPTION
\fIPo\fP copies its standard input or file arguments to its standard output,
with a page offset inserted at the beginning of each line.
.PP
The simplest page offset is obtained with \fB-\fP\fIx\fP,
which just gives \fIx\fP blanks.
If \fB-\fP\fIx\fP\fB.\fP\fIy\fP is used,
the offset consists of \fIx\fP blanks, a cut mark (vertical bar),
and \fIy\fP blanks.
.PP
The default is set up so that text prepared with the default
\fInroff\fP line length comes out centered after trimming.
The \fB-s\fP option is for things like system documentation
which are (for some silly reason) done with a 60-character line
instead of the nroff default of 65.
.SH "SEE ALSO"
The \fI.po\fP commands in the various formatters.
.SH "DIAGNOSTICS"
Messages, plus return code of -1 for bad usage, -2 for can't open file.
(Admittedly, these are of dubious value.)
.SH "U OF T INFO"
Written at U of T by Henry Spencer.
Rewritten by John Hogg to remove a few bugs, use stdio, and allow file arguments for input.
