.TH WHERE I 5/05/76
.SH NAME
where \- where in the manual can I find this
.SH SYNOPSIS
.B where
.I pattern
.SH DESCRIPTION
.I Where
searches the tables of contents with the
.I pattern
given,
and prints any lines in which that
.I pattern
is found.
This allows a documentation
enquiry without previous knowledge of the exact name,
or section of a command.
The
.I pattern
is similar to that used by
.IR grep ,
which in turn is derived from
.IR ed \ patterns.
See
.IR ed (I)
for a description of that.
This command is currently implemented as a shell file.
.SH FILES
/usr/man/man0/tocx1 through tocx9: the tables of contents
.SH "SEE ALSO"
.IR grep (I)
.SH "U of T INFO"
Written at the University of Toronto by
Martin Tuori
.SH BUGS
The tables of contents usually aren't completely up-to-date.
