.TH WMI 1
.DA 23/Aug/75
.SH NAME
wmi \- who am i, anyway?
.SH SYNOPSIS
wmi [-]
.SH DESCRIPTION
WMI prints out the effective user id, and, if different from
the real user id, prints the real user id in parentheses.
If an argument is given, then the same is done for group id.
.SH FILES
/etc/passwd
.br
/etc/group
.SH "SEE ALSO"
who(1)
.SH "U of T INFO"
Written at the University of Toronto by
Tom Duff
.SH BUGS
Has an uncheery cold steel voice.
