.TH X I 28/Nov/1977
.SH NAME
x \- expand unprintable characters
.SH SYNOPSIS
.B x
.RI [ file ]
\&...
.SH DESCRIPTION
The
.I x
command copies the
.IR file s
given as arguments (no
.IR file s
implies standard input)
to standard output, expanding tabs, backspaces, and control characters
other than newline into printable representations.
The representations chosen are '<' for backspace, '>' for tab,
newline for newline,
.RI \'\\ nnn '
for any other control character,
\&'`c' for character 'c' with the top bit set,
and the character itself for anything else.
.SH "SEE ALSO"
.IR p (I)
.SH "U OF T INFO"
Written by Henry Spencer.
