.\" @(#)newspace.1	1.2 1/21/86 21:36:09 - Amdahl/UTS
.TH NEWSPACE 1 "Local"
.SH NAME
newspace \- show how much space each newsgroup uses
.SH SYNOPSIS
.B /usr/lib/news/newspace
.SH DESCRIPTION
.I Newspace
is a shell script which
displays the total disk space used by the articles in
each Usenet newsgroup.
While
.IR du (1)
is used to measure the disk space, the report is
.I not
a
.I du
of all the newgroup directories, but the disk space used
by that newsgroup alone;
.IR eg ,
the total for net.music does not include the total for
net.music.gdead.
.P
The output is sorted so that largest newsgroups are
displayed first.
.P
.SH FILES
.TP 25
/usr/lib/news/archive
list of newsgroups to measure
.TP 25
/usr/spool/news/\(**
where all newsgroups are stored
.SH SEE ALSO
du(1)
.SH DIAGNOSTICS
Self-explanetory.  In particular, the list of newsgroups to
measure is taken from /usr/lib/news/active; and the
newsgroups are expected to be found under /usr/spool/news.
.SH BUGS
