.TH SP 9-EMACS "8-Aug-1985"
.UC
.SH NAME
sp, sp-from-buffer \- give possible spellings
.br
get-next-word \- return word at cursor
.SH SYNOPSIS
.B (sp)
.br
.B (sp-from-buffer)
.br
.B (get-next-word)
.SH DESCRIPTION
.I Sp
prompts for a word and then invokes the
.B sp
program with the word as an argument.
The output of the
.B sp
program, a list of words, is placed in a buffer called "sp".
If the word is found, then the cursor is positioned at the word.
If the word isn't found, the cursor is left at the start of the buffer.
In either case the mode line of the buffer indicates whether the word
was found.
.sp 2
.B Sp-from-buffer
is the same as
.B sp
except that the user is not prompted for the word; the word under or
immediately to the left of the cursor is used.
.sp 2
.B Get-next-word
returns the word the cursor is pointing at or the word immediately
to the left of the cursor if it is between words.
.SH BUFFERS USED
sp \- result
.SH FILES
/usr/local/lib/emacs/sp.ml
.br
/usr/local/sp
.SH SEE ALSO
.B sp(1-LOCAL)
.SH AUTHOR
Barry Brachman
.br
Dept. of Computer Science
.br
University of British Columbia
