.TH DMAIL 1 "6 December 1985"
.UC
.SH NAME
dmail \- an original mail like interface for mail
.SH SYNOPSIS
dmail -v -O -f [fromfile] -o [tofile] -l rcfile -L -F [field] -F [field]...
.PP
dmail user user user user...
.br
.SH GENERAL
.I Dmail
is a program which hopefully simplifies reading and organizing your mail.
It was designed to overcome several gripes people had over other mailers.
.I Dmail
uses the /usr/spool format for any folder's you create.  To simply matters
even more, it was partially modeled on standard Mail in terms of writing to
your 'mbox' and getting items from your 'spool', at least as default
parameters.  About the only other similarity between the two programs is
in the 'type', 'quit', and 'exit' commands of 
.IR dmail .
.I Dmail keeps multiple messages per file, fully compatible with standard
mail (thus folders are files rather than directories). 
.PP
.I Dmail
is not a glorified
.IR Mail ,
however.  Though most other mailers have folders, you are usually required
to read your mail in the order it comes in.  For somebody who is on three
high-volume mailing lists, it can be rather difficult.  
.I Dmail
provides a mechanism in which you can separate your mail by any partial string
in any Field without having to create a folder.  The
.I select
command is usually instantanious, and with aliases, you can switch between
mailing lists, personal mail, or anything you wish at a keystroke.  Whenever
you 
.I select
on something, you get a reduced list (as if the other messages didn't exist),
and may execute such things as 'delete all' on it without effecting other
mail.  It serves to allow you to read each mailing list (or whatever) one
at a time.
.PP
Mail-headers are a problem for many people, especially those logging in over
300 or 1200 baud lines.  In many cases, the header is larger than the message;
in any case, they can be a nuisances.
.I Dmail
will not print any fields you do not want printed.  This seems to be a better
mechanism than Mail, which allows you to exclude certain headers.  In 
.IR dmail ,
you specify what to include.  To see the entire header, you use the 
.I header
command from 
.I dmail.
.PP
Apart from that, 
.I dmail
gives you set variables, aliases, folder's, and is generally faster than
other mail programs.
.SH OPTIONS
.I Dmail
may be executed with several options, putting it in one of two modes.  Firstly,
when executed with a user-name list, 
.I dmail
will put you into the editor setting up the To: field properly and allowing you
to enter a letter which would then be sent off.  Secondly, if no user-list is
given, dmail will attempt to read mail from your spool file (or from file), and
put you into command mode.  If the mail file is empty or does not exist, you
will be told that you have no mail, and control will be returned to your shell.
The editor is specified by the enviroment variable VISUAL (Default vi).
.PP
dmail -O -v -f [fromfile] -o [tofile] -l rcfile -L -F [field] -F [field]...
.TP
.B \-O
places
.I dmail
in interactive mode, even if there is no mail to read.
.TP
.B \-v
Places sendmail in verbose mode when you mail,
reply, or forward a message. (sets the verbose variable)
.TP
.B \-f
Specify where mail should be taken from.  The default
is /usr/spool/mail/$USER.  This option without a filename specifies that 
mail should be taken from $HOME/mbox.  Otherwise, the specified filename
becomes the fromfile.  This means that by specifying just the -f option and
not the -o option will cause both the infile and outfile to be $HOME/mbox
.TP
.B \-o
Specify where 'read' mail will be written out to.  The default
is $HOME/mbox.  This option without a filename specifies that the mail
should be placed in $HOME/.mbox .  Otherwise, the specified filename becomes
the outfile.  Additionally, if both -f and -o are specified without filenames,
both the fromfile and the outfile will be set to $HOME/.mbox
.TP
.B \-l
Specify the RC file (default is $HOME/.dmailrc).  The RC file consists of a
list of
.I dmail
commands, as if they were typed in.
.TP
.B \-L
Disables sourcing of any RC files
.TP
.B \-F
This option tells 
.I dmail
to include the given field on initial mail load.  Normally, only the From:, 
To:, and Subject: fields are initially loaded.  When you specify other fields,
.I dmail
must scan your fromfile again.  When you have large amounts of mail (+50000
bytes), this can take a couple of seconds.  The -F option allows you to 
specify a field to be loaded in addition to the defaults listed above.  You
may specify multiple -F field  options.  This is only a convenience feature,
normally you don't have to worry about it.  Some people, however, have spool
files of several hundred thousand bytes and would use this option to prevent
delays later on.
.PP
.SH INTERRUPTS
.I dmail
handles the INTR character.  You may use it to break out of listings, types,
or anything else without worry of destroying something.
.SH COMMAND OVERVIEW
.PP
The basic commands for
.I dmail
are as follows (There are, of course, many commands, these are just a few):
.I list
.I type
.I header
.I delete
.I next
.I select
.I quit
.I exit
.I alias
.I unalias
.I set
.I unset
and
.I mail	
.PP
You may abbrieviate any command you wish.  It is suggested that you do not
abbreviate commands in your rc file (default .dmailrc), as any new commands 
added in later versions may change something. Using full command names in
your rc file will keep things compatible.
.PP
For many commands (e.g. delete), you may specify a message list.  You can
give numerical ranges (1-4 6-9), number lists (1 2 3 6), or any of several
reserved words, such as 'all'.  See 'help keywords' from dmail for a 
complete list.  All lists apply only to the currently selected messages.
.PP
.I list
displays parts of the headers of messages, one message per line, for all
messages currently selected.  You can set the output format with the
.I setlist
command.
.PP
.I type
prints the message text of a message.  By the way, only header
fields specified by the
.I setlist
command will be printed (default- From: To: Subject:), which is useful.
.PP
.I header
prints out the entire header of a message.
.PP
.I delete
deletes a message or message list (you can say 'delete all' to delete all
messages currently selected).
.PP
.I next
goes to the next message and type's or header's it, depending on what last was
done (type or header).
.PP
.I select
selects what you want to look at.  You can say 'select all', to select all the
messages, or selects of the form:
.TP
select Field match match match , Field match match ....
.PP
where Field is From:, To:, or any field you wish (you can abbreviate the 
fields.... Fro To, etc...).  match is a string which you are attempting to
match in the Field.  If a match is found, that message will become selected.
Thus, you can select all your personal mail with:
.TP
select Cc myname , To myname
.PP
Use the on-line help for more information on the 
.I select
or any other command.
.PP
.I quit
from
.I dmail
please.  Any unread messages stay in your spool (or fromfile), any read
messages are placed in your mail-box, any deleted messages are deleted.
.PP
.I exit
from
.I dmail
please.  Nothing is written or altered, exit without changing anything.
.I alias
is used to alias commands to other commands, or command sequences.  For 
instance, you can alias 'me' to select all personal mail:
.TP
alias me "select Cc myname , To myname"
.PP
you can alias a sequence of commands:
.TP
alias q  "select all ; pre all ; quit"
.PP
The above would unread any read mail and quit (therefore, any mail not deleted
will end up staying in your spool file).  You can also
.I unalias
aliases.
.PP
.I set
a variable to a string.  You can also
.I unset
a variable.  Several variables have special meaning, use
.I help set
from 
.I dmail
for a full explanation.
.PP
.I mail
and
.I reply
may be used to mail out or reply to messages.
.SH BUGS
.PP
Please send bug reports to:
		...!ucbvax!dillon
		dillon@ucb-vax.berkeley.edu

