.TH FROM 1L
.ad b
.SH NAME
from - list from and subject of all messages in mailbox or file
.SH SYNOPSIS
.B from
[-n]
[ filename ]
.br
.B from
[-n]
[ username ]
.SH HP-UX COMPATIBILITY
.TP 10
Level:
HP-UX/CONTRIBUTED
.TP
Origin:
Hewlett-Packard
.SH DESCRIPTION
.I From
outputs a line per message in the current users mailbox 
of the form;
.PP
<from> [subject]
.PP
If a filename is specified, the program reads that file
rather than the default file.  If the argument is a
\fIusername\fR then look for that users mailbox.
.PP
Furthermore, if the \fI-n\fR flag is specified, the headers
will be numbered using the same numbering scheme that, for
example, \fIreadmsg\fR will understand.
.PP
Filename can be specified with the same notation as
when invoking the \fBElm\fR mailer.
.SH AUTHOR
Dave Taylor, Hewlett-Packard Laboratories.
.SH SEE\ ALSO
readmsg(1L), elm(1L), mail(1), mailx(1)
.SH BUGS
Occasionally it gets confused about whether a message has
a subject or not.  This, unfortunately, is due to the
vast number of possible headers in the messages...
