.TH MESSAGES 1L
.ad b
.SH NAME
messages - quick count of messages in mailbox or folder
.SH SYNOPSIS
.B messages
.br
.B messages
folder-name
.SH HP-UX COMPATIBILITY
.TP 10
Level:
HP-UX/CONTRIBUTED
.TP
Origin:
Hewlett-Packard
.SH DESCRIPTION
.I Messages
counts the occurances of "^From\ " in either the current incoming 
mailbox or the specified folder.
.P
This is, in fact, a simple little shell script!!
.SH AUTHOR
Dave Taylor, Hewlett-Packard Laboratories
.SH SEE\ ALSO
from(1L), elm(1L)
.SH BUGS
Don't be foolish...
