.TH PRINTMAIL 1L
.ad b
.SH NAME
printmail - format mail in a readable fashion for printing
.SH SYNOPSIS
.B printmail
{-d}
{filename}
.SH HP-UX COMPATIBILITY
.TP 10
Level:
HP-UX/CONTRIBUTED
.TP
Origin:
Hewlett-Packard
.SH DESCRIPTION
.I Printmail
copies all messages from either the file specified or the
default user mailbox separated by form feeds to standard output.  
With the
.B \-d
option, the messages are separated by a dashed line
rather than the formfeed (for lots of little mail).
.sp
.P
If the program is given a file as standard input, it will
use that instead of the default mailbox for the operation
specified.
.SH EXAMPLE
A typical usage of this command is;
.nf
	printmail -d | print 
.fi
.SH AUTHOR
Dave Taylor, Hewlett-Packard Laboratories.
.SH SEE\ ALSO
elm(1L), mail(1), mailx(1), from(1L)
