.TH TRIM-HEADERS 1L
.ad b
.SH NAME
trim-headers - help keep mailbox files clean of trash headers
.SH SYNOPSIS
cat \fIfilename\fR |
.B trim-headers
> \fIfilename2\fR
.br
.B trim-headers
filename-list
.SH HP-UX COMPATIBILITY
.TP 10
Level:
HP-UX/CONTRIBUTED
.TP
Origin:
Hewlett-Packard Laboratories
.SH DESCRIPTION
.I Trim-headers
is a simple awk script that removes all headers from the specified
folder, either standard input or one of a list of filenames, according
to how it's invoked.  The program knows about the following headers;
.sp
.nf
	From 
	From:
	Subject:
	To:
	Cc:
	Date:

.fi
All other headers are considered extraneous and are removed.
.SH AUTHOR
Dave Taylor, Hewlett-Packard Laboratories
.SH SEE\ ALSO
awk(1), printmail(1L), readmsg(1L)
.SH BUGS
The current incancation of the \fIawk\fR script doesn't understand
the idea of multiple line header fields, so a message that has, say,
a three line To: list will only have the first line saved...
