.TH WNEWMAIL 1L 
.ad b
.SH NAME
wnewmail - daemon to asynchronously notify of new mail
.SH SYNOPSIS
.B wnewmail
.br
.B wnewmail
filename
.PP
.SH HP-UX COMPATIBILITY
.TP 10
Level:
HP-UX/CONTRIBUTED
.TP
Origin:
Hewlett-Packard
.SH DESCRIPTION
.I Wnewmail\^
is a daemon designed to run in \fBa window\fR on a windowing
system (such as an HP or Sun system) and check every 10 seconds
to see if there is any new mail for the user that
started it up.
.P
If there is new mail, the program will "beep", and write to
the window for each of the new messages;
.nf

   Mail from <name> -- <subject>

.fi
where <name> is either the name of the person sending it,
if available (the ARPA 'From:' line) or machine!login where
machine is the machine the mail was sent from.  If there
is no subject, the message "<no subject>" will appear on
the screen.
.P
If the message is a \fIpriority\fR message (that is, the
header contains a line "Priority:"), then the line output
will be "PRIORITY mail from ..." rather than just "Mail from".
.P
This program will run forever, and can internally reset 
itself if mail is deleted from the incoming mailbox while
trying to monitor it.
.P
If \fBwnewmail\fR is started up with a filename, it will
perform exactly the same, but with the specified file as
the one to check rather than the default users mailbox.
.SH AUTHOR
Dave Taylor, Hewlett-Packard Laboratories.
.SH SEE ALSO
notify in sh(1) or csh(1), newmail(1L)
.SH NOTE
This is almost identical to the program \fBnewmail\fR...
