.TH X10 1 local
.SH NAME
.B x10\^
- control program for the BSR X10 Powerhouse
.SH SYNOPSIS
.B x10 data \fIunit-name\fP \fIbinary-state\fP \fIid\fP
.br
.B x10 date
.br
.B x10 delete \fIrequest-type\fP \fIitem-numbers\fP
.br
.B x10 diagnostic
.br
.B x10 dump \fIrequest-type\fP
.br
.B x10 fdump \fIrequest-type\fP
.br
.B x10 finfo \fIrequest-type\fP
.br
.B x10 fload \fIrequest-type\fP
.br
.B x10 info
.br
.B x10 unit \fIunit-specifier\fP \fIstate\fP
.br
.B x10 monitor
.br
.B x10 reset [\fIhousecode\fP]
.br
.B x10 schedule \fIunit-specifier\fP \fIday-specifier\fP \fItime\fP \fIstate\fP
.br
.B x10 setclock
.SH DESCRIPTION
.I x10
is a little program for controlling a BSR X10 "Powerhouse" home
control device.  The BSR X10 can remotely control lights and appliances
in your house by signalling over the house wiring.
.PP
The BSR X10 Powerhouse connects to a computer with an RS232 interface.
It can store up to 128 events;  each event can turn on, turn off, or dim
up to sixteen slave units.  The X10 box has a battery backed up clock
which the computer can read.
.PP
Slave units are identified by a one-letter housecode ranging from A to P (for 16
different codes) and a number from 1 to 16, for a total of 256 possible
unit codes.
.PP
You could just put a bunch of "x10 unit" commands in your crontab, but
this doesn't work if your system is down for backups, or has crashed,
or if someone's tripped over the RS232 cable and unplugged it, and it
clutters up your crontab something awful.  For most uses, it's much
easier to just load the events into the X10.  You can dump the schedule
into a file (with the \fBx10 fdump\fP command),
and you can have different files for different times of
the year, for before and after Daylight Savings Time, etc.
.PP
X10 unit descriptions are kept in a file called \fBid\fR.  Each
line contains a number (1-255) and a unit description (0-39 characters),
separated by a tab.
The number represents a code that can be stored in the X10 along
with a unit id using the \fBx10 data\fR command.  If the \fBid\fR
file exists, the \fBx10 dump data\fR or \fBx10 dump all\fR commands
will print descriptions for each unit code contained in the file.
.SH COMMANDS
.IP \fBdata\fP \fIunit-name\fP \fIbinary-state\fP \fIid\fP
Loads data into "graphics" storage in X10 box.  Currently used to
record correspondence between id file identifier and unit code,
and current state of unit.
This stuff is incomplete at present.
.PP
.IP \fBdate\fP
Gets current date and time from X10 and displays it in a form suitable
for feeding to \fIdate(1)\fP as input.  Thus, you can set your system clock
by saying "date `x10 date`".
.PP
.IP \fBdelete\fP \fIrequest-type\fP \fIitem-numbers\fP
Deletes the request of type \fIrequest-type\fP with item number
\fIitem-number\fP from X10 memory.
.PP
.IP \fBdiagnostic\fP
Runs the X10 diagnostic and reports the result.  \fBCaution:\fP running
the diagnostic scrambles X10 memory, losing all downloaded events and
data.
.PP
.IP \fBdump\fP \fIrequest-type\fP
Writes a readable description of all events of type \fIrequest-type\fP
on standard output.
.PP
.IP \fBfdump\fP \fIrequest-type\fP
Writes an unreadable description (binary data) of all events of type
\fIevent-type\fP on standard output.  If you redirect this stuff to
a file, you can subsequently feed it to a \fBx10 fload\fP command.
.PP
.IP \fBfinfo\fP \fIrequest-type\fP
Like \fBdump\fP, but reads binary data in \fBfdump\fP format from
standard input, rather than reading data from the X10.
.PP
.IP \fBfload\fP \fIrequest-type\fP
Loads the X10 memory with requests of type \fIrequest-type\fP from
data on standard input in \fBx10 fdump\fP format.
.PP
.IP \fBinfo\fP
Displays current setting of X10's clock and housecode.
.PP
.IP \fBunit\fP \fIunit-specifier\fP \fIstate\fP
Sets the specified unit to the specifed state.
.PP
.SH ARGUMENTS
Most X10 commands require arguments.  They are as follows:
.TP 5
\fIhousecode\fP
housecode is a letter from a-p
.TP 5
\fIid\fP
The identification number of the unit (1-255).  It is used to associate
a description string from the ID file to a specific unit.
.TP 5
\fIitem-number\fP
An X10 event-numbers (0-127) or id-slot (0-255).
.TP 5
\fIbinary-state\fP
id-state is either \fBon\fR or \fBoff\fR
.TP 5
\fIday-specifier\fP
mode-day is in the form: (mode) ([day])
.br
Modes:
.RS 5
 \fBn\fRormal  (days)
.br
	\fBse\fRcurity (days)
.br
	\fBtod\fRay
.br
	\fBtom\fRorrow
.RE
Days:
.RS 5
\fBm\fRonday, \fBtu\fResday, \fBwed\fRnesday,
\fBth\fRursday, \fBf\fRriday,
.br
\fBsa\fRturday, \fBsu\fRnday, \fBweekd\fRay,
\fBweeke\fRnd, \fBe\fRveryday
.RE
.TP 5
\fIunit-name\fP
A name for a single unit in the form: (housecode)(unit-number)
.RS 5
housecode is a letter from a-p
unit-number is a number from 1-16
.RE
.TP 5
\fIunit-specifier\fP
A specifier for one or more units, in the form
(housecode)(unit-number[,unit-number...])
.RS 5
housecode is a letter from a-p
.br
unit-number is a number from 1-16 or a '*' to indicate all units
.RE 3
.TP 5
\fIrequest-type\fP
request is \fBevents\fR or \fBdata\fR for delete, fdump, finfo,
and fload commands
.br
request is \fBevents\fR or \fBdata\fR or \fBall\fR for dump command
.TP 5
\fIstate\fP
state is in the form: (function) ([value])
.RS 5
.B on
.br
.B off
.br
.B dim
(value)
.RS 5
value is a number from 1-16
.RE 3
.TP 5
\fItime\fP
Time is in 24 hour format of the form HH:MM
.SH EXAMPLES
.TP 5
x10 unit a5 on
Turns slave unit A5 on.
.TP 5
x10 unit b7 dim 8
Sets unit B7 to dim level 8 (levels run from 0 to 15, bright to dim)
.TP 5
x10 info
Displays X10 clock time and base housecode
.TP 5
x10 setclock
Sets ,10's clock to current time of day (from UNIX)
.TP 5
x10 schedule a3,5 security everyday 17:30 off
Enters an event to turn units A3 and A5 off every day about 17:30
.TP 5
x10 schedule a2 normal wed 5:00 on
Enters an event to turn unit A2 on every Wednesday at 5:00
.TP 5
x10 schedule b8 today 9:00 dim 9
Enters an event to dim unit B8 to level 9 today at 9:00
.TP 5
x10 dump all
Displays all events and data in X10's memory
.TP 5
x10 delete event 12
Deletes event 12 from X10's memory
.TP 5
x10 reset
Clears X10 memory, deletes all events and sets housecode A
.br
(does not clobber clock)
.TP 5
x10 reset c
Clears X10 memory, deletes all events and sets housecode C
.br
(does not clobber clock)
.TP 5
x10 diagnostic
The X10 performs its internal diagnostic routine
.br
(clobbers memory and clock, but not housecode)
.TP 5
x10 fdump data > datafile
Dumps X10 id data into file
.TP 5
x10 fload events <eventfile
Loads X10 event data from file
.TP 5
x10 finfo events < eventfile
Displays events in file produced by x10 fdump
.TP 5
x10 date
Displays date in date(1) input format.
.SH FILES
id - X10 unit description file
.SH AUTHORS
Originally written by Larry Campbell (maynard!campbell).  System V
port, ID file, improved display formats, and other cleanup by John
Chmielewski (rogue!jlc).
.SH SEE ALSO
X10 POWERHOUSE computer interface model no. CP290 programming guide
.br
date(1)
