#!/bin/ksh
PATH=/usr/ucb:/bin:/usr/bin:/usr/local/bin
case x$1 in
	x)
		echo Usage: $0 files...
		exit
		;;
esac

while :
do
	echo -n "How do you want to print these files:
screen formatted (NROFF)
printer formatted (NROFF)
typeset to printer (TROFF)
lineprinter
diablo to printer (typewriter-style)
? "
	read how
	case x$how in
		xl*)
			how=lineprinter
			break
			;;
		xs*)
			how=screen
			break
			;;
		xp*)
			how=printer
			break
			;;
		xt*)
			how=typeset
			break
			;;
		xd*)
			how=diablo
			break
			;;
		*)
			echo "Unknown printing command."
			;;
	esac
done
echo "Printing $* ..."
case $how in
	l*)
		qp -n $*
		;;
	p*)
		nroff -ms -T630-12 $* | qdiablo -12
		;;
	d*)
		qdiablo -i -12 $*
		;;
	s*)
		nroff -ms $* | ${PAGER-less}
		;;
	t*)
		qtroff -ms $*
		;;
esac
