.ds v \fIve\fR
.ds V \fIVe\fR
.ds ]W "2nd Release"
.TH VE 6 10/3/84
.SH NAME
ve - visual empire
.SH SYNOPSIS
ve [-a|c command_file] census map commodity spy ship radar coastwatch...
.SH DESCRIPTION
\*V is a screen oriented empire(6) tool to aid in decision
making and command file creation.
It has been used by kings, presidents and petty dictators
in many different countries and worlds with varying degrees of
success.
The program runs independently of empire and can thus be used
as much and whenever you wish.
.sp
\*V takes as input any number of empire commodity, census, map, spy,
ship, radar and coastwatch reports, combines the information and 
displays a map on the screen
and the census and commodity information for that sector at the bottom.
As you move your cursor from one sector to the next the information
at the bottom is updated.
You can do surveys of the land, mark sectors and save commands in
a separate command file to be executed later in empire.
If the \fI\-a\fR option is used the \fIcommand_file\fR is
appended to whereas the \fI\-c\fR option will create or
truncate the file.
.sp
The following are the commands that are understood (if not
quite executed) by \*v.
.sp
.IP q
Quit \*v.
.sp 2
.IP "Entering information:"
Many commands in \*v will prompt you for more information
at the bottom ("last line") of the screen.
The following characters have a special meaning when
entering information.
.sp
.IP BS
The backspace key will erase one character using a
backspace-space-backspace sequence.
.IP @
The @ key will erase the entire line.
.IP ESC
The ESCape key will move the cursor from the bottom line
to its current map position, wait a second and then jump back.
.IP .
The period will immediately expand to the x and y coordinates of
the current sector.
A `.' embedded into macros will get expanded when the macro is.
.IP ^P
Proposed movements may be traced on the screen and allow you to verify
moves and nav's by using the ^P command.
.IP backslash
The backslash, `\\\' will cause the next character to be interpreted
literally.
This is how `.'s are embedded into macros and how one
keeps a macro from expanding.
.IP macros
Macros are a single character that will expand to a string
as soon as they are entered.
The commands to set and delete macros are described below.
.sp 2
.IP "Movement and display functions:"
The following commands control the movement of the cursor
on the screen and the printing of the status lines and
and display.
.IP "yugjbn"
Move one sector in the specified direction.
These are the same as in empire (up and left, up and right,
left, right, down and left, down and right respectively).
.IP ^Y|^U
Move/scroll up.
.IP ^B|^N
Move/scroll down.
.IP ^G
Move/scroll left.
.IP ^J
Move/scroll right.
.IP l
Leap to a specified sector.
\*V will prompt for the x and y coordinates of the sector.
.IP P
Toggle the printing of the status lines at the bottom of
the screen (for slow baud rates).
Normally \*v will update the status lines every time the
cursor is moved, but with printing turned off, the status
lines are only printed by the `p' command below.
.IP p
Print the status lines for that sector.
Only useful if printing has been toggled off.
.IP ^F
Flip between the survey map and the designation maps.
.IP ^L
Redraw the screen.
.sp
.IP "Marking the map:"
The result of a `?' command is to mark
sectors of the map.
Sectors are marked using the \fIcurrent mark\fR
character. This can be changed without affecting
the screen allowing for multiple marks on the
same screen.
A sector is marked by placing the current mark character
(default is `>') directly to the left of the sector.
As an example of multiple marks,
you can set the current mark to `^' and
do the command "?civ>100" then set the mark to `v'
and do "?civ<5" to get a visual representation of
the high and low civilian population sectors.
.IP m
Set the current mark character.
.IP M
Reset the mark character to the default of `>'.
.IP c
Clear the current marks on the screen.
.IP C
Clear ALL of the marks on the screen.
.sp 2
.IP "Command file:"
The optional command file can be used to store notes
or commands to later be executed by empire.
\*V lets you append to the file, change or create it and
edit it without exiting the program.
.IP a
Append a line to the command file.
.IP O
Create or change the current command file.
If there is a current command file it is closed
before the new file is opened.
.IP V
Invoke the default visual editor (normally \fIvi(1)\fR)
on the current command file.  The shell variable VISUAL will be used if set.
.IP E
Invoke the default line editor (normally
\fIex(1)\fR) on the current command file.  The shell variable EDITOR will be used if set.
.sp 2
.IP "\*V Commands"
.IP ?
This command will prompt you for an expression similar
to that in empire (see Command Syntax in the empire
manual).
The effect of all `?' commands is to "mark" sectors
that satisfy the requirements of the command.
Unfortunately the command is not as robust as
it is in empire. At most two commands (separated by `&')
can be combined, not all of the items can be checked and
the item name must be on the left while the value is on
the right.
.sp
Some allowed commands would be
.in +5
.nf
?civ>100&mil<5
?country=4
?des=h&lcm<20
?del=food&contract=mil
.fi
.in -5
The items that can be accessed are:
.in +5
.ta 1.5i
.nf
civ	civilians
mil	military
foo	food
sh	shells
gun	guns
pl	planes
iro	iron
dus	gold dust
bar	gold bars
oil	oil
lcm	light construction material
hcm	heavy construction material
eff	efficiency
mob	mobility
min	mineral content
gmi	gold mineral content
fer	fertility
pet	petro content
des	designation
cou	country
del	delivery route
.fi
.in -5
Note that the above are the minimal abbreviations for the
different items.
.IP I
The I command allows more report files to be read in.  This is useful
when combined with the ! command to update your empire and look at the
results without ever exiting \*V.
.IP !
The ! command forks a shell (honors the SHELL variable).  The command
file is flushed before forking to allow its use.
.sp 2
.IP Macros:
A macro is a single character that will be expanded
immediately as typed it does not need to be space
delimited.
A `.' may be embedded into a macro and will be expanded
at the time the macro is typed.
For example, a C could be defined as "mov civ \\\.".
Then whenever a C is typed it would expand to "mov civ x, y "
where x,y are the coordinates of the current sector.
.IP s
Set up a macro.
Note that you must use a `\\\' to embed a `.' into
a macro.
.IP d
Delete a macro.
.sp 2
.IP "Surveys of the land"
It is possible to survey any appropriate item on the
commodity or census list.
A survey has a \fIrange\fR associated with it which
describes the maximum value for the item being surveyed.
When the survey is done each sector is replaced by a
single digit from 0 to 9 which indicates which tenth
of the range the value of that item occurred in.
For values greater than the range capital letters are
used up to `Z'.
After that only a `$' is printed.
The survey map is distinct from the designation map.
You can flip between the two at any time by typing `^F'.
For example, if the range is 100, the item being surveyed
is civilians and the number of civilians in the sector is
25, a 2 will be displayed.
.IP S
Perform a survey
.IP R
Set up the range for surveys.
.sp 2
.IP "Naval reports"
Normally, your opponents navies as well as your own will not be displayed.
The ship display may be turned on using the 'N' command.  At this point, the
flagship of each sector which contains a ship will be displayed in the sector
in which they reside.
Information about each ship in a sector may be obtained by moving your cursor
over the top of the sector and paging through each ship with the '+', '-',
and '/' keys.
.IP N
Toggles the ship display mode.
.IP G
Go to the sector of the specified ship.  \*V will prompt for the ship number.
.IP +
Display information on the next ship in the sector.  Ships are ordered by
their ship number.
.IP -
Display information on the previous ship in the sector.
.IP /
Display information on the flagship in that sector (ship with the lowest
number).
.sp 2
.IP "Moving along routes"
You can walk along delivery routes by setting up the
desired route with the `r' command and then typing the `w'
command.
The cursor will then move along the chosen delivery route.
.IP r
Designate a current route.
.IP w
Walk along the current route.
.SH AUTHORS
Matthew Diaz and Michael Baldwin
Modifications by Bill Jones, Jim Knutson, Ken Montgomery, Dan Reynolds
.SH "SEE ALSO"
empire(6)
.SH BUGS
Probably lots
.sp 1
The `?' command should be identical
to that in empire.
.sp 1
Some contortions of radar scans may not work.
.sp 1
Surveys with ships may leave survey values on the designation map.
.sp 1
New ship reports don't replace the old values (read using the I command).
.sp 1
Command files that are removed in a forked shell will reappear.
.sp 1
The erase and line kill characters
should be taken from the environment.
