
.TH UUKILL 1 LOCAL
.SH NAME
uukill \- remove job from UUCP queue
.SH SYNOPSIS
.B uukill
.I jobid
.SH DESCRIPTION
.I Uukill
takes a job ID displayed by the
.IR uuque (1L)
program and removes the spool files for that job.
You must not only have read/write access in the UUCP spool directory,
but only the superuser or the owner of a job can kill the job.
It has been tested with SystemIII UUCP, and should work with V7, SystemIII
and some System V UUCP's.
It has not been tested with Honey DanBer UUCP.
It does not yet work under the 4.2BSD UUCP, although this is being
worked on; the program will dynamically determine whether the structure
is ``flat'' or arranged in directories and act accordingly.
.SH BUGS
Should be more secure so that it can run setuid.
