.TH UUQUE 1 LOCAL
.SH NAME
uuque \- Show uucp job queue
.SH SYNOPSIS
.B uuque
[
.I \-j
] [
.I \-v
] [
.IR \-s site
]
.SH DESCRIPTION
.I Uuque
is a program to print out status information about the UUCP queues for
the indicated site.
It has been tested with SystemIII UUCP, and should work with V7, SystemIII
and some System V UUCP's.
It has not been tested with Honey DanBer UUCP.
It does not yet work under the 4.2BSD UUCP, although this is being
worked on; the program will dynamically determine whether the structure
is ``flat'' or arranged in directories and act accordingly.
.PP
The program displays the jobs spooled for the indicated site, their size,
and a total size of all the jobs.
Two flags may be specified to get additional output:
.TP \-j
Print the job ID's with each job.
.TP \-v
Print the subjects and newsgroups of news and/or mail messages.
.PP
You must have read permission in
.I /usr/spool/uucp
for this program to work.
.SH BUGS
Only one system can be displayed at a time.
