.TH VMSWRITE 1 MAN.CS.UX
.SH NAME
vmswrite \- write a Files-11 tape
.SH SYNOPSIS
.B vmswrite 
[
.B \-abfnrv
] name ...
.SH DESCRIPTION
.I vmswrite 
writes a Files-11 tape which may be read on an RSX or VMS system.
A multifile, single volume tape is written, consisting of the
specified files.
The tape is created as though it was written on a PDP-11 with RSX-11M.
Tapes written by this program have been successfully read under
RSX-11M (Version 3.2) and VMS (Version 2.2, 2.3 and 2.4).
.PP
The
.B -a
option will append the files to the end of an existing Files-11
tape, that is, the VOL1 record is not written.
To do this, the tape is rewound and the files are counted, up
to the double end-of-file that marks the logical end-of-tape.
The new files are appended to the tape, with the file number
entry of the HDR1 label picking up where the previous files left off.
.PP
The
.B -b
option will use the next command line argument as the tape block
size in bytes, rather than the default of 2048 bytes.
Any value greater than 512 will force one to use something like
``/BS:2048.'' on the PIP command line under RSX.
.PP
The
.B -f
option will use the next command line argument as the tape device,
rather than the default of
.I /dev/rmt0
(drive 0, raw mode, 1600 bpi).
The argument must be a tape device name.
.PP
The
.B -n
option will not rewind the tape at the end.
If this option is not specified, then by default the tape is rewound
when finished.
This option is of no practical interest.
.PP
The
.B -r
option will use the next command line argument as the record size,
implying that fixed-length records are to be written.
The block size (specified by the
.B -b
option, or the default of 2048 bytes), must be evenly divisible
by the fixed-length record size.
Furthermore, the size of the UNIX file must be evenly divisible
by the fixed-length record size.
This option specifies that
.I all
files being written to the tape are fixed-length records having the
same size records.
If you wish to intermix variable-length records (normal text files)
with fixed-length records, use the
.B -a
option and execute
.I vmswrite 
as many times as needed.
.PP
The
.B -v
option may be used to produce a verbose output, with the name
of every file being written to the terminal as the file is written
to tape.
Normally
.B vmswrite 
does its work silently.
.PP
All lower case alphabetics in the filenames are converted
to upper case, since this is required by RSX (but not VMS!).
All directory prefixes are removed from the filenames
(all characters up to, and including, the final '/') so that
a filename of the form "/usr/xyz/file1.f" would have a filename
on the HDR1 label of "FILE1.F".
The volume id of the tape is set to the six character string
"BSD4.2".
The creation date and the expiration date on the HDR1 label are set
to the date of last modification of the UNIX file.
This date corresponds to the date shown with the "ls -l" command.
.SH SEE ALSO
vmsread(1)
.SH FILES
/dev/rmt?
.br
/dev/nrmt?
.SH BUGS
The UNIX protection of the file is not converted to the DEC
equivalent, instead the protection of the files on tape are
"RWED" for everybody.
It should be possible to change the volume id.
.SH AUTHOR
The Department of Computer Science
.br
University of Manchester
.br
Oxford Road
.br
Manchester M13 9PL
.br
ENGLAND
.br
UUCP:- ...!mcvax!ukc!uk.ac.man.cs.ux!software
.br
JANET:- software@uk.ac.man.cs.ux
.br
ARPA:-  software%uk.ac.man.cs.ux@ucl.cs
.br
