.TH FTIMES 1
.SH NAME
ftimes \- display access, change and modify times of a file
.SH SYNOPSIS
.B ftimes
[
\fB\-acmv\fR
] file
.SH DESCRIPTION
.IR Ftimes
displays the access, change and modify times of a file in seconds
past the epoch (1 January 1970).
This is useful for making decisions in shell scripts.
.PP
Flags a, c and m select the corresponding times.
The v flag displays output in human readable form
ie. Sat Nov  9 16:40:22 CST 1985
If no option, or only the v flag is selected,
the default is the modify time.
.PP
Example:
.br
.nf

.in +5
if test `ftimes RCS/file,v` -gt `ftimes file`
then
	co file
fi
.in -5

.fi
is a shell script to check out a RCS file if a newer version
has been checked in since the working version was created.
.SH AUTHOR
Ken Yap (University of Rochester)
