.TH RPS 1
.SH NAME
rps - convert image files to PostScript
.SH SYNOPSIS
.B rps
[file] [-w r1 c1 r2 c2] [-c n] [-i nr nc]
.SH DESCRIPTION
.I rps
converts an image file into postcript language, which may then be printed
on a Laser Writer with
.I lpr
.PP
When given a file name as an argument,
.I rps
reads the named file as an input image.  The image is read as a 1 byte per
pixel image.  The image size is assumed to be 256 rows by 256 columns.  The 
.B \-i
option may be used to specify the size of the input if it is not 256 * 256.
The two arguments following the 
.B \-i
option are taken as the row and column dimensions.
.sp
The
.B \-w
arguments specify an output window on the Laser Writer.  The page in specified
in a row-column coordinate system, with 3300 rows and 2550 columns.  There are
300 pixels per inch.
.sp
The 
.B \-c
argument specifies the number of copies of the image to be printed.
.SH AUTHOR
Marc Majka
