.TH MDUMP 8 "UofI CSO"
.SH NAME
mdump \- multiple dump per tape utility
.SH SYNOPSIS
.B mdump
[
.B \-d
] [
.B \-w
] [
\fB\-wl \fIn\fR
] [
\fB\-dl \fIn\fR
] [
.B \-l
] [
.B \-e
] [
\fB\-t \fIday-of-week\fR
] [
\fB\-f \fI[host:]/dev/rmtx\fR
]
.SH DESCRIPTION
.I Mdump
simplifies the backup procedure for systems with multiple filesystems
by putting all daily and/or weekly backups onto a single tape.
.PP
The order and selection of filesystems to be dumped is determined by
.I /etc/dumptab 
and by the options
.BR \-d ,
.BR \-w ,
\fB\-dl \fIn\fR and
\fB\-wl \fIn\fR.
.B \-d
selects daily backups to be done at the default daily dump level of 5;
.B \-w
selects weekly backups with a default dump level of 4.
The
.B \-wl
and
.B \-dl
switches respectively take the weekly and daily dump level from the following
argument
.IR n .
Specifying both of (
.B \-d
and
.B \-w
) or (
.B \-dl
and
.B \-wl
)
causes daily and weekly backups to be selected.
A dummy file is inserted on the tape for non-selected filesystems
to preserve file ordering.
.PP
The
.IR st (8)
command (set tape) will position the backup tape to the correct tape
file for restores.
.PP
The backup device is selected with the
.B \-f
option.
Remote backup over the network is accomplished by specifying the device
name in the same manner as
.IR rdump (8),
e.g., uiucuxc:/dev/rmt0.
.PP
After
.I mdump
has finished writing the dump files,
a listing of each dump will be created and sent to the \s-1IBM\s0 printers
unless the
.B \-l
option is given to suppress the listings.
.PP
In the case of positioning errors during the listing phase of
.IR mdump ,
hanging rsh commands are the usual cause,
.B \-e
will execute the listing phase of
.I mdump
only.
At least one of the flags
.B \-d
and/or
.B \-w
must be specified in addition to the
.B \-e
flag.
.PP
To run
.I mdump
as though it were a different day of the week, e.g.,
create or list a Monday tape on Wednesday, the 
\fB\-t \fIday-of-week\fR
flag is supplied where
.I day-of-week
is one of mon, tue, wed, etc.
.SH NOTES
In the case where
.I mdump
found no files to dump,
the subsequent listing phase will complain that
it "Cannot find file dump list".
.I Mdump
will print a message saying that the list command exitted abnormally
and ask whether to continue.
Entering 'y' directs
.I mdump
to continue listing the other filesystems.
Any other response causes an exit.
.SH FILES
/etc/dumptab, /etc/dump
.SH "SEE ALSO"
dumptab(5), dump(8), rdump(8), st(8)
.SH BUGS
No provision is made for tape overflow.
This is an incentive to use 6250 bpi drives.
.PP
Any tape error means restarting
.I mdump
from the beginning.
