.TH SUBDIRS 1 "12 October 1984"
.SH NAME
subdirs \- print sub-directories and symbolic links
.SH SYNOPSIS
.B subdirs
[-l] [directory name]
.SH DESCRIPTION
.I Subdirs
lists the names of all the sub-directories below the directory indicated
by the parameter given.
If the directory is not supplied, "." will be assumed.
The program will report any mounted file systems and symbolic links
encountered as it scans the directories.
Normally, to speed up
.IR subdirs ,
directories with no subdirectories (link count = 2) are not scanned.
The
.I \-l
flag causes these to be scanned; finding
.B all
symbolic links, but with a speed penalty.
.SH DIAGNOSTICS
A pathname ending in
.B "/..."
indicates a subdirectory nested too deeply for subdirs to handle.
.SH "SEE ALSO"
du (1), ls (1), mount (8)
.SH AUTHOR
Stephen J. Muir, Lancaster University.
