.TH DTREE l
.SH NAME
dtree \- print directory tree structures
.SH SYNOPSIS
.B dtree
[
.B \-adfglnpsvx
]
[
.B \-b filenamesize
]
[
.B \-c linelength
] [ directory1 ...]
.SH DESCRIPTION
.I Dtree
is a program to print out the tree structure of directories
and their children. If no directories are specified,
.I dtree
takes the current working directory to be the top of the tree
structure.  It prints out just the directory structure by default.
If no flags are specified,
.I dtree
prints out just the directory structures.
Recognized options are as follows:
.TP
-a
Include files in printout (excluding entries beginning with '.')
.TP
-b
Take the next argument to be the maximum length of a directory name; default
is 14 characters, or the value associated with a -c argument, if any.  
any directories with names longer than this length will not be searched, thus
any files and directories within them will not be included in the output.
.TP
-c
Take the next argument to be the length of each
column of the printout. (By default, this is 14, the
maximum filename length.  Any lengths greater than
the column width are truncated accordingly, and the last character which
fits into the column is replaced by an asterisk.)
.TP
-d
List directories first. For each directory, its subdirectories
will be listed first, and then all its other entries.
.TP
-f
List files first. Reverse of -d.
.TP
-l
Long listing. Useful information is printed to the right of
each entry. The name of the owner, its size in blocks, and its mode are printed.
.TP
-g
Same as the -l flag, except that the group name is used instead of
the owner name. If both the -l and -g flags are used, both the
owner and group will be printed.
.TP
-n
No sort. Names are listed in the order they are read
from the directory.
.TP
-p
Include entries beginning with '.' (excluding "." and "..").
.TP
-s
Simplify the long listing. Prints uid, size in blocks, and octal mode of the
file. This flag implies the -l flag unless the -g flag is specified.
.TP
-v
Disable variable length columns.  Normally columns are of variable length.
Rather than using the same
width for each column of output, each column is shortened as much as
possible without truncating any names.
.TP
-x
Do not cross file systems.  Dtree will not cross over to a
subdirectory if it is on a different file system.
.SH AUTHOR
Dave Borman, Digital Unix Engineering Group
.br
decvax!borman
.br
Originally written at St. Olaf College, Northfield, MN.
