# This data file was generated by the Spreadsheet Calculator.
# You almost certainly shouldn't edit it.

format A 25 0
rightstring A0 = "Account Description"
rightstring B0 = "Cash Tri"
leftstring C0 = "al Balance"
rightstring B1 = "Debit"
rightstring C1 = "Credit"
leftstring A2 = "Closing Cash"
let B2 = 415.13
leftstring A3 = "Closing Money Fund"
let B3 = 1052.77
leftstring A4 = "Closing Savings"
let B4 = 200
leftstring A6 = "Advances: HMS"
let B6 = 395.01
let B8 = @sum(B2:B7)
let C8 = @sum(C2:C7)
