.TH VNEWS 1
.SH NAME
vnews \- read news articles
.SH SYNOPSIS
.BR vnews " [ " \-a
.IR date " ] [ "
.B \-n
.IR newsgroups " ] [ "
.B \-t
.IR titles " ] [ "
.BR \-rxhfuA " ] [ "
.BR \-c " ]"
.PP
.B "vnews \-s"
.SH DESCRIPTION
.SS "Overview"
.. .RS 5
.B Vnews
is a program for reading USENET news.
It is based on
.BR readnews (1)
but has a CRT oriented user interface.
The command line options are identical,
but only the options listed in the synopsis are supported.
The effect of the
.B -c
option is different in vnews than in readnews; it
causes vnews to display the entire first page of an article
immediately rather than initially showing only the header.
The
.B -A
option causes the newsgroup index to be displayed each time
a new group is entered.
The list of available commands is quite similar, although since
.B vnews
is a "visual" interface, most
.B vnews
commands do not have to be terminated by a newline.
.B Vnews
is somewhat less friendly than
.BR readnews ,
so new users should probably start out with readnews.
.. .P
.. .B Vnews
.. is an experiment in writing a good user interface.
.. The only way I can tell how successful I have been is by the responses I
.. receive, so please send you comments, good or bad, to
.. {harpo|ihnp4|burl|ucbvax!mhtsa}!spanky!ka.
.. (Bug reports should be sent to the same address.)
.P
.B Vnews
uses
all except the last two
.. all except the first two
lines of the screen to display the current article.
The second to the bottom line
.. Line 2
is the secondary prompt line, and is used to input string arguments
to commands.
The bottom line
.. Line 1
contains several fields.
.. The first field is the prompt field.
.. If
.. .B vnews
.. is at the end of an article, the prompt is "next?"; otherwise the prompt is
.. "more?".
The first field contains an approximation of the percentage of the
article that has been read.  It will be 100% if and only if the entire
article has been read.
.. [This is a more informative (and cryptic) replacement for the
.. more/next indication.]  \
..
The second field is the newsgroup field, which displays the current
newsgroup, the number of the current article, and the number of the last
article in the newsgroup.
The third field contains the current time, and the last field contains the
word "mail" if you have mail.
When you receive new mail, the bell on the terminal is rung and the
word "MAIL"
appears in capital letters for 30 seconds.
.RE
.P
.SS "Differences from Readnews"
.. .RS 5
Most of the readnews commands have
.B vnews
counterparts and vice versa.
Commands are not present in
.B Vnews
include:
.TP 10
.B d
The digest command is not yet implemented.
.TP 10
.B K
You can get the same effect by using the
.B n
command with a huge count.
.TP 10
.B P
Use "N-".
.TP 10
.B X
This should be a separate program.
.P
.B Vnews
has commands for moving around in the article which readnews does not have
since they aren't applicable.
It also has a
.I parent
command which will go to the article that the current article is a followup
to, and a
.I write
command that writes out the body of an article without the header.
.P
You can refer to the current article from the shell or while writing a
followup as $A.
.P
You can use the
.B n
command to delete articles while looking at the index page.
.. .P
.. The
.. .I decrypt
.. command always does rotation 13.
.. .P
.. The algorithm for handling articles posted to multiple groups is different;
.. .B vnews
.. attempts to show you these articles only once even if you quit in the
.. middle of running
.. .B vnews
.. and resume it later.
.. .P
.P
.SS "Article selection algorithm"
.P
Newsgroups are shown in the order that they appear in the .newsrc file.
Any newsgroups which contain articles but do not appear in the .newsrc
file are appended to the .newsrc file in the order in which they appear
in the groupfile file.  (This means that if the -x option is specified
you will be shown newsgroups in the order in which they appear in the
groupfile file.)
.P
Vnews has a newsgroup stack which allows the commands
.BR N ,
.BR p ,
and
.B <
to save the current newsgroup.
Only real newsgroups are pushed; not single articles fetched using the
.B p
and
.B <
commands.
The phrase "advance to the next newsgroup" always means
"pop the newsgroup stack if it is nonempty; otherwise go to the next
newsgroup in the .newsrc file."
.P
Within a newsgroup, articles are grouped by discussion.  Within a
discussion, articles are sorted by posting date.  Discussions are
sorted by the posting date of the first new article in the discussion.
.P
Articles within a newsgroup are numbered by
.B vnews
so that you can refer to them.
These numbers are not related to the names of the files containing the
articles.
.P
An article is normally considered to be read if you have
seen the end of it.
The
.B n
and
.B e
commands allow you to explicitly mark an article as read or unread.
.P
When an article has been posted to multiple group, vnews will show
the article only in the leftmost newsgroup in the newsgroup list that
you subscribe to.
.P
.SS "Commands"
.P
Each
.B vnews
command may be preceded by a \fIcount\fR.
Some commands use the \fIcount\fR; others ignore it.
If the \fIcount\fR is omitted, it defaults to one.
Some commands prompt for an argument on the secondary prompt line.
The argument is terminated by a return.
Standard
.SM UNIX
erase and kill processing is performed on commands being entered.
An interrupt (delete or break) or a CONTROL-G
gets you out of any partially entered command.
.P
The following commands exist:
.TP 10
.B SP
A space scrolls forward.
.. [Normally space advances an entire page, but if there are
.. only one or two more lines left in the current article,
.. space will simply advance the article the one or two lines
.. required to show the rest of the article.]  \
..
If you are at the end of a article, it advances to the next article.
If you are at the end of the index, it leaves the index and displays
the current article.
.TP 10
.B "^B"
A CONTROL-B goes backwards \fIcount\fR pages.
.TP 10
.B "^D"
Go forward \fIcount\fR half pages.
.TP 10
.BR "^N" " or " "^Y"
Go forwards \fIcount\fR lines.
.TP 10
.BR "^P" " or " "^Z"
Go backwards \fIcount\fR lines.
.TP 10
.B "^U"
Go backwards \fIcount\fR half pages.
.TP 10
.B a
Switch the display between the index and the current article.
The index is identical to that produced by the
.I readnews
.B a
command except that articles which have been read are marked with "D".
All
.I vnews
commands except
.B D
are functional on the index; the article scrolling commands
scroll the index and all other commands apply to the current article.
[In particular, you can type a sequence of
.BR n 's
and
.BR e 's
on the index page to quickly get rid of uninteresting articles.]
.TP 10
.BR "b" " or " "-"
Subtract \fIcount\fR from the current article number.
If the result would be less than one, an error message is printed.
.. [It would be nice to have a command which
.. always go back to the previous article like the 'b' command in 2.10.]
.TP 10
.B c
Cancel the current article.
.B Vnews
prompts for confirmation before canceling the article.
Carriage return or 'y' means yes; anything else means no.
.TP 10
.B "D"
Decrypts a joke.
It only handles rot 13 jokes.
The
.B D
command is a toggle; typing another D re-encrypts the joke.
.TP 10
.B e
Mark the current article as not read and advance \fIcount\fR unread articles.
If there are fewer than \fIcount\fR unread articles left in the
newsgroup, advance to the next newsgroup.
.TP 10
.B h
Go back to the top of the article and display only the header.
.TP 10
.B H
Show the complete header.
Typing
.B l
(or almost any command)
will restore the original display.
.. [I'm still not convinced of the value of this command,
.. but other people seem to be...]
.TP 10
.BR "l" " or " "d"
Causes the current article to be displayed.
Display of the current article is turned off by commands which scramble the
screen
.RB "(" "!" ","
.BR "f" ","
and
.BR "r" ")."
.. My feeling here is that the user frequently wants to respond to an article
.. and then go on to the next article; she/he shouldn't be forced to wait while
.. the current article is rewritten to the screen.
The
.B l
command will also redisplay the article if the help message
or detailed header is currently
displayed.
The (feeble) mnemonic significance of
.B l
is that is similar to control-L, which redraws the screen.
.. [Blanking out the article display has been of rather questionable value
.. since release 2.10, when checks for pending input were added.
.. However, the 3B20 hardware buffers about 256 characters of output,
.. and some versions of UNIX may not support checks for pending input,
.. so I have left it in.  It is straightforward enough if you are used to
.. it.]
.TP 10
.B n
Mark the current article as read.
Then advance by \fIcount\fR unread articles, marking the skipped articles as
read.  If there are fewer than \fIcount\fR unread articles left in the
newsgroup, mark the unread articles as read and advance to the next
newsgroup.
.TP 10
.B N
Go to a different newsgroup.
You are prompted for a newsgroup name.
.IP "" 10
There are two special cases.
A null newsgroup name 
it advances to the next group.
The name "\-" pops everything off the newsgroup stack and then backs
up to the previous group in the .newsrc file.
[This isn't implemented properly yet; the
current code backs up to the previous group that contains articles,
just like in 2.10.
It should restore the previously read group.]
.IP "" 10
Otherwise, the
.B N
command
.. discards everything on the newsgroup stack,
pushes the current group onto the stack and goes to the specified group.
Both read and unread articles are included in the index.
However, the
.B n
and
.B e
commands will skip over the articles that have been already read.
.TP 10
.B p
Gets you the parent article (the article that the current article is a
followup to).
If no
.B References:
line exists for the current article then the title of the article will
be used to guess the parent; of course this guess may be wrong.
.TP 10
.B "q"
Quit. The .newsrc file is updated.
.TP 10
.B r
Reply to the author of the article.
See the
.B f
command for details.
.TP 10
.B f
Post a followup article.
No warning messages are printed.
[I despise them, and so far nobody has asked for them.]
If the article was posted to a moderated group, the followup is mailed to the
sender of the article.
.IP "" 10
Both \fIreply\fR and \fIfollowup\fR work similarly.
A file containing a header is created and an editor is invoked on the file.
You can modify the header as well as enter the body of the article.
The environment variable
.B "$A"
is set to the current article in case you want to refer to it or quote it in
your response.
.B "$A"
will also be passed as an argument to the editor.
.IP "" 10
If you plan to quote extensively from the article you are writing a followup
to, you may find it easiest to include the entire body of the parent article
and delete the parts you don't want.  If you use EMACS (either Gosling's
or Warren Montgomery's), there is a macro called gparent (get parent article)
which is normally bound to ^X^Y
that reads in the body of the parent article, prefacing each line with a
.BR > .
If you use a different editor, such as
.BR ed (1),
there is a shell procedure which will accomplish the same task if your
editor has the ability to capture the output of a command.  In
.BR ed ,
type
.BR "r\ !gparent" .
.. The second argument to the editor is
.. .IR "$A" ,
.. so that if you run Gosling's Emacs, the article will automaticly appear in
.. the second window.
.IP "" 10
If you change your mind about replying or posting a followup article, exit
the editor without changing the file.
.. [A message will appear on the screen to inform you that the response was not
.. mailed/posted.]
If you change your mind about whether you should have used an
.B f
or
.B r
command, edit the first line of the followup.
.. .IP "" 10
.. [Vnews forks off a process to deliver the reply or followup.
.. In order to avoid messing up the screen, errors are reported by mail.]
.TP 10
.B s
Prompts for a filename and writes the article to the file.
Depending on how the netnews administrator set up your system, the article
may have a "From " line in front of it to allow the file to be read using
your mail program.
.IP "" 10
The
.I save
and
.I write
commands normally append to the specified file,
but if
.I count
is zero any existing file is overwritten.
.IP "" 10
If the filename does not begin with a slash
vnews runs through the following list of kludges.
If the filename is omitted, it defaults to "Articles".
A leading "~/" on the filename is replaced by the name of your login directory.
Finally, if the filename is does not begin with a slash and the environment
variable $NEWSBOX is set, then any "%s" in $NEWSBOX replaced
by the current newsgroup and the result is prepended to the filename.
.. Users frequently set $NEWSBOX to the name of their login directly.
.TP 10
.BR "s|" ", " "w|"
Read a command and pipe the article into it.
The article is formated identically to the
.B s
and
.B w
commands.
.TP 10
.B ud
Unsubscribe to the current discussion.
[This command is still somewhat experimental.
In particular, if you unsubscribe to very may groups reading and writing
the .newsrc file becomes very slow.]
.TP 10
.BR ug " or " un
If \fIcount\fR is nonzero, unsubscribe to the current group and advance
to the next group.
The group will no longer be shown to you unless you specificly ask for
it with the
.B N
command.
If \fIcount\fR is zero, resubscribe to the current group.
.. [This is a two character command to ensure that it is not typed accidentally
.. and to leave room for other types of unsubscribes (e. g. unsubscribe to
.. discussion).]
.TP 10
.B v
Print netnews version.
.TP 10
.B w
Like
.B s
except that the article header is not written.
.TP 10
.B "+"
Add \fIcount\fR to the current article number.
If this would go beyond the end of the current newsgroup an error
message is printed.
.TP 10
.B "^\e"
When sent a quit signal,
.B vnews
terminates without updating .newsrc.
Depending on how your system administrator set up vnews
it may or may not generate a core dump.
[This command is intentionally hard to type.]
.TP 10
.B "!"
Prompts for a
.SM UNIX
command and passes it to the shell.
The environment variable
.I $A
is set to the name of the file containing the current article.
If the last character of the command is a "&", then the "&" is deleted and
the command is run in the background with stdin, stdout and stderr redirected
to /dev/null.
If the command is missing, the shell is invoked.
Use the
.B l
command (or essentially any other command) to turn on the display after the
program terminates.
.. .TP 10
.. .B "#"
.. Prints the numbers of the current article and the last article in the current
.. newsgroup.
.TP 10
.B "^L"
Redraws the screen.
CONTROL-L is not a real command; it may be typed while in the middle of
entering another command.
.TP 10
.B "<"
Prompts for an article ID or the rest of a message ID,
and displays the article if it exists.
.TP 10
.B CR
Carriage return goes to the article numbered \fIcount\fR in the current
newsgroup if count is specified.
If count is omitted, then a carriage return is treated like a space.
.TP 10
.B "?"
Displays a synopsis of commands.
The synopsis will be removed from the screen when the next command is
executed.
If you want to remove the synopsis without doing anything else, use the
.B l
command.
.SH AUTHOR
Kenneth Almquist
.br
{harpo, ihnp4, burl, akgua}!hou3c!ka.
.SH BUGS
Netnews release 2.10.2 stores dates in GMT, which is probably not
what the user expects.
.P
As with other visual interfaces,
.B vnews
does not handle typing errors gracefully.
Perhaps there should be an "undo" command.
.P
No "digest" command is provided.
.P
The
.I save
and
.I write
commands should create nonexistent directories.
