.TH Talk 1
.SH NAME
talk \- talk to another user
.SH SYNOPSIS
.B talk user [ tty ]
.SH DESCRIPTION
.PP
Talk is a utility that enables two users to interactively
communicate on a character basis on split screens.
It is intended to supersede the write utility for interactive
use by providing a more useful service.

Talk is invoked with a user name and an optional tty name thus :-

        talk user [ tty8 ]

.PP
If user happens to be logged in more than once and no tty name is
supplied, talk will use the first entry in /etc/utmp (as used by who).
.PP
Talk will then attempt to notify the requested user that you are
trying to talk with him.
Trying to talk to a user may fail for two reasons :-

        The requested user is not logged in.

        The requested user has disabled messages (via mesg)

.PP
If the user doesn't answer, talk will keep notifying him.
After a reasonable number of retries, talk will give up and exit.
.PP
To reply to a user trying to talk to you, you should type
talk user (as shown in the request message).
.PP
When your party has connected you may both begin to talk (this
will be indicated by the bell ringing on your terminal).
The name of the person you are talking to and an elapsed time
indicator will appear in the centre of the screen.
You will notice that there are bursts of input and
output - this is due to the way they are handled within talk.
In order to avoid busy waiting, a sleep of one
second occurs whenever there is no activity.
.bp
.PP
Certain characters when typed have special meaning :-


ctrl-l    -    Refresh the screen.  Useful if the
               screen gets corrupted.

ctrl-d    -    Disconnect - finish talking.

ctrl-g    -    Ring the bell on other users terminal.

delete    -    Delete the character before the cursor
               (works backwards over lines as well).
               Uses your normal delete key.

ctrl-c    -    Forced exit.  This has the same effect
               as disconnect, although it may be
               used at any stage of the proceedings
               (ie. before connection has occured).


.SH FILES
/etc/utmp               to find recipient's tty
/tmp/tr_xxxxxxxx        temporary files (named pipes) for
/tmp/tw_xxxxxxxx        communication pickup
.SH BUGS
.PP
One second delay between bursts of activity (to be fixed when using
version 8).
.PP
Restricted to the domain of current machine.
