.TH JUNKMAIL 8 
.UC 4
.SH NAME
junkmail \- delete undesired mail from /usr/spool/mail
.SH SYNOPSIS
.B junkmail \fR[\fB-a\fR] [\fB-w\fR] [\fB-dn\fR[\fB-m\fR]] [\fB-u\fRusername] [directory]
.SH DESCRIPTION
.I Junkmail
is designed to cope with overuse of /usr/spool/mail.
It searches 
/usr/spool/mail/*
for old and/or large letters and deletes them,
leaving a message informing the user of this action.
It may also be used to delete all mail from a specified user.

The following options are interpreted by 
.I junkmail.
.TP
.B \-a
Select an audit trail.
.TP
.B \-w
Specifies that shortened files are to be written, 
containing letters that indicate what has been deleted.
Otherwise, only an audit is performed.
.TP
.BI \-d n[-m]
Specifies that the following number
.I
n
or range of numbers
.I
n-m
defines the age of discarded letters.
A letter newer than
.I
n
days will only be discarded if the mail file
exceeds the limit by 100%.
A letter between
.I
n
and
.I
m
days old will be discarded if the mail file exceeds the size
limit.
A letter older than
.I
m
days will always be discarded.
.I
N
defaults to 7;
.I
m,
to 21.
If a single value is specified, it is taken to be
.I
m,
and 
.I
n
is assumed to be 7.
Of course,
.I
m
must be greater than
.I
n.
.TP
.B \-u\fRusername
specifies that all mail originating from user
"username" 
be deleted, whether or not it satisfies the aging constraints.  
All other mail will be untouched, and no letter informing the
recipient(s) of the deletion will be left.
.TP
[directory]
is the optional mail directory name,
with "/usr/spool/mail" as the default.
.SH FILES
/usr/spool/mail/*
.SH "SEE ALSO"
mail(1)
.SH BUGS
When an individual username is selected,
.I
junkmail
cannot cope with large files and prints a message to that
effect rather than deleting the letters.
