.TH VPLOTDB 1 AMPEX
.SH NAME
\fBvplotdb\fR \- debugging graphics filter
.SH SYNOPSIS
\fBvplotdb\fR [file ...]
.SH DESCRIPTION
.I Vplotdb
causes the named files of
.I vplot(5)
vector plotting
instructions to be checked for errors and printed in
readable form on the standard output.
If no file names
appear the standard input is assumed.
An invalid vector plotting instruction will produce a diagnostic.
Plain ASCII characters between the vplot instructions are distinguished
from the instructions.
.LP
The standard coordinate range of 16384 pixels is mapped to the
floating point coordinate 1.00.  For example, a move instruction to
the coordinate (8191,4095) prints as
.br
     'm' 0.500 0.250
.br
These coordinates are the same as the root frame of the
.I stdplt(Vol. 2B)
library package.
.SH DIAGNOSTICS
Invalid vplot instructions cause messages.
Any lower-case ASCII letter with the 0200 bit turned on is considered
to be a possible vplot instruction.  Normal ASCII characters and the
remaining characters with 0200 are passed to the standard output
file.
.SH FILES
.nf
.ta 12
*.vp	standard naming convention for vplot input files
.SH "SEE ALSO"
mp(1), tek(1), rplot(5), vplot(5), stdplt(Vol. 2B)
.SH AUTHOR
Rob Clayton, Stanford University
.br
with modifications by John Nickolls, Ampex Corp.
.SH BUGS
