.TH SUNVIEW 1
.SH NAME
sunview - view an image file on a Sunwindows GFX-Window
.SH SYNOPSIS
.B sunview
[image] [-r nrows] [-c ncols] [-a amplitude] [-p period]
.SH DESCRIPTION
.I sunview
reads a raster image file and displays a halftone rendition in a
sun gfx-window.  The input image size is specified by the
.B -r
and
.B -c
options. The default image size is 256 rows and 256 columns.  The
input image is expected to be 1 byte per pixel.  The image is resized
to fit into the available window space. A modulation technique is used
for halftoning. The amplitude and period of the modulation may be changed
with the 
.B -a
and
.B -p
options.  The default amplitude is 75.0, the default period is 5.
.SH AUTHOR
Marc Majka  -  UBC Laboratory for Computational Vision
