.ie t \{
.ds Q ``
.ds U ''\}
.el \{
.ds Q ""
.ds U ""\}
.de QU
\\$3\\*Q\\$1\\*U\\$2
..
.TH OFF 1 "December 21, 1986"
.SH NAME
off \- run ditroff or nroff with appropriate preprocessors
.SH SYNOPSIS
.B off
[
.B \-m
] [
.B \-n
] [
.B \-P
] [
.B \-p
] [
.BI \-x nnn
] [ troff option ... ] [ file ... ]
.SH DESCRIPTION
.I Off
reads the argument files, or the standard input if there are none.
If the first line is an
.IR nroff/troff (1)
comment beginning with \e", .\e", or \'\e",
.I off
treats the remainder of the line as a shell command through which
the input is to be piped.
For example, a file beginning with
.RS
.PP
\&.\e"    tbl | eqn | ditroff -me
.RE
.PP
will be piped through
.IR tbl (1),
.IR eqn (1),
and
.IR ditroff (1).
.PP
.I Off
uses
.I ditroff
as the default text processor.
Normally any word that ends in -troff or -nroff is converted to
.QU ditroff,
and
.QU neqn
is converted to
.QU eqn.
If
.B \-n
is specified,
.QU nroff
is used instead,
.QU eqn
is converted to
.QU neqn,
and
.QU pic
is suppressed unless
.B \-P
is specified.
The
.B \-p
option may be used to pipe the output through
.IR lpr (1);
if
.I nroff
is used, the output will first be piped through
.IR col (1)
to remove half line feeds.
An argument of the form
.BI \-T device,
.BI \-r aN,
or
.BI \-o range
is passed to
.I ditroff
or
.I nroff;
.BI \-T device
is also passed to
.I eqn
(but not
.IR neqn ),
and to
.I pic
unless
.B \-n
is specified.
You can use
.BI \-x nnn
to specify multiple copies to
.I ditroff
or
.I lpr.
.PP
The
.B \-m
option causes
.I off
to send you mail when done.
.SH DIAGNOSTICS
.QU "No invocation"
if input does not start with a comment line,
and complaints about unknown command options.
.SH "SEE ALSO"
ditroff(1), troff(1), bib(1), eqn(1), pic(1), refer(1), tbl(1)
.SH AUTHOR
Col. G. L. Sicherman (decvax!sunybcs!colonel)
