.TH PHONE 1L "13 March 1985"
.UC 4
.SH NAME
phone \- lookup against telephone list on remote host
.SH SYNOPSIS
.B phone
[ -h
.I host
]
.I name
.SH DESCRIPTION
.I Phone
is a trivial client program used to retrieve local employee information
from a master file on a remote host by contacting a suitable server.
The user list residing on 
.I host
(default \fBut\-ratliff\fP)
is searched for all lines containing
.I name
as a substring (the search is case-insensitive).
These lines are printed as the output of the
.I phone
program.
.PP
.I Phone
operates by opening a TCP connection to the port indicated
in the service specification for ``phone''.  
The remote
.I phoned
server then reads up to 128 characters of 
.I name
and uses this
string as the search key, folding to lower case.
Regular expressions of the type allowed by 
.I grep(1)
are allowed, with the caution that special characters should
be escaped to avoid interpretation by the shell.
.I Name
may be specified as the null string,
in which case the entire user list is retrieved.
.PP
.SH "FILES"
.br
.ns
.TP 21
/etc/services
for specification of service port
.SH "SEE ALSO"
grep(1), phoned(8)
.SH "BUGS"
The update procedure for the list itself is ill-defined.
