.TH SERVER 8C 85/10/27
.UC 4
.SH NAME
server \- remote command server
.SH SYNOPSIS
.B /etc/server
.br
.B /etc/fingerd
.SH DESCRIPTION
This is a generic server daemon program, to be executed by \fIinetd\fP(8).
It is ordinarly accessed by client(1), and is useful for implementing
remote man servers, phone lists, etc.
.PP
\fIServer\fP gathers a line of input, converts it into arguments,
checks command name against the file \fB/etc/server.cmds\fP,
and executes the command.
It is similar to rshd, except it doesn't require user authorization,
and it is therefore limited to a small number of commands.
.PP
\fB/etc/server.cmds\fP ordinarly consists of one command name per line.
There may be other words on the same line, in any order:
.IP "login"
the connection is logged in wtmp.
.IP "local"
the foreign host must be in the same domain as this host.
.LP
If \fB/etc/server.cmds\fP can't be found, the default line is
.IP
man login
.PP
Comments may be introduced with # at the beginning of a word.
This works both in the input line, and in \fB/etc/server.cmds\fP.
.PP
If the name of the command is not \fBserver\fP, and instead
ends with the letter `d', the command to be called is assumed
to be the last filename element of that name minus the letter `d'.
E.g., if \fB/etc/server\fP is linked to \fB/etc/fingerd\fP
and \fIinetd\fP calls it under the latter name, \fIserver\fP
will assume the command to be executed is \fIfinger\fP.
The \fIlogin\fP option will also be assumed, but not \fIlocal\fP.
It is not necessary for the client to pass the command name
in the input line, as \fIserver\fP will insert the command name
(in the example, \fBfinger\fP) as the first word of the line,
taking the line passed as arguments to the command.
.PP
Note that the environment variable \fBPATH\fP should be set
appropriately when \fIinetd\fP is started, in order for the
various server commands to be found properly.
.SH DIAGNOSTICS
Text messages through the TCP port.
Should be self-explanatory.
.SH FILES
.nf
/etc/server.cmds
/etc/services:
server		599/tcp		# generic command server
.SH "SEE ALSO"
client(1),
inetd(8),
rshd(8).
