.TH CHUNI 1 local
.SH NAME
chuni \- change default login universe
.SH SYNOPSIS
.B chuni
name
[
universe
]
.SH DESCRIPTION
.I Chuni
is a command similar to
.IR  chsh (1) ,
except that it is used to change the login universe field in the universe
file rather than the shell field in the password file.
If no
.I universe
is specified,
then the current login universe is printed.
Otherwise, only
.IR att
or
.I ucb
can be specified as the universe.
.PP
Only the Superuser can change the login universe of someone else.
.PP
An example use of this command would be
.PP
.DT
	chuni bill ucb
.SH FILES
/etc/u_universe
.SH "SEE ALSO"
chsh(1), universe(1) 
.SH AUTHOR
Frank Crawford
.\"	@(#)chuni.1	8/31/84
.SH BUGS
.PP
If Pyramid ever add a universe name that is not 3 characters long then
this will have to be rewritten.
