.TH FPACK 1WI "December 15, 1985" "Wang Institute" "Unix User's Manual"
.SH NAME
fpack \- pack and unpack ascii files with simple archiving scheme
.SH USAGE
.B fpack
[files]
.SH DESCRIPTION
.I fpack
is a simple plain text file archiving scheme to either
reduce the number of files or to package them together.
It is designed to be portable to systems between which
files may be transferred, such as between UNIX and MSDOS.
It can save space on systems that use disk blocks for files that occupy
a small part of a block.
One of the program's requirements is that it does not alter the format
of its input, so files like documents or human readable data files
are not converted to a special format.
.PP
Files are delimited by a special string at the start of a line:
.br
	fpack:!@#$%^&*():	<filename>
.br
.SH NOTES
.PP
Text outside file delimiters in an archive will be ignored.
.PP
If a file does not end with a newline character,
one will be silently added.
.PP
If a file to be unpacked exists,
then it will not be overwritten.
Instead, the contents of the file(s) being unpacked will be discarded.
.SH EXAMPLES
.nf
Pack up some C source files.
	fpack a.c b.c c.c > archive
Unpack all files.
	fpack < archive
.fi
.SH "SEE ALSO"
shar(1), sh(1) make a more flexible archiving scheme for UNIX.
.SH AUTHOR
Gary Perlman
