.TH TAPEMGR 1 "4 April 1986"
.SH NAME
tapemgr \- manage tape drives, by restricting access to only one user.
.SH SYNOPSIS
.I tapemgr
.I "[-r drive|all] [-n #drives|all] [-c command] [-v] [-t]"
.SH DESCRIPTION
Normally the requested number of drives are allocated then a command is
executed and once the command has terminated
the drives are deallocated, one of the actions taken by
.I tapemgr
during deallocation is to make sure the drive is dismounted and offline.
.TP 5
.I "-r drive"
.PD 0
.TP 5
.I "-r all"
.PD
Resets the specified drive or all drives.
If you do not own the specified
drive then you must be
.I root
or in the group
.I tapemgr
to reset the drive.
The option may appear more than once on the command line,
and the drives specified are accumulated.
Once the option is specified the drives specified will be reset and
no other actions taken.
.TP 5
.I "-n #drives"
.PD 0
.TP 5
.I "-n all"
.PD
This option tells tapemgr how many drives to allocate (the default is 1).
This option may also appear more than once on the command line but only
the last occurrence has any ultimate effect.
.TP 5
.I "-c command"
Normally
.I tapemgr
starts up
.I /bin/sh
or the shell specified in the environment variable
.I SHELL.
If the
.I -c
option is specified then the command specified will be will be executed
instead of shell.
.TP 5
.I "-v"
This option toggles verbose mode, initially verbose mode is on.
.TP 5
.I "-t"
Normally
.I tapemgr
has a timeout of 6 hours, if you are
.I root
or in the group
.I tapemgr
you can request that the timeout be turned off with the -t option.
.SH EXAMPLES
.TP 5
.I "tapemgr -r all"
resets all the tape drives on the system, this command should appear in
.I /etc/rc.local.
.TP 5
.I "tapemgr"
allocates one drive.
.TP 5
.I "tapemgr -r 1"
resets drive 1. NOTE: drives are numbered from 0.
.TP 5
.I "tapemgr -n 2"
requests 2 tape drives.
.TP 5
.I "tapemgr -n all"
requests all tape drives.
.TP 5
.I "tapemgr -c 'csh -f' -v -t"
requests 1 tape drive executing the c-shell with the -f option turning off
verbose mode and the time out.
.SH ENVIRONMENT
.TP 5
.I TAPE_DRIVES
The numbers of the drives selected in a blank separated list. This environment
variable is created by
.I tapemgr
if it does not exist and is appended to if it does.
.TP 5
.I SHELL
Used by
.I tapemgr
for a default program to start up if the -c option is not specified.
.SH FILES
.TP 5
.I "/usr/adm/tapelog"
A log of all the activities of tapemgr. No logging is done if the file
does not exist.
.TP 5
.I "/dev/rmt*"
character special tape devices.
.TP 5
.I "/dev/mt*"
block special tape devices.
.SH AUTHOR
Michael Thompson at Dalhousie University, Halifax N.S. Canada.
.SH DIAGNOSTICS
I hope they are self explanatory.
.SH BUGS
None that I know of, but this program has not been tested on a system with
more than one drive, so that might be where the troubles will start.
