.TH UNRM 1 LOCAL
.SH NAME
unrm, rm \- remove files and bring them back
.SH SYNOPSIS
.B unrm
[
.B \-f
] file ...
.br
.B rm
file ...
.SH DESCRIPTION
.I Rm
is a local replacement for the standard
.IR rm (1)
command.  Prior to removing a file it ferrets away a copy of it in
the directory
.RI /tmp/rm/ login_id ,
creating each component along the way as necessary.
The standard ``\-r,'' ``\-f,'' and ``\-i'' options may be specified,
but they are ignored.
.PP
Files that have been deleted with this version of
.I rm
can than be retrieved with the
.I unrm
command.
.I Unrm
checks to see that you are indeed the owner of a file before you
can copy it.  It will not overwrite a file of the same name in the
current directory, unless the ``\-f'' flag is specified, which
causes the file to be replaced regardless.
.PP
If these programs are available, the system administror will probably want
to add a line like the following to /usr/lib/crontab:
.RS
40 4 * * *      find /tmp -mtime +2 -exec rm -f {} ;
.RE
This removes all files from temp that haven't been touched within
two days.
.SH BUGS
Strange things can happen if you try to specify something other than
a regular file.
