.TH MAILWATCH 1
.SH NAME
mailwatch \- watch for mail
.SH SYNOPSIS
.B mailwatch
[
.B \-a
] [
.B \-c
] [
.B \-e
] [
.B \-o
] [
.B \-i
.I empty-icon
] [
.B \-I
.I full-icon
] [
.B \-l
.I empty-label
] [
.B \-L
.I full-label
] [
.B \-m
.I mail-reader
] [
.B \-t
.I check-time
]
.SH DESCRIPTION
.I Mailwatch
monitors the users' mailbox (as given in the
.B MAIL
environment setting) and alerts the user when there is new mail.
.I Mailwatch
uses the SUN
.IR shelltool (1)
terminal emulation capabilities to post the new mail alert.
It will not function properly unless running in a SUN tty emulation window.
.PP
While waiting for mail, the window will be closed and displaying the
.I empty-mailbox
icon.  When new mail arrives, the
.I full-mailbox
icon is displayed.  The
.I mailwatch
window may optionally pop to the front of the screen, open and start up
a mail reader.
After the mail reader has exited and the mail
disposed of, the window is closed and the
.I empty-mailbox
icon is displayed.
.SH OPTIONS
.TP 15
.B  \-a
Ask before starting up the mail reader program.
.TP
.B \-c
Clear the terminal emulator window before starting up the mail reader program.
.TP
.B \-e
Bring window to front when mail arrives.
.TP
.B \-o
Automatically open window when mail arrives.
.TP
\fB\-i\fP\fI empty-icon\fP
Icon to display when mailbox empty.
(Default is \fI/usr/include/images/emptymbox\fP).
.TP
\fB\-I\fP\fI full-icon\fP
Icon to display when mail arrives.
(Default is \fI/usr/include/images/fullmbox\fP).
.TP
\fB\-l \fP\fIempty-label\fP
String to use as label for empty mailbox icon. (Default is for no label).
.TP
\fB\-L \fP\fIfull-label\fP
String to use as label for full mailbox icon. (Default is for no label).
.TP
\fB\-m \fP\fImail-reader\fP
Mail reading program to use. (Default is
.IR Mail(1)).
.TP
\fB\-t \fP\fIinterval\fP
Check for mail every
.I interval
seconds.  (Default is 60 seconds).
.PP
.I Mailwatch
can also be forced to check the mailbox by sending it an interrupt signal
(\fBSIGINT\fP).  Sending a quit signal (\fBSIGQUIT\fP) causes 
.I mailwatch
to exit.
.PP
.I Mailwatch
uses the SUN tty emulator window capabilities which are controlled by
command strings, so it need not run on the SUN workstation itself.
.SH BUGS
.PP
The window is closed only if the mailbox file is empty.
.sp
All pending input is flushed when new mail is detected, and this sometimes
causes 
.I mailwatch
output to be garbled.
.sp
This program could well run as an actual tool, sparing the expense of running a
shelltool for mail monitoring.
.sp
SUN UNIX 3.0 has a
.I mailtool
which performs many of these functions, but we don\'t run 3.0 yet.
.SH AUTHOR
Clyde Hoover, University of Texas Compuation Center, Austin Texas.
.SH FILES
The name of the mail file watched is taken from the
.B MAIL
environment entry.
.br
.I /usr/include/images/emptymbox
and
.I /usr/include/images/fullmbox
are the default icons displayed.
