.TH LIMIT 1L "University of Kentucky" "4.2BSD"
.SH NAME
limit \- limit processor usage of a program by renicing
.SH USAGE
limit 
.I file
[
.I args
]
.SH DESCRIPTION
.LP
Limit(1) is meant to limit processor usage by background processes.
It fork()'s and exec()'s 
.I file
with 
.I args
(if any) then goes into an infinite loop watching the load average.
If the load average becomes very high then it changes the 
.I nice
value for the process group to successively higher numbers.
If the load average drops back down it again lowers the nice value.
If the load average is nonexistant it sets the nice value 
a little bit below 0.
.LP
Intended usage of the program is via a shell script, for instance
replace /usr/bin/rnews with:
.RS
.nf
.ft L

#! /bin/sh
exec /usr/local/limit /usr/lib/news/rnews

.ft P
.RE
.LP
Which will limit the impact of rnews upon your system.
.SH AUTHOR
David Herron
.br
University of Kentucky, Computer Science
.br
cbosgd!ukma!david, david@ukma.bitnet
.SH BUGS
This program is a little simple minded.
There are some cases where you will want all but one of a set of 
process groups to be niced down, and the other given extra priority.
.LP
Note that this program needs to be setuid to root, so it can
raise and lower process priorities at will.
However, the child process sets its uid and gid back to the real ones
before doing the exec().
.LP
As written it is 4.2BSD specific.
However if System V provided functions similar to load average and renice
then it could run there.
