/*
 * This file contains the string that get written 
 * out by the emacs-version command.
 * Rich had it generated by a command file. I do
 * it manually, until I can figure out a way to get
 * the MicroGnuEmacs version number generated in an
 * reasonable and automatic manner.
 */

char	*version = "MicroGnuEmacs 1a" ;
