.TH PRINTPIC 1 "18 April 1987"
.SH NAME
printpic \- make b&w halftone print of pic file on Laser Writer
.SH SYNOPSIS
\fBprintpic\fP [\fIoptions\fP] \fIpicfile\fP
.SH DESCRIPTION
\fIPrintpic\fP makes black and white halftone prints of picture files
on an Apple Laser Writer.
The program reads the
picture file, translates it into Postscript image format
and pipes this to the \fIlpr(1)\fP program for spooling to a printer.
If printing is not desired then the Postscript output can
be saved in a file using the \fB\-p\fP option.
.PP
By default the entire picture file is
rotated 90 degrees so that it nearly fills the page
and 8 bits of luminance are used,
but the intensity transform, picture file window,
and the image's placement on the page may be changed.
.PP
Options:
.nf
.ta \w'-dither amplitude   'u
\fB\-P\fR \fIprinter\fP	print on named Laser Writer, default is in the environment variable PRINTER
\fB\-p\fR \fIoutfile\fP	output Postscript to \fIoutfile\fP rather than spooling, file name '\-' means standard output
\fB\-label\fR \fIlabel\fP	label string to be printed below image (quote if it contains spaces)
\fB\-w\fR \fIx1 x2 y1 y2\fP	window to read, default is entire image
\fB\-ar\fR \fIratio\fP	pixel aspect ratio, default is 1
\fB\-chan\fR \fIchan\fP	channel to print \fB{r|g|b|a}\fP, default is luminance
\fB\-bits\fR \fInbits\fP	number of bits per pixel to send, default is 8.  must be 1, 2, 4, or 8.
\fB\-gamma\fR \fIgamma\fP	gamma, default is 1
\fB\-negate\fR	negate image
\fB\-dither \fIamplitude\fR	turn on dithering, default amplitude is 0 (try .5)
\fB\-size\fR \fIsize\fP	image size on page in inches, default is 9, (the larger of width and height)
\fB\-rot\fR \fIangle\fP	rotation angle in degrees counter-clockwise, default is 90 (landscape format)
\fB\-cen\fR \fIx\fP \fIy\fP	image center on page, measured in inches from upper left, default is 4.25 5.5
.fi
.PP
Examples:
.br
.TP .7i
\fBprintpic foo.pic\fP
print image vertically on page on default printer.
.TP
\fBprintpic foo.pic -cen 4.25 3 -rot 0 -size 6 -label "8-bit halftone of foo.pic" -P gordo\fP
print image horizontally near top of page, 6 inches wide, with label,
on printer "gordo".
.TP
\fBprintpic foo.pic -dither .5 -bits 2 -chan r -p temp.ps\fP
write postscript output for 2 bits of dithered red channel to \fItemp.ps\fP
.SH NOTE
Takes 10 to 15 minutes for a 512x488x8 image because of 9600 baud link.
The laser writer prints only 5 bits of gray level max, even if you request 8.
.SH SEE ALSO
lpr(1)
.SH AUTHOR
Paul Heckbert, PIXAR
