.TH checkin 1L "OGC 3/11/85"
.SH NAME
checkin \- editor interface to rcs `ci`
.SH SYNOPSIS
.B checkin
.I "[file1 file2 ...]"
.SH DESCRIPTION
.LP
\fBcheckin\fR provides for the creation of rcs logs to be used
in rcs ci(1) procedures.
For each file specified, \fBcheckin\fR does an rcsdiff(1) on the
file and the latest checked-in version of that file.
If a difference exists, EDITOR is invoked on a temporary file
containing the diff.
The user creates a log based on the diff, saves the temporary file,
and exits the editor.
The query:
.IP 
\fLWant to checkin "file" with log? (y)\fR
.LP
Allows the user to verify the checkin with the just-created log.
If checkin is to proceed, reply with one of \fI<CR>, y, yes\fR.
If a checkin with the just-created log is not desired, reply with \fIn\fR.
.LP
The actual `ci` process for the verified logs starts once all logs
for all files have been created.
.LP
checkin examines the environment variables EDITOR and CHECKIN.
If EDITOR is set, it specifies the editor to invoke on the temporary
file; `vi` is used by default.
If CHECKIN is set, it specifies the `ci` options to use during
the checkin; "-l" (the letter ell) is used by default, this
checks the file back out locked.
.SH FILES
/tmp/CI.*.$$  -- temporary files, removed on completion 
.br
_log.*.$$ -- saved log files if `ci` error.
.SH AUTHOR
Mark Foster (Oregon Graduate Center, Beaverton, OR)
.br
usenet: {allegra,tektronix,reed}!ogcvax!fosterm
.br
csnet:  fosterm @ oregon-grad
.SH "SEE ALSO"
ci(1), rcsdiff(1), csh(1)
.SH DIAGNOSTICS
.LP
If there is an error on the rcsdiff of a file (i.e.,  the file has
not been checked in before, so this is the initial version), the
error message is used for the edit buffer, rather than the diff.
.LP
If the `ci` for a file fails, the log is saved in a "unique" file
in the current directory, using the source filename as part of the log 
filename. 
.SH BUGS
.LP
This process relies on a fast-starting, fast-exiting editor to be 
interactively useful.
.SH NOTES
.LP
Users of vi(1) may find a macro "kill to end of buffer" useful to
delete the diff once the log is created.  Include in ~/.exrc the line
.IP
map K :+1,$ d ^V^M
