.TH RPT 1
.SH NAME
rpt  \-   general purpose repeat command
.SH SYNOPSIS
.B rpt
[ -inputfilename ]
.I count command
.SH DESCRIPTION
Executes \fIcommand\fR the number of times specified by \fIcount\fR.
\fIcommand\fR may be a simple command, a pipeline, a command
list, a parenthesized command list or a quoted command list.
All metacharacters in a parenthesized command list must be
preceded by a backslash.
.PP
Input for \fIcommand\fR may be taken from a file by adding
a `-inputfilename' flag.
Input will be read in as many times as specified in \fIcount\fR.
.SH EXAMPLES
.nf
rpt 100 nroff -T12 letter
\0\0\0formats letter 100 times
rpt -names 50 nroff -T10 label
\0\0\0formats label 50 times using names as input file each time
rpt 15 tbl costs | nroff -Tcrt12 | col | lpr
\0\0\0formats costs 15 times; `tbl costs' is input to rest of
\0\0\0pipeline during each execution
rpt 15 "tbl cost | nroff -Tcrt12 | col | lpr"
\0\0\0similar to above, except all of quoted list before `| lpr'
\0\0\0is input for lpr during each execution
rpt 50 \\( nroff -T12 file1 \\; nroff -T10 file2 \\)
\0\0\0parenthesized command list formats file1 and file2 50 times
\0\0\0in 12 and 10 pitch, respectively
.fi
