.tr ~
.TH ULIMIT 1 local
.SH NAME
ulimit~- get/set file size limit
.SH SYNTAX
.BR ulimit
.RI [~newlimit~command~[~args~...~]~]
.SH DESCRIPTION
.I Ulimit
with no arguments will display the current maximum file size for the
calling process (usually the shell).
.I Ulimit
with at least two arguments will set the maximum file size to
\fInewlimit\fR and then execute the \fIcommand\fR.
The \fInewlimit\fR is specified in units of blocks (i.e. 512 bytes).
Any additional arguments (if found) are passed through to the
\fIcommand\fR.
.SH EXAMPLE
ulimit 4096 cat file1 file2 >largefile
.PP
This will allow \fIlargefile\fR to be 2 Megabytes.
.SH SEE~ALSO
sh(1), ulimit(2)
.SH NOTES
The name conflicts with the Bourne shell builtin \fIulimit\fR.
.SH AUTHOR
Paul Sutcliffe, Jr.  (...!seismo!cbmvax!devon!paul)
