.TH DIALUP 1
.SH NAME
dialup \- load phone number from service name and call
.SH SYNTAX
.B dialup
[
.B -s
]
.B service
.SH DESCRIPTION
.B Dialup
uses a simple database setup in the user's home directory to help users
who call other computers via cu(1).  This database contains the mnuemonic
name of the database for reference.  It also contains the phone number,
baud rate and description and optionally the user's login name and
password for that service.
.PP
If the
.B -s
option is used the login name and password are not printed.
.PP
The database consists of six fields seperated by colons (:) much like
/etc/passwd.  The fields in order are: name, phone number, baud rate,
login name, password and description.
.SH "SEE ALSO"
cu(1)
.SH CREDIT
This program was developed by Brad L. McKinley at M D R Professional
Software Inc.  The user of the program accepts any and all responsibility
for damages caused by this program.
