.TH FORK 1 16/10/80
.SH NAME
fork \- run a command in parallel and report when it is done
.SH SYNOPSIS
fork ["]command_line["]
.SH DESCRIPTION
Fork is a command file which can control the parallel execution of
another command.
It accepts as argument(s) an arbitrary command line,
which it will execute. It returns control immediately to the user,
but itself waits for the command to complete. It then prints a message
that the command is complete.
Fork is useful when a task is to be forked off,
but the user wants to be informed explicitly when that command is complete.
Many commands terminate silently, so fork was created to be equivalent to
"(command_line;echo command_line is done.)&".
Note that if command_line contains any characters special to the shell
command interpreter ('>' '<' '*' etc.) then command_line should be
enclosed in quotes, to delay interpretation of those characters.
.SH FILES
.SH "SEE ALSO"
sh(1)
.SH DIAGNOSTICS
.SH AUTHOR
Martin Tuori, DCIEM Toronto Canada
.SH BUGS
