.TH FSKIP 1
.ad
.SH NAME
fskip \- skip files on magtape
.SH SYNOPSIS
fskip [ n ]
.SH DESCRIPTION
Fskip reads the magtape until it finds
the n-th end of file mark from the beginning.
The default value of n is 1.
The tape is closed but not rewound.
.SH FILES
/dev/rmt0, /dev/nrmt0
.SH "SEE ALSO"
rewind(1), tm(4)
.SH AUTHOR
Hughes O'Neil
.br
Modified for V7 by Alexis Kwan (HCR for DCIEM)
.SH BUGS
