.TH REWIND 1
.ad
.SH NAME
rewind \- rewind magtape
.SH SYNOPSIS
rewind [-s] [-n]
.SH DESCRIPTION
Rewind opens and closes the magtape, rewinding it.
The option -s tells rewind to sleep until the tape is
finished rewinding, instead of exiting immediately after it closes
the device.
The option -n permits the selection of a tape drive other than the default 0.
.PP
This command is meant to be used with fskip(1),
and any other commands that don't rewind the magtape.
.SH FILES
/dev/rmt*
.SH "SEE ALSO"
fskip(1), tm(4)
.SH AUTHOR
Hughes O'Neil
.br
Modified for V7 by Alexis Kwan (HCR for DCIEM).
.SH BUGS
