.TH CHFN 1 Local
.SH NAME
chfn \- change user's real name
.SH SYNOPSIS
.B chfn
[ user [ realname ] ]
.SH DESCRIPTION
.I chfn
allows the user to change her real name, as printed by
.I finger(1)
and
.I who(1).
If no
.B user
argument is given, the real name is changed for the person
currently logged in.
.PP
If no
.B realname
is given, the current name is printed, and a new one is asked.
.PP
Depending on choices made by the system administrator, it might
or might not be possible to modify someone else's name. The program
will then ask for the correct password first.
.SH SEE ALSO
chsh(1), finger(1), who(1)
.SH DIAGNOSTICS
All kinds of problems with the password file, and locking it,
are reported, and the program exits.
.SH AUTHOR
K. Richard Magill, rich@rexaco1.UUCP
.br
Extensively modified by Jack Jansen, jack@htsa.UUCP.
