.TH CHSH 1 Local
.SH NAME
chsh \- change login shell
.SH SYNOPSIS
.B chsh
[ user [ shell ] ]
.SH DESCRIPTION
.I chsh
allows the user to change her login shell.
If no
.B user
argument is given, the login shell is changed for the person
currently logged in.
.PP
If no
.B shell
is given, the current shell is printed, and a new one is asked.
.PP
Depending on choices made by the system administrator, it might
or might not be possible to modify someone else's shell. The program
will then ask for the correct password first.
.SH SEE ALSO
chfn(1), login(1)
.SH DIAGNOSTICS
The
.B shell
given is checked for existence, and executability.
.br
Also, all kinds of problems with the password file, and locking it,
are reported, and the program exits.
.SH BUGS
The executability check only looks at the mode, so it doesn't
guarantee that you will be able to log in with the given shell.
.SH AUTHOR
K. Richard Magill, rich@rexaco1.UUCP
.br
Extensively modified by Jack Jansen, jack@htsa.UUCP.
