.TH XMODEM LOCAL "August 26, 1986"
.UC 4.2
.SH NAME
xmodem \- Christensen protocol file transfer utility
.SH SYNOPSIS
.B xmodem
[\fBst|sb|rt|rb\fR][\fBYBKcdlx\fR]
[file...]
.br
.SH DESCRIPTION
The
.I xmodem
program implements the Christensen (XMODEM) file transfer
protocol for moving files between 4.2/4.3BSD Unix systems and microcomputers.
The XMODEM/CRC protocol, the MODEM7 batch protocol, the XMODEM-1K
block protocol and the YMODEM batch protocol are all supported by 
.IR xmodem .
For details of the protocols,
see the document edited by Chuck Forsberg titled
.I
XMODEM/YMODEM Protocol Reference.
.sp
This program runs on 4.2/4.3BSD systems ONLY.  It has been tested on VAXes
and Suns against the MEX-PC program from Niteowl Software.
.PP
.SH PARAMETERS
Exactly one of the following must be selected:
.TP
.B rb  
Receive Binary - files are placed on the Unix disk without conversion.
.I Xmodem
will silently destroy existing files of the same name.
.TP
.B rt  
Receive Text - files are converted from the CP/M format of CR-LF pairs to the Unix
convention of 
.I newline 
characters only between lines.  
Bit 8 of each character is stripped (which makes Wordstar files much
more readable).
The resulting file
is acceptable to the Unix editors and compilers, and is usually slightly
smaller than the original CP/M file.
.I Xmodem
will silently destroy existing files of the same name.
.TP
.B sb  
Send Binary - files are sent without conversion as they exist on the Unix disk.
.TP
.B st  
Send Text - newline characters in the file are converted to CR-LF pairs
in accord with the CP/M conventions for text files.  The file grows
slightly as this occurs so the estimate of file transmission size and
time are always optimistically low.
.PP
.SH OPTIONS
.TP
.B Y
Select the YMODEM batch protocol for sending files; a list of files specified
on the command line will be sent in sequence.  The YMODEM batch protocol is 
used automatically for file reception if the sending program requests it.
.TP
.B B
Select the MODEM7 batch protocol for sending files; a list of files specified
on the command line will be sent in sequence.  The MODEM7 batch protocol is 
used automatically for file reception if the sending program requests it.
.TP
.B K
Select the XMODEM-1K file transfer mode for sending files. Use of 1K packets on
low-error lines increases throughput.  1K packets are automatically
used for file reception if the sending program requests it.
.TP
.B c   
Select the CRC-16 error-checking protocol on receive.  CRC mode is better at catching
transmission errors that occur than the alternative checksum protocol.  
CRC mode is automatically selected for file
transmission if the receiving modem program requests it.
.TP
.B d   
Delete the 
.I xmodem.log
file before file transfer is begun.
.TP
.B l   
Do NOT write to the log file.  If logging is selected, a file
.I xmodem.log 
will be created (or appended to), with entries for significant events, errors
and retries.  This can be useful to see why things went wrong
when they do.
.TP
.B x
Toggle on debug mode.  If debug mode is selected, copious and possibly
useful debugging information will be placed in 
.IR xmodem.log .
.SH "FILE NAMES"
Files transmitted using one of the batch modes
will be stored on the remote machine under a CP/M-ified name (limited
to eight characters plus a three character extension; ":" characters will
be turned into "/" characters; all characters will be in monocase).  Files received using one of the batch modes
will be stored under their transmitted names (except that any "/" characters
in the file name will be converted into ":" characters and all upper-case
characters will be translated into lower case).
.PP
When a batch receive is requested,
.I xmodem
takes a wait and see attitude and can adapt to either batch protocol or even
a classic XMODEM transfer (note that CRC-16 mode is automatically set under
these circumstances).
If a classic, "non-batch" XMODEM file reception takes place, 
the received file is stored as
.IR xmodem.in .
File names present on the command line for a batch receive are ignored.
.SH NOTES
While waiting for the beginning of a transfer or the beginning of a packet,
.I xmodem
treats two CAN (Cntrl-X) characters that are received within 3 seconds
as a request to abort.
.PP
Squeezed CP/M files must be transferred in binary mode, even if they
contain text.
.PP
If you use 
.I xmodem
over a 
.I rlogin
link, you must use the flag
.IR "rlogin machine -8" .
.SH EXAMPLES
To receive a text file transmitted from a micro (using CRC-16
error-checking) and store it under the
name 
.IR file.name ,
use the command line
.RS
.B "xmodem rtc file.name"
.RE
Note that if the transmitting program on the micro uses the 1K packet
protocol or either batch protocol,
.I xmodem
detects this automatically and takes appropriate action.  Further
note that if one of the batch protocols is used, the received file(s)
will be stored under their own names and the name on the command line
(if any) will be ignored.
.PP
To send a set of text files to a microcomputer using 1K packets and the
YMODEM batch protocol, use the command line
.RS
.B "xmodem stYK *.txt"
.RE
.SH FILES
xmodem.log (if logging is enabled)
.SH BUGS
Batch mode could be smarter about bad file-names in the midst of a
batch transmit/receive.
.PP
Batch mode could allow a mixture of binary and text files.
.PP
The file lengths and creation times embedded in the YMODEM batch protocol are
neither set on transmit nor used on receive.  However, the "IMP/KMD record
count" field is utilized.
.SH SEE ALSO
kermit(1)
.SH AUTHOR
Steve Grandi, National Optical Astronomy Observatories.  Based on
.I xmodem
by Brian Kantor, University of California at San Diego.
This, in turn, was based on
.I umodem
by Lauren Weinstein, Richard Conn and others.
