.TH VE 1
.SH NAME
ve \- an interactive viewer of programming errors
.SH SYNOPSIS
.B ve file
.SH DESCRIPTION
.I Ve
accepts only one argument which is the name of the file containing 
errors output from cc, ld, lint, cyntax and make. With the automatic
invocation of the
screen editor - vi, 
.I ve
allows the rapid positioning to the error lines specified 
in the error file one after the other, and if possible,  
prints the corresponding error message on the terminal's status line. 
Three commands may be typed when in the vi editor to browse through the 
error lines. 
.P
.in +10
^A \(em go to next error line, 
.br
^Z \(em go back to the last error line, and
.br
^C \(em go to the current error line.
.in -10
.SH ARTHOR
Ming Chi, Kam (joseph@cadvax.unsw.oz)
.SH BUGS
As users may change the contents of the file, so
.I ve
does not rely on the line number specified in the error file to
position the cursor to the line which may cause the error. Instead,
.I ve
uses a pattern matching method to try to match the  original line pattern 
before invoking vi, with the same file, after being possibly changed. 
As a result, there may be a chance, possibly very slight, that the file
contains more than one line with the same pattern and incidently, 
.I ve
positions to the wrong one. So users are advised to compare the line number
in the error message with the line number of error line positioned by
.I ve
in cases where the users have some doubts as a result of their big
difference or no error can be spotted. In both cases, the command n or N 
may be typed to see if any other match can be found.
