.TH CHECKMAIL 1 "March 4, 1986" "TeleSoft Inc." "UNIX User's Manual"
.\" $Compile: iroff -man.new %f
.SH NAME
checkmail \- prints who your mail is from and the subjects
.SH USAGE
.B checkmail
[-unaqo] [file]
.SH DESCRIPTION
.I checkmail
is a program that will tell you about the mail in your mailbox. 
It lists who each letter is from (without path or domain), the date received,
and the subject, one line per letter.
Using options listed below you may check for new mail or list only new
mail and also check files and mail folders other than your spool file.
.I Checkmail
with default options is similar to the 
.I from
program except that subjects are also displayed.

Normally a status of 0 is returned, unless the file isn't found in which case
a status of 1 is returned.

When the 
.I -q
option is used a status of 0 is returned if there is mail and 1 if there
isn't mail. 

.I Checkmail
normally displays outgoing mail (mail you have sent) found in the
file, you may choose ignore outgoing mail by using the 
.I -o
option.
.de OP
.TP
.B -\\$1 \\$2
..
.OP u
List only unread mail.  That is, mail that you haven't read yet. 
.OP n
List only new mail.  That is, mail that you haven't read or seen the
header of.  When you enter the mail program all the mail is marked as
no longer new but still unread.
.OP a
List all mail, regardless of status (read, unread, or new).  May be used
to override an option already given on the command line.
.OP o
Exclude outgoing mail from the display or search.
.OP q
Quiet operation.  Tells checkmail to only report whether it had any mail 
to display.  The status result is 0 if there was mail and 1 if there wasn't
any mail.  Useful in combination with 
.I -n
or 
.I -u
option to check for new or unread mail in a .login script.
.TP
.B file
Uses
.I file
instead of the default file /usr/spool/mail/$USER.
You may specify a mail folder by prefixing the folder name with "+" as
is done with the mail program.

.SH "EXAMPLES"
The following csh line could be used in your .login file to run the mail
program only if you have unread mail in your spool file.

  if { checkmail -qu } mail

Or the following could be used to display who new mail is from and the
subjects:

  if { checkmail -qn } then
      echo '===== NEW MAIL ====='
      checkmail -n
  endif

.SH "FILES"
/usr/spool/mail/$USER \- your mail spool file (default file)

.SH "SEE ALSO"
from, mail
.SH AUTHOR
Gary Morris (sdcsvax!telesoft!gm)
.SH BUGS
n/a
