.TH ANSWER 1 "HFVR"
.SH NAME
.\" name \- one-line description for in permuted index
answer \- to automatically reply to senders of Unix mail, while away
.SH SYNOPSIS
.\" bnf on command syntax
answer [-d] [-V] [-H]
.SH DESCRIPTION
.\" semantics
Answer will read through your whole mail file and for every message
determine if a reply should be given. The reply will be a short message
stating that the mail was received and when, on which machine.
If present the file $HOME/I_am_out is appended to this message.
.sp
No reply is given to daemons like **NSC, **RJE**, root, daemon and of
course yourself. Answer will also not reply to messages from itself.
Also not answered are the login names mentioned in the file 
$HOME/mail/.noanswer
.sp
Every message treated will be deleted from the mail file and stored
in the file $HOME/mail/stack_of_mail. This file needs not exist, but the
$HOME/mail directory must exist.
.sp
The -d option turns on the debugging mode and will display all generated
commands. In this mode all is done except for replying to the sender
.SH EXAMPLES
answer
.SH FILES
.nf
$HOME/mail/.noanswer        list of logins not needing replys
$HOME/I_am_out              appended to reply if exists
$HOME/mail/stack_of_mail    list of treated messages
.fi
.SH SHELL VARIABLES
.nf
HOME
LOGNAME
.fi
.SH SEE ALSO
mail(1), crontab
.SH DIAGNOSTICS
Every message treated is logged on stdout.
.SH WARNINGS
some errors will be produced if needed.
