.TH CRAPS 6
.UC 4
.SH NAME
craps \- play the game of craps
.SH SYNOPSIS
.B /usr/games/craps
.SH DESCRIPTION
.PP
.I Craps
is the popular gambling game found in most casinos, legal or otherwise,
and is now found on the system.  Although craps has many betting options,
it is beyond the scope of this manual to explain every possible bet.
.PP
To get started you really only need to know one command.  The command
.B ?
will give you a list of the available commands.
.PP
The object of craps is to (of course) beat the house, i.e. leave the
game with more money than when you started.
.PP
A "high rollers" list is maintained which keeps track of the amount won by
each person who has played, and also the number of games they have played.
It is highly likely that over the long run, the player on the top of the
list is the one who has lost the least amount of money!
.SH ENVIRONMENT
.PP
CRAPSNAME - used to set your name on the High Rollers List.
.SH AUTHOR
.PP
Ray Tripamer, University of Nevada, Las Vegas
:-)
.SH FILES
.DT
/usr/games/lib/craps.list\ \ \ High Roller List
.br
.SH SEE ALSO
"Playboy\'s Guide to Casino Craps"
.SH BUGS
.PP
If any should arise, please mail them to
me at: !seismo!unrvax!unlv!ray
