#! /bin/sh
remfolder="+reminders"
umask 077
case $# in
    0)
	while when=`promptdate`
	do
		remfile=`mhpath $remfolder new`
		echo "Date: $when

" > $remfile
		prompter $remfile
	done
	;;
    *)
	when=`promptdate "$*"`
	remfile=`mhpath $remfolder new`
	echo "Date: $when

" > $remfile
	prompter $remfile
	;;
esac
