.TH DATES 1
.UC
.SH NAME
dates \- report upcoming events
.SH SYNOPSIS
.B dates 
[ -t days ] file ...
.SH DESCRIPTION
.I Dates
examines a file containing information about upcoming events
and reports any that are to take place within the next seven days.
.PP
The event file is expected to contain entries of the form:
.IP
mmdd
.br
event information
.br
 ...
.PP
if that event takes place on a single day, or:
.IP
mmdd-mmdd
.br
event information
.br
 ...
.PP
if it takes place over a range of dates.
Comment lines beginning with a '#' are ignored.
.PP
For example, if your event file contains an entry for:
.IP
1206
.in +5
Saint Nicholas' Day!
.PP
then
.IP
dates eventfile
.PP
will yield:
.IP
Tue Dec 6:
.in +5
Saint Nicholas' Day!
.PP
assuming, of course, that it falls within seven days.
Events occurring the same day or the next are reported as
taking place "Today" or "Tomorrow".
.PP
You can shorten or lengthen the time period for which events are
reported by using the '-t' flag.
For example:
.IP
dates -t 0 eventfile
.PP
will report only those events taking place today.
.PP
Event entries may be listed in any order, but be warned that
.I dates
does not sort its output.
Upcoming events are reported in the order that they appear.
Obsolete entries are not deleted by
.I dates
since it has no way of telling that an event will not recur
next year (like birthdays).
.PP
It is often useful to put a call to
.I dates
in your .login or .logout (with the "C" shell) or your .profile 
(with the Bourne shell).
.SH BUGS
Doesn't seem to work quite right at midnight or New Year's.
.SH AUTHOR
Oscar Nierstrasz at the University of Toronto.
.SH SEE ALSO
events(1), calendar(1), at(1), leave(1), time(2).
