.TH ANSIR I
.SH NAME
ansir \- read ANSI standard labelled tape
.SH SYNOPSIS
.B ansir
[
.B \-ijnpg
] [ name ... ]
.SH DESCRIPTION
.I Ansir
reads a single volume multi-file ANSI Standard
Labelled Tape or anything that looks remotely like it.
It can handle 'F', 'U', 'D', 'S' and 'V' formats ('V' is for IBM tapes).
Labels can be in ASCII or in EBCDIC;
.I ansir
assumes the files to be in the same character code as the labels, except
for 'U' format files which are supposed to be in BINARY (i.e. untranslated).
The record separator for ASCII or EBCDIC is the newline; the record
separator for BINARY is determined interactively. All these rules can
be overridden through the
.B \-i
and
.B \-j
parameters.
.PP
Bad characters, i.e., those not in the ASCII95 set, are reported and
show up in the format \e[777]. This may necessitate some postprocessing
but too much light is better than being left in the dark.
.PP
.I Ansir
may consult the user on missing information; when a question is answered
with a single question mark,
.I ansir
supplies more information.
.PP
The program accepts the usual
.B \-cfhlm
parameters to describe the tape (see
.IR mag (I)).
.PP
There are a number of additional options:
.TP
.B \-i
the UNIX file name and character code are determined interactively. A
minus
.B \-
for a file name will result in skipping the corresponding tape file.
.TP
.B \-j
as i-option, but including record format, block length,
record length and buffer offset.
.TP
.B \-n
no execution: the files will not be extracted.
.TP
.B \-p
information from the labels is printed.
.TP
.B \-g
if a
.B \-p
is given, the information about generation number and
version number is also printed.
.PP
If
.I name
parameters are
given, only the named files are treated.
.SH SEE ALSO
mag(I)
.SH BUGS
The 'S' format has never been tried.
.PP
The
.B \-p
option causes too much output.
