.TH ANSIW I
.SH NAME
ansiw \- write ANSI standard labelled tape
.SH SYNOPSIS
.B ansiw
[
.B \-ignpv
] [ file ... ]
.SH DESCRIPTION
.I Ansiw
writes a single volume multi-file ANSI Standard Labelled Tape in F- or U-format.
.PP
If no option is given the tape has the following properties:
.br
	the volume serial number is 222222,
.br
	the owner is the user id,
.br
	the file identifier is the UNIX filename,
.br
	the expiration date is the current date,
.br
	the accessibility symbol is ' '.
.PP
The preferred record format is 'F' with block length 1920 and record length 80.
Each
.I file
is scanned before it is written to tape. If it is found to be incompatible
with the preferred record format,
.I ansiw
tries to find a better one. If it fails the user is consulted.
.PP
The program accepts the usual
.B \-cfhlm
parameters to describe the tape (see
.IR mag (I)).
.PP
There are a number of additional options.
.TP
.B \-i
the user is consulted about the tape properties.
.TP
.B \-g
if a
.B \-i
is given the user is also consulted about the generation number
and the version number.
.TP
.B \-n
no execution: the tape-file is not created.
.TP
.B \-p
a short report is printed for each file.
.TP
.B \-v
the user is only consulted about the Volume Label.
.PP
The 'D' and 'S' formats are not implemented since their portability
value is considered low.
.SH SEE ALSO
mag(I)
