.TH CPTP I
.SH NAME
cptp \- copy from tape to tape
.SH SYNOPSIS
.B cptp
[
.B \-x
] [
.BR of= file
|
.BR if= file
]
.SH DESCRIPTION
.I Cptp
converts between real tapes and tape images on disk.
The
.B of=
parameter causes
.I cptp
to read the real magtape and produce a tape image on the indicated file.
A call with an
.B if=
parameter will write back the tape image from the indicated file to the
real magtape.
.PP
The program accepts the usual
.B \-cfhlm
parameters to describe the tape (see
.IR mag (I)).
If the
.BI \-x -option
is given,
copying will continue regardless of read-errors or consecutive tape marks
(default is stopping after 4 consecutive TMs).
.SH "SEE ALSO"
mag(I),
rawtp(I),
survey(I)
