.TH MAG I
.SH NAME
mag \- generalized magnetic tape
.SH SYNOPSIS
.PP
.B cptp
[
.B -x
] [
.BR of= file
|
.BR if= file
]
.PP
.B rawtp
name [
.B \-x
] [ param ... ]
.PP
.B survey
[
.B \-px
]
.PP
.B ansir
[
.B \-ijnpg
] [ name ... ]
.PP
.B ansiw
[
.B \-ignpv
] [ file ... ]
.PP
.B NOSsplit
[
.B \-s
N ] [ name ]
.SH DESCRIPTION
These programs have in common that they use a 'generalized magtape'.
Such a generalized magtape may correspond to a real magtape or to a tape image
i.e., a normal
file with a specific structure which contains all information present on
a tape, including block sizes and tape marks. Conversion between real tapes
and tape images is done by
.IR cptp (I).
.PP
The generalized magtape is described by the following parameters which
apply to all the above programs.
.TP
.BI \-m d
the magtape is real and on unit
.IR d . 
.TP
.B \-h
the magtape is real and in high density.
.TP
.B \-l
the magtape is real and in low density.
.TP
.BI \-f " name"
the magtape is a tape image on file
.IR name .
.TP
.BI \-c " name"
the magtape is the character-device
.IR name .
.SH AUTHOR
Dick Grune.
.SH BUGS
Conflicts between options are not detected.
