.TH NOSSPLIT I
.SH NAME
NOSsplit \- split Cyber system tape
.SH SYNOPSIS
.B NOSsplit
[
.B \-s
N ] [ name ]
.SH DESCRIPTION
.I NOSsplit
reads a Control Data Cyber system tape (SI-format) as written under NOS/BE or
SCOPE by COPY, COPYBF or COPYBR. Each Cyber record is written to a separate
file. The EOR-levels appear on standard output.
.PP
A Cyber record consists of an integral number of Cyber words of 60 bits each,
whereas a UNIX file consists of an integral number of bytes of 8 bits each;
so, if the Cyber record has an odd number of words, a bit-to-bit mapping
won't work. Therefore, a mapping is used in which
each Cyber machine-word (60 bits) maps onto 10 characters, each containing
6 bits (again 60 bits).
Such a 6-bit file can be processed by
.RI NOStr (I),
which can do translation from DISPLAY code and Z-type record recognition.
.PP
The file names are
.IR name 00000,
.IR name 00001,
etc. The default
.I name
is
.BR x .
.PP
The program accepts the usual
.B \-cfhlm
parameters to describe the tape (see
.IR mag (I)).
.PP
When the
.B \-s
option is given, the first
.I N
records are skipped.
.SH SEE ALSO
mag(I),
NOStr(I)
.SH BUGS
There is no
.I NOScombine
to put Humpty Dumpty together again.
