.TH NOSTR I
.SH NAME
NOStr \- translate Cyber 6-bits files
.SH SYNOPSIS
.BR "NOStr -" C
[ file ]
.SH DESCRIPTION
.I NOStr
accepts as input a 6-bits Cyber file, as created, e.g., by
.IR NOSsplit (I).
Such a file contains a mapping of an integral number of 60-bits Cyber words;
each Cyber word is mapped onto 10 UNIX characters, each containing 6 bits in
the right-most 6 positions. Depending on the interpretation that should be
given to the original Cyber words
.I NOStr
performs the appropriate conversion indicated by
.IR C .
.PP
Three conversions have been implemented:
.TP
.B d
the input is interpreted as originating from Z-type
records in DISPLAY code (6 bits to a character, EOR marked by two or more 00
characters in the lower end of a word)
.TP
.B a
Z-type records in ASCII95 (8-bit characters right aligned in
12 bits, EOR marked by one or more NULL characters in the lower end)
.TP
.B b
`binary', i.e., ASCII256 (8-bit characters right aligned in
12 bits, no further processing); since this code is not well standardized,
parity checking, CR-removal and further preening are left to the user.
.SH SEE ALSO
NOSsplit (I)
.SH BUGS
As with
.I NOSsplit
the inverse does not exist.
