.TH RAWTP I
.SH NAME
rawtp \- read raw tape
.SH SYNOPSIS
.B rawtp
name [
.B \-x
] [ param ... ]
.SH DESCRIPTION
.I Rawtp
extracts arbitrary portions from a magtape.
.PP
The program accepts the usual
.B \-cfhlm
parameters to describe the tape (see
.IR mag (I)).
The additional
.BR \-x -option
will cause
.I rawtp
to continue reading regardless of read-errors or consecutive tape marks
(normally
.I rawtp
stops after 4 consecutive tape marks).
.PP
The tape is considered as a series of files, each terminated by a
tape mark (TM); a file is considered as a series of blocks, each
terminated by an InterRecord Gap (IRG); a block consists of characters.
.PP
An instruction
.I +t.i.c
or
.I \-t.i.c
moves the tape over
.I t
TM's,
.I i
IRG's (but not over a TM) and
.I c
characters (but not over an IRG). If the instruction begins with a
.I +
the contents are copied to a file, a
.I \-
just skips the contents.
.PP
Instructions may be concatenated into an instruction series. If an
instruction sequence is followed by
.BI x n
the effect is repeated
.I n
times. If
.I n
is absent or 0, the instruction series is repeated until it becomes
ineffective. E.g.,
.I +.1\-1x
will give you the first block of each file on tape.
Default parameter is
.I +1x
which splits the tape into its separate files.
.PP
The produced files are named
.I namepprrrii
where 
.I name
is the first argument,
.I pp
is the two-digit parameter number,
.I rrr
is a three-letter counter counting the number of repetitions of the
parameter, and
.I ii
is the two-digit instruction number within the parameter.
.PP
Example:

.br
	rawtp  tp  \-10  +..80\-3x

will skip 10 files, and then give the first 80 characters of the first
block of every third file on the files
.IR tp02aaa01 ,
.IR tp02aab01 ,
etc, (if present.)
.SH "SEE ALSO"
mag(I),
cptp(I),
survey(I)
