.TH SURVEY I
.SH NAME
survey \- survey contents of a magtape
.SH SYNOPSIS
.B survey
[
.B \-px
]
.SH DESCRIPTION
.I Survey
lists the lengths of the blocks on a magtape. If the
.B \-p
option is given, the first characters of each block are displayed
in ASCII, EBCDIC and hexadecimal.
.PP
The program accepts the usual
.B \-cfhlm
parameters to describe the tape (see
.IR mag (I)).
The additional
.BR \-x -option
will cause
.I rawtp
to continue reading regardless of read-errors or consecutive tape marks
(normally
.I rawtp
stops after 4 consecutive tape marks).
.SH SEE ALSO
mag(I)
