.TH EDITOR 1L 
.ad b
.SH NAME
editor \- a very simple, very fast input editor
.SH SYNOPSIS
.B editor
[filename] 
.SH HP-UX COMPATIBILITY
.TP 10
Level:
HP-UX/USER CONTRIBUTED
.TP
Origin:
Hewlett-Packard Laboratories
.SH DESCRIPTION
.I Editor
is a simple program suitable for use as the front-end editor for a number 
of programs, especially mail systems and conferencing systems.  It is
designed based on the functionality of the \fIBerkeley Mail\fR input
system and the \fIElm\fR builtin editor.
.sp
The program has a very small number of options, namely;
.nf

  ~?     list the help menu
  ~!     either a shell escape, or execute the specified command
  ~|     pipe the current text through the command
  ~e     invoke Emacs, if available
  ~v     invoke Vi, if available
  ~o     invoke a specified editor
  ~p     print the message entered so far
  ~r     read in the specified file
  ~w     write the message entered so far to the specified file

.fi
To end input, use either the \fIEOF\fR character (usually ^D) or
simply enter a `.' on a line by itself.
.SH AUTHOR
Dave Taylor, Hewlett-Packard Laboratories
.SH "SEE ALSO"
ex(1), ed(1), elm(1L), Mail(1), vi(1), emacs(1L), etc etc
.SH NOTES
Since this is a pretty mindless editor, it won't allow you to 
invoke it with a file that already exists.  Furthermore, the 
program MUST be given a filename to create/edit or it will 
complain.
.sp
Enhancement requests desired, but remember this isn't supposed to
be a real editor!
