.TH HOLD 1 "26/4/85"
.SH NAME
hold \- collect standard input into a file
.SH SYNOPSIS
.B "hold file"
.SH DESCRIPTION
.I Hold
collects standard input and writes it to the file.
The difference between it and
.I > or tee
is that the file
does not exist by that name until EOF is seen.
This is useful for putting the results of pipelines
back into the original file.
If
.I hold
is interrupted the temporary file is deleted.
.SH EXAMPLES
tr 'A-Z' 'a-z' < prog | hold prog
.SH AUTHOR
Ken Yap ( University of Sydney )
.SH FILES
holdXXXXXX	temporary
.SH SEE ALSO
tee(1)
