.\" RCS Info: $Revision: 1.2 $ on $Date: 86/04/02 10:33:33 $
.\"           $Source: /ic4/faustus/src/spellfix/RCS/spellfix.1,v $
.\" Copyright (c) 1985 Wayne A. Christopher, U. C. Berkeley CAD Group
.\"	Permission is granted to do anything with this code except sell it
.\"	or remove this message.
.TH SPELLFIX 1 "October 10, 1985"
.UC 4
.SH NAME
spellfix, baseword, spellcheck, wordchange \- interactively correct spelling
.SH SYNOPSIS
.B spellfix
document
.br
.SH DESCRIPTION
.B spellfix
interactively corrects the spelling in
.I document.
For each misspelled word, it determines a list of possible correct
spellings for the word and displays them on the screen, updating the
list as it finds more. It searches in order the list of correctly spelled
words in the document, a list of the 4000 most frequent words, and the
full dictionary
.I /usr/dict/words.
Also, if the user has a file called
.I .spellrc
in his home directory, words in this file are considered properly
spelled.
.PP
As the program is displaying words, the user may type a space to stop the
process. He is then prompted for a command, which may be one of:
.TP
E
Enter the correct spelling of the word, terminated by a newline.
.TP
?
Print out a help message.
.TP
Q
Exit
.B spellfix
immediately (doesn't save changes).
.TP
W
Write out the changes so far and exit.
.PP
Any other character is taken to be a choice of one of the words currently
displayed.
.PP
A line of context is provided, so that the user may see where the word is
used. Only one line in which the misspelled word appears is printed,
though.
.PP
.B spellfix
makes use of several other (possibly useful) programs:
.TP
.B baseword
Reads a list of words on the standard input, and for each word,
outputs a line consisting of:
.IP
\fIword0 word1 change1 word2 change2 ... wordN changeN\fR
Where
.I word0
is the origonal word, and each
.I wordI
is a possible base word for
.I word0,
that is, one with all the prefixes and suffixes stripped off. The
corresponding
.I changeI
is an editing script that describes how to reconstruct the origonal
word. The characters in this script have the following meanings:
.br
.nf
$ Go to the end of the word.
^ Go to the beginning of the word
\&. Duplicate the current letter.
+ Add the following characters.
- Delete the following characters.
c Any other character is either added or deleted, depending on whether
	a '+' or a '-' was last executed.
.TP
.B spellcheck [bad good]
Takes as input the output of baseword and outputs the lines for which
none of the possible base words is in the dictionary.
.TP
\fBwordchange file ...\fR
Reads
.I old new
pairs from the standard input and for every occurrence of
.I old
in any of the files, replaces
.I new.
(Except when
.I old
is a subset of another word.)
.SH "SEE ALSO"
spell(1)
.SH AUTHOR
Wayne Christopher (faustus@cad.berkeley.edu)
.SH BUGS
.PP
Suffixes and prefixes aren't dealt with well enough.
