.TH CENTER 1L 
.ad b
.SH NAME
center \- read stdin, output each line centered in 80 cols
.SH SYNOPSIS
.B center
< text > centered-text
.SH HP-UX COMPATIBILITY
.TP 10
Level:
HP-UX/USER CONTRIBUTED
.TP
Origin:
Hewlett-Packard Laboratories
.SH DESCRIPTION
.I Center
is a simple program that is useful within shell scripts.  There
are no doubt millions of `better' ways to accomplish what
this program does, but it does work!
.SH EXAMPLE
.P
Let's assume we're in "sh";
.nf

        $ name="John Doe"
        $ echo $name
        John Doe
        $ name1=`echo $name | center`
        $ echo $name1
                                John Doe
        $

.fi
.SH AUTHOR
Dave Taylor, Hewlett-Packard Laboratories
.SH "SEE ALSO"
digest(1)
