.TH MYDATE 1L 
.ad b
.SH NAME
mydate \- readable date format
.SH SYNOPSIS
.B mydate
.br
.B "mydate notime"
.SH HP-UX COMPATIBILITY
.TP 10
Level:
HP-UX/USER CONTRIBUTED
.TP
Origin:
Hewlett-Packard Laboratories
.SH DESCRIPTION
.I Mydate
is a simple program that displays the local date in a much more
readable format than possible by the \fIdate\fR(1) program.
There are two ways to use it, both exemplified below.
.P
This is most useful for use within scripts.
.SN EXAMPLE
.nf

	% date 
	Mon Jun  2 18:35:24 PDT 1986

	% mydate
	Monday, June 2nd 1986 at 6:35 pm

	% mydate notime
	Monday, June 2nd 1986
	 	
.fi
.SH AUTHOR
Dave Taylor, Hewlett-Packard Laboratories
.SH "SEE ALSO"
date(1), digest(1)
