.TH ROLO 1 "6 December 1984"
.UC 4
.SH NAME
rolo \- use an online rolodex, containing information about people.
.SH SYNOPSIS
.B rolo
[ name1 name2 ... \-u otheruser \-s \-l ]
.SH DESCRIPTION
By default
.I rolo
reads in a rolodex data file from the user's home directory, prints
out a menu of choices, and lets the user scan, update, delete and add to
his personal database of people.  If no rolodex database exists one
is created.
.I rolo
checks to see that the rolodex database is not already in use.
.PP
The command line options are:
.TP
.B \-u otheruser
Uses the rolodex database in the 'otheruser' home directory.  This may
not be possible if the directory or the database is read or write protected.
.TP
.B \-s
Prints people's names, work phone numbers and home phone numbers in a nice
format to standard output.
.TP
.B \-l
Normally the rolodex database is locked when being used.  This option
unlocks the database as soon as it is read in.  The \-s option implies this.
.PP
Invoking 
.I rolo
followed by a list of names causes 
.I
rolo
to search the database for all people whose names or company
affiliations contain any of the name arguments as substrings.  All the
information about each person is printed to standard output, the program
pausing after each record is printed.  Using this feature causes the
database to become unlocked, since this is a read-only mode.
.PP
Extensive help is available on-line.  Typing '?' or 'help' will generally
print a help file for you.
.SH FILES
/usr/src/local/cmd/rolo     for the source.
.PP
/usr/local/lib/rolo     for help files.
.PP
/usr/local/rolo         the executable image.
.PP
.PP
.SH AUTHOR
Peter Webb wrote the first rolodex program.
.PP
JP Massar revised and then complete rewrote this older version.
Net address: massar@think.com, ihnp4!think!massar.
.SH BUGS
There is no way to keep certain entries private.
.PP
You can't get a short summary of only a subset of people.



