.\" @(#)staticon.1	1.2 (Don Gworek) 9/14/86
.\" This document uses the troff(1) -man macros
.TH STATICON 1 "14 September 1986"
.SH NAME
staticon
\- display an icon
.SH SYNOPSIS
.B staticon
[
suntool args
]
iconfile
.PP
.SH DESCRIPTION
.I Staticon
displays your favorite icon when closed or open.
Accepts all the generic tool arguments
discussed in 
.I suntools(1).
.SH SEE ALSO
suntools(1), iconedit(1)
.SH NOTE
One of the more frivolous programs ever written.
.SH AUTHOR
Don Gworek ...{rocksvax|decvax}!sunybcs!gworek
