.TH HIER 1 "Unsupported Utility"
.SH NAME
hier \- show filesystem hierarchy
.SH SYNOPSIS
.B hier
[
.B \-adp
] [
.BI \-c \0columns
] [
.BI \-i \0indent
]
.br
[
.I directories...
]
.ad b
.SH DESCRIPTION
This command shows you a filesystem hierarchy in a useful, indented way.
At each level files are sorted in two groups:
non-directory files,
then directories (recursing into each one).
It examines the named
.IR directories ,
or by default the present working directory.
.PP
Options are:
.TP
.B \-a
All: include directories and files whose names start with ".".
.TP
.B \-d
Show directories only; skip other types of files.
.TP
.B \-p
Print filenames packed onto lines, not aligned in columns.
.TP
.B \-c
Set width of display for showing multiple filenames on a line
(or use the COLUMNS environment variable).
The default is 80 columns.
.TP
.B \-i
Set indentation (number of blanks) per hierarchy level.
The default is 4 spaces per level.
.SH EXAMPLES
.TP
hier
.br
Show all non-"." files, recursively,
in and under the current directory.
.TP
hier -apc 40 /etc
Show all directories and files,
including any whose filenames start with ".",
in a format 40 columns wide,
and with filenames packed into lines,
under directory "/etc".
.SH SEE ALSO
ls(1), sftw(3) (does not exist (yet))
.SH DIAGNOSTICS
If a file is not stat-able,
or a directory is not readable,
the filename is printed on a line to itself,
like a directory (sorted with directory names),
with an appropriate message following.
.SH BUGS
Unlike
.IR ls (1),
it sorts files across lines rather than down columns.
Fixing this would be non-trivial.
.PP
Also, due to the behavior of
.IR sftw (3)
(like
.IR ftw (3)),
it never lists "." and ".." files, even with the
.B \-a
option.
