.TH shred 1L "April Fool's Day, 1987"
.SH NAME
shred -  Program to break a C program into subroutines.
.SH SYNOPSIS
.B shred
.B [\-u] [\-h
.I <header file>
.B ]
.I <file.c> ...
.SH DESCRIPTION
.I shred
is a (and i quote)
.nf
.ps 8

		\fIkrufty hack to rip large \fB(C)\fI source modules into
		subroutine modules.  This program is only semi-intelligent
		and should be treated as such.
							M.J.R.\fR
.ps 10
.fi
.PP
Some more intelligence, and options have been added here at LLE. In
particular, shred recognizes functions with types out front, or on the previous
line(s). Also, it prefixes each subroutine with an 'include' line for the
.I header file
and with the comments which appeared before this subroutine, but after the
previous subroutine, if any.
It now can tell the difference between a function declaration and a function
definition. Declarations are left in the
.I header file.
And, finally, you can now get the file names
to be prefixed by an underscore as an option, rather than always, as was
previously the case.
.SH OPTIONS 
.B \-u
- prefix file names with underscore. (this was the old default)
.br
.B \-h
.I <header file>
- use this as the name of the file containing header (non-subroutine)
lines. (default is _header.h)
.SH EXAMPLES 
% \fBshred messy.c\fR
.br
hopefully the result is a bunch of subroutines in separate files.
.SH BUGS
As mentioned, shed is not too smart.
There is little hope of shred working on files with C syntax errors.
Also, shred doesn't know about #ifdef's, so any weirdness in #ifdef's, or
even syntax errors inside #ifdef's will confuse it.
However, if it gets confused, the
worst that seems to happen is all of your file(s) end up in the
.I header file.
At the moment, strange things happen if the subroutine files already
exist. The new file is appended to the existing one, however, no comments
will be prepended. In any event, this usually results in garbage, but at
least nothing gets lost. There is a check to make sure you're not writing
over the file you're reading from, which could be ugly.
.SH AUTHOR
Copyright, 1987, Marcus J Ranum
.br
All rights reserved. This code can be distributed, modified,
or altered at will, but it or versions of it may not be sold
for profit.
.sp 2
Local extensions by S Swales, Lab. for Laser Energetics (LLE)
