.TH PUREPATH 1 "HFVR"
.SH NAME
.\" name \- one-line description for in permuted index
purepath \- to remove double entries in $PATH
.SH SYNOPSIS
.\" bnf on command syntax
purepath [-V] [-H] [path]
.SH DESCRIPTION
.\" semantics
purepath will print a new path with all mutiple defined entries
removed. Input is either path as given in command line or by default
purepath will examine $PATH as exported.
.SH OPTIONS
.nf
-V    to display version number.
-H    to display usage.
.fi
.SH EXAMPLES
PATH=`purepath`      # to make $PATH pure
