.TH DATE l "6 August 1984"
.UC 4
.SH NAME
date \- formatted output of current date
.SH SYNOPSIS
.B date
[ 
.B \-lf
]
[ [\-]
.B format variables
]
.SH DESCRIPTION
Without any argument,
.I date
output use ASCII format.
The
.B \-f
option stand for french output.
The
.B \-l
option stand for long output, either in english or in french.
.PP
The string
.I format
contains a format like that used by the C subroutine
.I printf
; all special char conventions are recognized.
The string would have better to be quoted to prevent any further shell
interpretation.
An optionnal single \- allow use of formats beginning with a \-.
.PP
.I Variables
is a list of single letters, either comma or blank separated, or even
concatened alltogether; valid names and their meaning are :
.TP 10
d, j
day of the week.
.TP 10
M
month.
.TP 10
D, J
day of the month.
.TP 10
h
hours.
.TP 10
m
minutes.
.TP 10
s
seconds.
.TP 10
Y, A
year.
.SH SEE ALSO
ctime, localtime, gmtime, asctime, timezone (3)
.SH AUTHOR
A. Didelot
.SH BUGS
No way to specify letter's case using format.
