tcopy: tcopy.c
	cc -s -O tcopy.c -o tcopy
upd: upd.c
	cc -s -O upd.c -o upd
dostp: dostp.c
	cc -s -O dostp.c -o dostp
fork.result: fork
	echo fork is a command file, ready to go.
fskip: fskip.c
	cc -s -O fskip.c -o fskip
calls: calls.c
	cc -s -O calls.c -o calls
rewind: rewind.c
	cc -s -O rewind.c -o rewind
all: tcopy upd dostp fork.result fskip calls rewind
