.TH NAME SECTION local
.SH NAME
dca2troff  \- convert Document Content Architecture documents to troff
.SH SYNOPSIS
.B dca2troff < file
.SH DESCRIPTION
.B dca2troff
reads IBM Document Content Architecture (
.B DCA
) documents in Revisable-Form
Text (
.B RFT
) format.
Only a few of the many
.B RFT
commands (
.I Structured Text, Multibyte and One-Byte
) are implemented.  The program does parse the commands and
will print out warnings for any unknown commands.  Troff form
comments are insterted in the output text stream for some of the
useful commands like font change requests.
.SH FILES
.SH SEE ALSO
IBM document - Document Content Architecture: Revisable-Form
Text Reference ( part # SC23-0758-0 ).
.SH DIAGNOSTICS
.SH BUGS
The version of the RFT manual I used was the first edition ( june 1983 ).
I found at least two very common commands that Display Write 3 uses are
not in the manual,
.I dca2troff
now ignores them.
.br
Biggest bug: DCA-RFT files are in EBCDIC.
.SH AUTHOR
Scott Bradner ( sob@harvard.{arpa,csnet,uucp,bitnet,harvard.edu}
