.TH GETUNENT 3-ucb
.SH NAME
getunent, getunnam, setunent, endunent \- get universe file entry
.SH ORIGIN
4.2BSD
.SH SYNOPSIS
.nf
.B #include <local/universe.h>
.PP
.B struct universe *getunent()
.PP
.B struct universe *getunnam(name)
.B char *name;
.PP
.B int setunent()
.PP
.B int endunent()
.PP
cc ... -ltrw
.fi
.SH DESCRIPTION
.I Getunent
and
.I getunnam
each return a pointer to an object with the
following structure,
containing the broken-out
fields of a line in the universe file.
.RS
.PP
.nf
.so /usr/include/local/universe.h
.ft R
.ad
.fi
.RE
.PP
.I Getunent
reads the next
line (opening the file if necessary);
.I setunent
rewinds the file;
.I endunent
closes it.
.PP
.I Getunnam
searches from the beginning until a matching
.I name
is found
(or until EOF is encountered).
.SH FILES
/etc/u_universe
.SH AUTHOR
Scott Simpson, TRW
.SH "SEE ALSO"
u_universe(5)
.SH DIAGNOSTICS
Null pointer
(0) returned on EOF or error.
.SH BUGS
All information
is contained in a static area,
so it must be copied if it is
to be saved.
