.\" @(#)shift.3	1.1 (TRW) 11/15/83
.TH SHIFT 3 TRW
.UC
.SH NAME
string_downshift, string_upshift \- shift case of strings
.SH SYNOPSIS
.nf
.B char *string_downshift(s)
.B char *s;

.B char *string_upshift(s)
.B char *s;

.B cc ... -ltrw
.fi
.SH DESCRIPTION
.I String_downshift 
shifts 
.I s 
in place to lowercase.
.I String_upshift 
shifts
.I s
in place to uppercase.
Both routines return
.I s.
.SH AUTHOR
Michael Gorlick, TRW
.SH SEE ALSO
ctype(3), string(3)
