.TH SEARCH 6 8/14/81
.SH NAME
search \- search and destroy players and aliens
.SH SYNOPSIS
.B search
.br
.B sscore
.SH DESCRIPTION
.PP
.I Search
is a computer game which can be useful in expelling pent up
frustration and anger.  Search is crt oriented and the
object of the game is to accumulate points by searching out and
destroying alien beings and other players flying through a "256 by
256 universe".
Many players are usually involved in a single "game" of search,
each navigating their own spacecraft through a common universe.
.PP
Search was recently modified to use messages on SVR2 unix.
For detailed directions, read the document
.I "A Guide to the Game of Search."
.PP
The program sscore dumps the points data base.
.SH FILES
.DT
/etc/searchd	central server for all players
.br
/usr/games/lib/search/points	player point totals
.br
/tmp/SEARCH	communications lock between slave and sgame
.SH SEE ALSO
Greg Ordy and Sam Leffler,
.I "A Guide to the Game of Search"
.SH BUGS
.PP
While search employs 
.IR termcap (5)
to manage the screen, it requires that the terminal have an
addressable cursor, clear screen capability, and at least 24
lines of 80 characters.
