.TH SNAKE2 6 "University of Rochester"
.SH NAME
snake2 \- another snake game
.SH SYNOPSIS
.B snake2
.SH DESCRIPTION
Tired of getting eaten by the snake(6) all the time?
Be a snake!!
Eat other users.
Run snake2.
.PP
You are the snake.
You look like this: ssssssS
.br
Change your direction by using the number keypad (i.e. 8 is up,
2 is down), using the keys around the 'k' key (for righties) or
the 'd' key (for lefties).
All 8 directions work.
.PP
Score by eating other folks.
Point values are based on eatee's size.
After 250 points, all point values are doubled.
If you see a capital letter, it means the box has triple point value.
Go for it!
But beware of the root (of all evil).
Its point value is unknown and sometimes does you more harm than good.
.PP
Ctrl-L will refresh the screen if necessary (like if somebody writes
to you) but won't slow the snake down a mite.
.SH BUGS
.PP
You can't go to the bathroom in the middle of this game.
.SH AUTHOR
Don Libes (seismo!nbs-amrf!libes)
