.TH BJ 6 86/07/13
.SH NAME
bj \- network blackjack game
.SH SYNOPSIS
.B
bj [hostname] [-arrows]
.br
dealer
.SH DESCRIPTION
The program \fIbj\fP is the client portion of a network blackjack game,
the program \fIdealer\fP is the server portion.  The game allows up to
six players to play blackjack against the dealer, and the game may
span machines.  The networking code uses stream sockets in the
internet family.  The dealer runs as a daemon in the background
and may be started with the command /usr/games/dealer&.  Once the
dealer is running, players may attach with the command /usr/games/bj.
.PP
The game will display the players currently in the game, and will allow
you to select which seat you wish to sit at.  Once seated, you bet
by typing in the amount you want to bet, and the cards are dealt.  The
top line of the display is a status line, informing each player of other
player's activities and prompts from the dealer.  While a player's hand
is being processed, the following commands are allowed:
.TP
space
stand
.TP
h
Take another card.
.TP
q
Quit after this hand.
.TP
s
Split a pair.
.TP
d
Double down.
.PP
If the dealer has an ace showing, each player is asked if they want insurance.
Insurance pays 2 to 1 if the dealer has blackjack, and thus insurance costs half
what the player's bet is.  Blackjack pays 3 to 2.  Once you have initially bet,
you can repeat your last bet by simply hitting return, rather than typing it
in again.  Beware - this amount is actually the last amount that you won or
lost, watch out if you just doubled down and lost, your bet is twice what you
think it is.  The display shows the player and the machine they are logged
in to, along with their bet and how much they are up or down.  You can set
an environment variable called BJ if you want to change your name, but there
isn't really enough room to display a name like "Amarillo Slim".
.SH OPTIONS
.TP
hostname
If the dealer server does not reside on the machine bj is running on, you
must provide the name of the host which dealer is running on.
.TP
-arrows
Normally the current player is highlighted in inverse video.  This is not
always easy to read, especially on Sun consoles.  The -arrows option
highlights the current player by placing "-->" next to their name.
.SH FILES
.TP
/usr/games/bj
.TP
/usr/games/dealer
.TP
/etc/services
.TP
/etc/hosts
.SH BUGS
Probably lots.  Undocumented features, too.  (Or is that redundant)  Look
through the sources.  Go away.
