.TH BATCH 1 UofW
.SH NAME
batch \- Submit a shell script to a daemon for low-priority batched execution
.SH SYNOPSIS
.B batch
[
\fB\-v\fR
]
[
\fB\-P\fIa\fR
]
queue_name
[
shell_file ...
]
.SH DESCRIPTION
.B Batch
is used to submit a list of commands to be executed by the shell possibly
at a later time when system resources are available.
This allows the system to restrict the number of jobs of a particular
class that are executed simultaneously, and to adjust the number
based on the current system load.
.PP
The contents of the specified files are concatenated together, saved
away in a system spool directory, and passed to the current shell
($SHELL) at execution time.
If no files are specified, the standard input is read.
Most, but not all, environment variables are also copied to the
beginning of the spooled command file.
.PP
The
.B queue_name
argument is the name of the queue to submit to.
Queues are named by what kind of thing usually goes into them;
they can actually contain any shell script at all.
.PP
The \-P option may specify a priority from
.I a
to
.I z;
this priority determines the sequence in which jobs are run.
The highest priority is
.I a
and the default is
.I q.
Priorities in the range from
.I a
to
.I g
are reserved to the super-user.
The \-v option for verbose gives you the name of the spool file
in which the shell commands have been put while wating execution.
.PP
Mail will be returned to you at the end of the job if the job exits with
a non-zero status return or produces any output.
Mail may also be sent to you depending on the individual queue upon
job start, system crash, or successful execution with no output.
.SH "SEE ALSO"
batchd(8), nice(1), renice(8), batchqueue(p), batchcancel(p), troffqueue(p), troffcancel(p)
.SH BUGS
.PP
If you don't have permission to determine the current working directory
then the shell file may execute under the spool directory when it runs.
.PP
Queues are named by the type of thing that usually gets put into them;
they should be named by the type of service they provide.
.PP
There is no official "batch remove" command to cancel a batch job.
You can try to find the spool directory and over-write the spooled
list of shell commands, but if the job has already started to run you
must use "ps -x" to find the running process and kill it by hand.
Your best bet is to use batchcancel(p).
.PP
Using letters to indicate priority is strange.
A numbering system would be more natural.
One based on
.IR nice (1)
wouldn't be too bad.
