enum keyword {
	K_EXEC=1, K_MAXEXEC, K_MAXQUEUE, K_SUPERVISOR, K_MAIL, K_MAILSUPERVISOR,
	K_CONSOLE, K_NICE, K_RESTART, K_TIMECMD, K_DAY,
	K_OFF, K_DRAIN, K_ON, K_NUMBER, K_TIME, K_VARIABLE, K_LINE,
	K_SYNTAX, K_LOADSTOP, K_LOADSCHED,
	K_CPULIMIT, 
	K_RLIMITCPU,
	K_RLIMITFSIZE,
	K_RLIMITDATA,
	K_RLIMITSTACK,
	K_RLIMITCORE,
	K_RLIMITRSS,
};
