.TH DES 1  LOCAL
.SH NAME
des \- perform DES encryption on a file
.SH SYNOPSIS
.B des
filename
.SH DESCRIPTION
This program takes a single argument, a file to encrypt or decrypt.
When started, it asks for a password.
If the file is named like ``foo.n'' the file is decrypted with the given key,
and output is put into the file ``foo.''
Otherwise, if the file is named like ``foo,'' the file is encrypted and
the output is put into ``foo.n''.
In both cases, the original input file is removed.
.SH "SEE ALSO"
crypt(1)
.SH BUGS
May not be true DES.
