.TH GETPATHS LOCAL 6/2/86
.SH NAME
getpaths \- gather Usenet article paths
.SH SYNOPSIS
.B getpaths
[
.BI \-n " file"
] [
.BI \-u
] [
.I distrib
]
.SH DESCRIPTION
.PP
.I Getpaths
scans through the news spool and prints out all article paths.  Crossposted
articles have their paths printed only once.
.PP
By default, usernames are removed from the paths.  If the
.B \-u
flag is given, usernames are left on.
.PP
The
.BI \-n " file"
option causes paths to be included only from articles that are newer
(in terms of file modification time) than
.IR file .
.PP
If no argument is given, the entire news spool will be scanned.  The
.I distrib
argument is a relative path from /usr/spool/news.  For example,
.PP
getpaths net
.PP
gets paths from net.*, and
.PP
getpaths net/micro/atari
.PP
does what you think.
.SH BUGS
The algorithm for eliminating crosspostings only prints a path if
the first newsgroup on the Newsgroups: line matches the directory currently
being scanned.  So if you say "getpaths na", an article with the header
line
.PP
Newsgroups: net.wanted,na.forsale
.PP
will not have its path printed (though it will print if the groups are given
in the reverse order).  In other words, the first group is always considered
the primary group, and other groups are always considered crossposts.
.SH AUTHOR
Joseph T. Buck, Entropic Processing, Inc.
.br
{pesnta,oliveb}!epimass!jbuck
