.TH TU58 1 "21 January 1984"
.UC 4
.SH NAME
tu58 \- emulate a tu58 tape drive over a serial line
.SH SYNOPSIS
.B tu58 
[
\-options
] serial_device file1 
[
file2
]
.SH DESCRIPTION
.I Tu58
will read and decode input from 
.I serial_device
according to the radial serial protocol. It will act in
accord with this protocol using 
.I file1
and\/or
.I file2
as a storage device. In this way these files resemble tu58 tapes.
.PP
.I Tu58
options include:
.TP
.B \-c
Create the files.
.TP
.B \-cn
Create file number n.
.TP
.B \-i
Initialize the files as rt11 directories with no entries.
.TP
.B \-in
Initialize file number n as an rt11 directory with no entries.
.TP
.B \-r
Files are read only.
.TP
.B \-rn
File number n is read only.
.TP
.B \-sn
Set the speed for
.I serial_device
at n baud.
.PP
In place of
.I serial_device
a \- can be used to indicate i/o from the standard input and output.
In addition error output is always sent to the standard error output.
.SH FILES
.ta 2i
/usr/local/tu/dk\?	files in rt11 format suitable as tu58 files
.br
.SH "SEE ALSO"
rtpip(1)
.SH BUGS
It can only output at 9600 baud. It has to be used at 4800 baud for
both input and output. 
