.TH RNGET 1 local
.ad b
.SH NAME
rnget \- unbundle a shell archive package
.SH SYNOPSIS
\fBrnget\fR [\fB-p\fI pattern\fR] [\fB-r \fIfile\fR]
[\fB-f \fIprog\fR] [\fIdirectory\fR]
.SH DESCRIPTION
.B rnget
unbundles the distribution package into the specified directory.
If the directory does not exist, it is created.
.PP
.B rnget
changes to the given directory (if given) and then
reads its standard input and searches for the given pattern
(default to "[#:]") at the beginning of a line.
All lines previous to that are saved in a file.
The line with the pattern and all subsequent lines are passed
to the standard input of \fIprog\fR (default /bin/sh) for processing.
.PP
The idea is that the input is a shar file contained inside
of a news article, with a scan done before hand for the
beginning of the shar.  For shars that don't begin with `#'
or `:' \fB-p\fP can be used to specify something else.
.PP
.B rnget
can be used from `rn' using the command:
.sp 1
.ce
| rnget directory
.sp 1
to cause the shell archive contained in the current article to be
extracted (using a rather simple algorithm) and piped into /bin/sh
for processing.  Unlike the simpler:  w | (cd dir; sh)  command,
this works if there is text before the actual start of the archive.
.PP
Available options are:
.TP 7
.B \-p
The next argument is interpreted to be the search pattern to be used
to indicate the end of the text to be saved in the file and the
beginning of the text to be passed to the shell.
The default pattern is "[#:]".
.TP 7
.B \-r
The next arguement is interpreted to be the name of the file which
this routine saves the material at the beginning of the article before
the pattern is encountered.
The default name is "READ_ME".
.TP 7
.B \-f
The next argument is interpreted to be the command to execute for
filtering the shell archive.  For example, if you really just
wanted to send only the archive to a file,
you could use the rn
command:  \fB| rnget -r /dev/null -f "cat > file"\fR.
.TP 7
.I directory
This is the name of the directory into which the archive is to be
unbundled.
If not given, the current directory is used.
.SH FILES
.TP 7
READ_ME
The default file used to collect the text which appears before the patten
appears in the shar archive.
.SH DIAGNOSTICS
The diagnostics are self-explanitory.
.SH "SEE ALSO"
rn(1),
shar(1),
sh(1).
.SH BUGS
Ownerships and permissions for archived files are not retained.
.SH AUTHORS
.SS "Original Shell Script"
Ronald S. Karr, National Semiconductor Inc., Sunnyvale, CA
.SS "Revisions and Manual Page"
R. O. Domitz, Concurrent Computer Corporation, Tinton Falls, NJ
