.TH CHECKMAIL 1 "15 July 1986" "" "Local UNIX Programmer's Manual"
.SH NAME
checkmail \- check the status of your and others mail
.SH SYNOPSIS
.B checkmail 
[
-q
] [
user ...  
]
.SH DESCRIPTION
checkmail tells whether you have, mail (old mail), new mail, no mail,
or no mailbox on the machine it is executed on.
.PP
By default,
.I checkmail
only reports the status of your mailbox, it returns a status of one
if you have 
.I "new mail"
and zero otherwise.
If you specify a list of users, it tells you
the state of their mailbox(s).
.PP
If you have a .hushlogin file, it defeats mail checking on login.
This program can then be used to re-instate this. It can also check 
your mail on login, and if you have new mail start up a mail job 
in the background with the following in your
.I .login 
file.

.nf
	checkmail
	if ($status != 0) then
		mail &
	endif
.fi
.PP
with the -q option, checkmail is quiet, has no output but still 
sets the status flag.
.SH BUGS
.I biff
if the user is logged in and they have biff set to y, the status 
returned will be that of old mail.
.PP
.I from
If the user executes the command "from" it will also appear as old mail.
.SH "SEE ALSO"
chtim(1), stat(2), biff(1), from(1)
.SH AUTHOR
Scott Mesches
