.TH MAILSPLIT 1L Local
.SH NAME
mailsplit \- split a file or mailbox into single items (smaller files)
.SH SYNOPSIS
.B mailsplit
[
.B \-?
]
[
.B \-o\fIformat\fP
]
[
.B \-p\fIpattern\fP
]
[
.B \-\fIn\fP
]
[\ file...\ ]
.SH DESCRIPTION
.I Mailsplit
splits large files into smaller ones.  The splits occur on lines that match a
.I pattern ,
which defaults to
.br
\ \ \ \ ``^From ''
.br
so that the command
.br
\ \ \ \ mailsplit mbox
.br
will split a
.I mail (1)
format mail-box, putting each message in a differnt file.
.PP
Options are:
.IP -?
Print a summary of options.  Any unknown option will also do this
.IP -p
The following string is taken to be a pattern to be used to match input lines
to determine points at which to split the input.
See
.I ed (1)
for details of the patterns.  The pattern may contain newlines (which match
themselves).
.IP -o
The folowing string is taken to be
.I printf -style
format to be used in the generation of output filenames.
There should be a %d in the string, which will be used to insert a
disambiguating number.  This number is zero for the first file, and is
incremented at the start of each output file.  The \-\fIi\fP option can be used
to start the number with another value, however.
The default format is
.br
\ \ \ \ split:%-06.d
.br
which results in files having names split:000000, split:000001, split:000002,
and so on.  Thus,
.br
\ \ \ \ mailsplit -o%d
.br
would produce files having the names 1, 2, 3, and so on.  The default format
was chosen because the resulting files are listed in numerical order by
.I ls (1),
or by
.br
\ \ \ \ echo *
.br
which is sometimes useful.
.IP \-\fBi\fP\fIn\fP
The number
.I n
will be used to number the first file; the number used each time will
thereafter be incremented as normal.  See the -\fBp\fP option for the use of
this.
.IP \-\fBn\fP\fIn\fP
Split the input every
.I n
lines.  In this case, no pattern matching is performed.  This is the behaviour
of
.I split (1),
except that
.I mailsplit
normally produced different filenames.
.SH DIAGNOSTICS
Mostly straight-forward.
``Internal Error'' indicates a bug in
.I mailsplit ,
and should be reported.
Exit staus 1 indicates an error parsing options \- for example, if an unknown
flag was ued.
Exit status 2 indicates a meaningless combination was detected and rejected
(this is rare in practice).
Exit status 3 indicates a run-time problem \- for example, if a file couldn't
be opened.
.SH "SEE ALSO"
.I ed (1),
.I mail (1),
.I ls (1),
.I split (1),
.I printf (3).
