.TH PED 1 "16 Mar 1987" Local
.UC 4
.SH NAME
ped \- edit a REGIS picture interactively
.SH SYNOPSIS
.B ped
[
.I file
]
.br
.SH DESCRIPTION
.I Ped
lets you interactively create and edit a REGIS line drawing
on a DEC graphics terminal.
If you specify a
.I file,
it must be a
.I ped
save file.
While such files will draw your picture when sent to the terminal,
they have special structures and information.
You cannot use
.I ped
on any old file of REGIS commands.
.PP
.I Ped
works only with points, lines, and curves.
You cannot specify colors or fill.
.SH "COMMAND SUMMARY"
.PP
The commands
.BR h ,
.BR j ,
.BR k ,
and
.B l
move the cursor left, down, up, and right.
You can prefix them with numbers; e.g.,
.B 100h
moves 100 pixels leftward.
Similarly,
.BR b ,
.BR n ,
.BR u ,
and
.B y
move down and left, down and right, up and right, and up and left.
.PP
The
.B p
command plants a numbered
.I point
at the cursor position.
You can relocate it with the
.B m
command,
or remove it with
.BR x .
.PP
You can make a chain of lines through labeled points with
.B v
(vector mode),
an open spline curve with
.B o
(open curve mode),
or a closed spline loop with
.B z
(closed curve mode).
Exit from these modes with
.BR i .
You can draw a circle with
.BR c .
.PP
The
.B J
and
.B K
commands move the whole picture down or up.
Use
.B g
to toggle a square grid imposed on the picture.
The
.B f
command reflects the picture horizontally or vertically,
and
.B s
expands or shrinks it.
If your picture is messed up, you can redraw it from scratch with
.BR r .
.PP
The
.B L
command displays a table of all lines (not curves),
showing their endpoints.
The
.B V
command deletes all points not currently used in lines, circles, or splines.
.PP
The
.B ?
command displays a menu, and
.B !
is a shell escape.
.PP
You can write your picture to a
.I ped
save file with
.BR w ,
specify a new file to edit with
.BR e ,
and exit from
.I ped
with
.BR q .
.SH BUGS
.I Ped
has been tested only on GIGI terminals.
Whether it works on other REGIS terminals is a matter for speculation.
In any case,
.I Ped 's
use of color will probably fall flat on VT240s.
.PP
This program is a
.SM HACK.
If you don't like it, go modify it yourself.
.SH AUTHOR
Col. Sicherman
