.TH APPEND 1 Local
.SH NAME
append \- append a file to the current directory
.SH SYNOPSIS
.B append 
filename [newname]
.SH DESCRIPTION
.PP
Append is a command to allow another person to put a file (actually
a link) into a particular directory.  This simulates the "append only"
access permission allowed by Multics but not Unix.
.PP
The mechanism is quite simple: the program is setuid to the owner of
the directory, and when called checks the file for plausibility
and links it into the current directory.
.PP
The use of a link allows the author to modify (ie, maintain) the program
without requiring the superuser to delete and reinstall the new version
in the target directory.
.SH INSTALLATION
.PP
To install append, place a copy into the directory you wish to
have accessable to others, chown it to yourself, and
set it setuid and executable, but not writable.
The chown command is:
.br
    chown your_name append
.br
The chmod command for this is:
.nf
    chmod u+s,g-w,o-w,a+x append  -- can be used by anyone
      or
    chmod u+s,g-w,o-w,g+x append  -- can be used by group only
.fi
.SH "CHECKING THE ADVISABILITY OF APPENDING"
.PP
It is inadvisable to append many kinds of file to a directory,
such as directorys and special files, and of course the file
should be present and either readable or executable.
Append checks for accessability and plausability.
.PP
Please note that it is quite reasonable to append a setuid
or setgid program to a directory. In fact, this is the proper
way to place a "gate" to certain private or sensitive
information in a generally accesable place.  It is not
reasonable to contrive to chown and re-setuid a program
to belong to root and append it to a directory, but this is dealt
with by chown and chmod directly, and does not affect append.
.PP
This does not mean that giving anyone append permissions on /bin is
a good idea: it is not hard to write a program which contains a
trapdoor to catch the superuser, and append on /bin or /usr/bin
would make it easy to put it in his way.
.PP
In general, one places append permissions on directories like
/usr/local/bin (which superuser doesn't normally search for commands)
and transfer directories.  Uucppublic would have been an excellent
example if the uucp author known about this technique...
.PP
One can append a FIFO to a directory even though it
is a type of "special" file, since this does not constitute an
(obvious) security problem.
.SH FILES
None.
.SH "SEE ALSO"
cp(1), section on "ln", append.web for detailed discussion of the 
algorithm.
.SH DIAGNOSTICS
Self-explanatory, one hopes.
.SH BUGS
.PP
It is possible, as mentioned above, to install a trapdoor program
using append in /bin, /usr/bin or /etc: do not grant append permissions
to these directories.
.PP
There is no companion "unappend" program, since that would be a
security bug of the first order.
.PP
You must have cd'd to the target directory to use append.


