.TH SETUNAME 1 "NCR Tower"
.UC 4
.SH NAME
setuname \- update utsname structure on disk or in memory
.SH SYNOPSIS
.B setuname
[ 
.B [-k] [-K] [-u /unix] [-n nodename] [-s sysname] [-r release] [-v version] [-m machine]
]
.SH DESCRIPTION
.I Setuname
displays and changes the utsname structure in a disk resident kernel
as well as updating the structure in memory.  It is especially handy
for setting the nodename used by uucp and mail.
.PP
The options are:
.TP \w'\-n\ nodename\ \ 'u
.B \-k
write the new utsname struct into /dev/kmem
.TP \w'\-n\ nodename\ \ 'u
.B \-K
same as -k but don't write onto disk resident copy of kernel
.TP \w'\-n\ nodename\ \ 'u
.B \-n nodename
set new nodename to "nodename"
.TP \w'\-n\ nodename\ \ 'u
.B \-s sysname
set new sysname to "sysname"
.TP \w'\-n\ nodename\ \ 'u
.B \-v version
set new version to "version"
.TP \w'\-n\ nodename\ \ 'u
.B \-r release
set new release to "release"
.TP \w'\-n\ nodename\ \ 'u
.B \-m machine
set new machine to "machine"
.TP \w'\-n\ nodename\ \ 'u
.B \-u filename
use filename, otherwise /unix is changed
.PP
Without arguments the program reads /unix and /dev/kmem and displays
the utsname structure found at the address in /unix's symbol table.
Updating of /dev/kmem does not take place if the utsname from
/dev/kmem do not agree with uname().
.SH FILES
.ta \w'\-n\ nodename\ \ 'u
.PD 0
/unix	kernel file
.PP
/dev/kmem	memory
.PD
.DT
.SH SEE ALSO
uname(1), uname(2)
.SH AUTHOR
Michael C. Wescott
.SH BUGS
Tower specific code. No way to specify alternate for /dev/kmem.
