.ls 1
.TH NOTE 1 LOCAL
.SH NAME
note \- manage notes on program sources
.SH SYNOPSIS
\fBnote\fR [\fB\-e\fR] [\fB\-s\fR] [\fB\-r\fR [program ...]]
.SH DESCRIPTION
\fINote\fR is a shell script designed to manage notes on sources, such
as what they are, where and whom they came from, when they were
received/created, and whether or not they work.
It is primarily intended for keeping track of software recived via
the Usenet news network.
.sp
With no options, \fInote\fR appends lines from standard input
to a file called ``NOTES'' in the current directory. 
The format of a NOTES file is:
.sp
.nf
.in +0.7i
.ta 0.8i
program:	[Mmm dd yy] comments ...
<\fI1 tab\fR>	more comments
<\fIblank line\fR>
.sp
.fi
.in -0.7i
.TP
\fB\-e\fR	edit the NOTES file using $VISUAL as the editor.
If VISUAL is not set, \fInote\fR looks for $EDITOR, and if that is
also not set, defaults to ``/usr/bin/vi''.
.TP
\fB\-r\fR	show all notes on the given program(s), or the entire NOTES
file (unsorted) if no program is given, piped through $PAGER (unless
PAGER is \fIcat\fR).
.TP
\fB\-s\fR	show the entire NOTES file, sorted so all notes on a
given program occur together, piped through $PAGER.
.SH ENVIRONMENT VARIABLES
.ta 1.3i 3i
.nf
\fBName	Default	Purpose\fR
.sp
PAGER	/usr/local/bin/more	Used to page output
VISUAL	/usr/bin/vi	Used to edit the NOTES file
EDITOR	none	Used if VISUAL is not set
.fi
.SH FILES
.ta 1.3i
./NOTES	file where notes are kept
.br
/tmp/note$$	temporary files
.SH SEE ALSO
\fIsavesrc(1L)\fR
.SH AUTHOR
Written by Christine Robertson 1986
.SH BUGS
Please send all bug reports to {linus, ihnp4, decvax}!utzoo!toram!chris.
