.TH VSPELL 1 ""
.SH NAME
vspell \- finds misspellings and helps correct them.

.SH SYNOPSIS
.B vspell
.I filename

.SH DESCRIPTION
.B Vspell
facilitates faster repair of misspellings detected by
.B spell(1).
.B Vspell
runs
.B spell
on the document supplied as an argument.
If there are no spelling mistakes it exits.
If potential misspellings are detected by spell, it captures the
list of candidate words from the output of 
.B spell
and invokes the editor.
If the EDITOR environment variable is set, that editor is used.
Otherwise
.B vi(1).
.P
You may correct any misspelled words using the editor.
When the editor is exited, the changed words are used to
construct an
.B ex(1)
script which is applied globally to the original document.
The editor script takes account of a misspelled word which may
occur as a substring within another word.
.SH SEE ALSO
spell(1), ex(1)
