.TH PM UCD "16 October 1985"
.SH NAME
pm \- computer version of PacMan
.SH SYNOPSIS
.B pm
[
.B -s
] [
.B -p
] [
.B -Bn
]
.SH OPTIONS
.TP
.B \-s
Print out the list of scores.
.TP
.B \-Bn
Specify the baud rate which you are using.
.TP
.B \-p
Print list of players.
.SH DESCRIPTION
.I Pm
is a UNIX version of the popular arcade game PacMan.
The player, represented by the `@' symbol, attempts to score as many
points as possible.  He does this by eating the small dots on the
screeen, the energizers, the monsters and fruit.  Each item provides
a number of points as follows:
.sp
.nf
.ta 3i
Dot(.)	10
Energizer(*)	50
Monster	varies
Fruit(%,&,0,etc.)	varies
.fi
.LP
Of course it would be simple if this was all there was to do. 
Unfortunately, the pacman is chased by Groucho, Zeppo, Harpo and Chico
which are represented by G, Z, H and C respectively.  If they ever
run into the pacman, he is eaten and loses a life (you begin the game
with three).  However, pacman can retaliate by eating an energizer.
When this happens, the characters representing the monsters become
lower case and pacman will be able to eat them.  But beware, the
opportunity to do this is short.
.LP
The points gained for eating monsters vary based on the number consecutively
consumed.  This is probably related to the fact that the monsters
tend to move more quickly as the game continues.
In addition, fruit is worth more as the pacman continues.
.PP
.TP
.I List of Commands
.nf
.ta 3i
!	exec a shell
b	toggle beeping
f	toggle speed
h	move left
j	move down
k	move up
l	move right
p	pause
q	quit
SPACE	stop
.fi
.LP
Players will discover several interesting features in the game.  For
one, the monsters will become faster and more aggressive as the game
goes on.  For another, players may notice that the monsters have their
own personalities; it has been postulated that this is related to
the favorite machines of the author.
.LP
Normally the game does not generate beeps, but the player can cause
.I pm 
to beep whenever the pacman eats anything with the
.B b
command.  In addition, the game
pauses after each cycle.  These pauses may be shortened with the 
.B f
command.
.SH FILES
*/pm_roll	list of the top ten
.br
*/pm_user	list of who plays
.SH AUTHOR
Peter Costantinidis, Jr., University of California, Davis
.SH DIAGNOSTICS
Occasionally complains when strange things seem to occur in the tunnel.
.SH BUGS
.I Pm
is at less than its best at terminal speeds of less than 9600 Baud.
In addition, the algorithm
.I pm
uses to simulate real time is very cpu intensive, and thus the game is
expensive to play.
