# Makefile for program 'p2c' on MS-DOS, Microsoft C 4.0

CFLAGS = -Zi -W3
CC = cl

#default: p2c.exe
#	echo Done.

p2c.obj: p2c.c p2c.h ktypes.h
	$(CC) $(CFLAGS) -c p2c.c

proc.obj: proc.c p2c.h ktypes.h
	$(CC) $(CFLAGS) -c proc.c

doalloc.obj: doalloc.c
	$(CC) $(CFLAGS) -c doalloc.c

p2c.exe: p2c.obj proc.obj doalloc.obj
	$(CC) $(CFLAGS) -F3000 p2c.obj proc.obj doalloc.obj
