.TH flst 1 "Digital Research, Inc."
.SH NAME
flst - fast listing sub-tree
.SH SYNOPSIS
flst [-d] [directory(s)]
.SH DESCRIPTION
.I Flst
lists a tree file system or systems specified in the argument
with indentation reflecting the level
of nesting of the file in the file system. If no argument is
given
.I flst
takes the current directory as default.
.TP 5
.B  \-d
Only print out directory names, rather than all files.
.SH SEE ALSO
ls(1), lstree(1)
.SH DIAGNOSTICS
.br
It cannot list files nested more than twenty levels.
