.TH ROBOTS 6 "2 November 1984"
.SH NAME
robots \- a game of logic
.SH SYNOPSIS
.B /usr/games/robots [-s]
.SH DESCRIPTION
.B Robots
is a display-based game which must be played on a CRT terminal
from among those supported by vi(1).
The object of the game is to avoid the robots:
causing them to collide with each other, creating a
.IR scrap\ heap .
Robots are also destroyed if they run into a
.IR scrap\ heap .
.PP
You are represented on the screen by an I.
The robots are represented by `=' signs.
Scrap heaps are represented by `@' signs.
After each move, all robots move one step towards you.
.PP
The following commands are recognized:
.IP h
Move left.
.IP l
Move right.
.IP j
Move down.
.IP k
Move up.
.IP y
Move up and left.
.IP u
Move up and right.
.IP b
Move down and left.
.IP n
Move down and right.
.IP .
Do nothing.
.IP t
Teleport.
.IP s
Sit and watch.
.IP d
Display dots.
.IP m
Print list of `safe' moves.
.IP ?
Same as above.
.IP q
Quit game.
.IP ^R
Redraw the screen.
.IP ^Z
Suspend the game, on systems which support it.
.PP
A command may be preceeded by a count where relevant.
.I Shift\-direction
moves as far as possible in that direction.
.I Control\-direction
moves until adjacent to something.
.PP
A record is kept of the personal best scores of each player:
one for the current week and one for all time.
Scores are printed out at the end of the game.
The scores can be printed out with the '\-s' argument.
.SH NOTES
At the start of each level, you have a number of
.I free teleports.
These are teleports which are
.I guaranteed
not to land you next to a robot.
The number you have remaining is shown at the bottom left-hand corner
of the screen within angled brakets.
At the start of the level, you are given one, two or three free teleports.
This number starts off as one and increases as follows.
If you have one free teleport per level, and you save it,
you will get two per level.
If you have two (or more) free teleports, and you save them both,
you will get three per level.
If you have two free teleports, and you save one of them,
you have a 50% chance of getting three per level.
Where there are two numbers, the second indicates free teleports saved from
the previous level.
.SH FILES
.nf
/usr/games/lib/robots_tmp	this week's best scores
/usr/games/lib/robots_hof	all time best scores
.fi
.SH AUTHOR
Allan Black, Strathclyde University, Glasgow.
