.TH HDATE 6 "4 Dec 1985"
.UC 4
.SH NAME
hdate, hcal \- hebrew date and calendar
.SH SYNOPSIS
.B hdate
[
.B \-j
] [
.B \-h
] [ day month year ]
.PP
.B hcal
[
.B \-j
] [ month ] year
.SH DESCRIPTION
.I Hdate
translates the specified date to the Hebrew calendar.
If no arguments are given, it uses today's date.
`month' is a number between 1 and 12.
If `year' is less than 100, 1900 is added.
.PP
If the 
.B \-h
option is specified, 
.I hdate
takes the given date as a hebrew date, and translates it
back to the common calendar.
Months are numbered with Tishrey being 1 and Elul 12; Adar2 in
a leap year (me`ubereth) is specified by adding 30 to the day
(thus Purim is either 14/6 or 44/6).
Note that for dates in the 2nd half of the 20th century A.D.,
`year' should be in the 5700's.
.PP
.I Hcal
prints a calendar with both common and Hebrew dates for the
specified month, or the whole year if no month is specified.
Biblical holidays are marked by `*', other holidays by `+'.
.PP
If the
.B \-j
option is specified the given or output common date is
set in the (old) Julian, rather than the (current) Gregorian calendar.
This option is default for years before 1582 (5342 Hebrew).
With this option, 1900 is
.I not
added to years before 100.
.SH "SEE ALSO"
date(1), cal(1)
.SH AUTHOR
Amos Shapir, NSTA
.SH BUGS
These programs use the currently held method of computing
the Hebrew calendar, which has been in use only since the 9th century.
