.TH RM-DAMNIT 1 LOCAL
.SH NAME
rm-damnit  \- remove stubborn files
.SH SYNOPSIS
.B rm-damnit
.PP
.SH DESCRIPTION
.I Rm-damnit\^
removes the entries for one or more
files
from a directory.
If an entry was the last link to the file, the file
is destroyed.
Removal of a file requires write permission in its directory,
but neither read nor write permission on the file itself.
.PP
.I Rm-damnit\^
is intended to be used to remove files which rm(2)
can not remove because they contain improper names.
(Rm(2) will not remove files with improper names such as those 
with imbedded spaces, characters with the high bit set or imbedded
zeros.)
.PP
Rm-damnit prints each file name in the current directory in turn.
(Invalid characters are printed as question marks.) 
After each name, it prompts with a question mark.
You may type y to remove the file, or q to quit the program.
Any other character will cause the program to go on to the next file.
(Be careful.  If you remove a file, the file is irretrievable.)
.SH SEE ALSO
rm(2).
.SH DIAGNOSTICS
Rm-damnit will prompt for all entries in a directory, regardless of
whether or not it has permission to remove them.  If the prompt is
responded to with a 'y', it will try to unlink the file even if it
does not have permission.  If the unlink fails, the message:
.RS
"Remove Failed"
.RE
will be output.
