.TH HOLDSCREEN 1 LOCAL
.SH NAME
holdscreen \- screen locker
.SH SYNOPSIS
.B holdscreen command
.SH DESCRIPTION
.I Holdscreen
executes its arguments as a child process
and waits until standard input is ready
to read.
.I Holdscreen
then kills the screen holder process, clears the screen and exits.
This is usually done by pressing a key on the terminal keyboard.
Since
.I holdscreen
runs in RAW mode, any key may be pressed.
.SH BUGS
.I Holdscreen
was developed for use on SUN workstation displays, so the screen clear
sequence is coded in.  For more general usage,
.IR termcap (5)
should be used.
.SH AUTHOR
Clyde Hoover @ Computation Center, The University of Texas at Austin
.br
clyde@ngp.UTEXAS.EDU, !seismo!ut-ngp!clyde
