.TH DIS6502 1 "1 OCT 1986"
.UC 4
.SH NAME
dis6502 \- Disassemble 6502 object code
.SH SYNOPSIS
.I dis6502
[
.I \-b 
]
[
.I -p \fIpfile\fP 
]
.I file
.LP
.SH DESCRIPTION
.I  Dis6502
disassembles 6502 binary files.  Binary formats understood include
Atari binary files (L menu command) and boot files.
Equate and control files can be included via the
.I -p
option to name well known locations and to control the dissassembly
process.  The output includes a cross reference.
.PP
The dissassembly process is a two pass operation:  First the program
flow is traced starting with the init and run parameters in the file
headers.  The dump routine then prints out the information.
.PP
The command line options are:
.TP
.I \-b
Assume that the file is a boot file, not a load file.
.TP
.I \-p \fIpfile\fP 
Read in the predefine file \fIpfile\fP.
Up to 20 \fI-p\fP options may be included.
.PP
Lines in pfile consist of:
.PP
 lineno name .eq number
.PP
 .stop number
.PP
 .trace number
.PP 
.I Lineno
refers to a decimal number.  
.I Number 
may be a decimal number or
may be a hexadecimal number (the first character of the number
should be "$").  For example, "$21b5" is
the hexadecimal number 21b5.
.I Name
is a sequence of numbers and characters starting with a
letter.
.I .trace 
causes
the trace process to continue at the address given.  
.I .stop
causes the
trace process to stop at the address given.
.SH AUTHOR
Robert Bond
.SH BUGS
