#define GS 29
#define RS 30
#define SI 15
#define SO 14
#define ETB 23
#define EOT 4
#define ETX 3
#define ESC 27
#define SUB 26
#define ENQ 5
#define TEK 1
#define HP 0
#define NULL 0
#define CR 13
#define FF 12
#define X 1
#define Y 2
#define CCS 3
#define CVT 4
#define CD 5
#define DEBUG 7
#define FD 6
#define LF 10
#define VT 11
#define BS 8
#define CM 0
#define US 31
#define FILL 8
#define HPBS 9
#define HPBC 10
#define HPBP 11
#define FDI 12
#define BLACK '1'
#define RED '2'
#define GREEN '3'
#define BLUE '4'
