.pl 72
.TH SCAME 1 1985-02-09
.SH NAME
scame - a screen oriented text editor a la emacs
.SH SYNOPSIS
.I scame
[-n] [filename]
.SH DESCRIPTION
.PP
If
.I filename
is specified,
.I scame
will search through its buffers for it.
If it isn't found, it will be read in into a new buffer.
The flag -n will make 
.I scame
forget about earlier work, starting with a fresh buffer. This is hardly
ever necessary.
.PP
.ta 17
This is the
.I scame
Command Chart:
.nf

To get a C-A (Control-A) hold down the 'Ctrl'-key and type an 'A'.

If your terminal has a 'Meta'-key:
To get a M-A (Meta-A) hold down the 'Meta'-key and type an 'A'.
To get a C-M-A (Control-Meta-A) hold down both the 'Ctrl'-key and
the 'Meta'-key and type an 'A'.

If your terminal lacks 'Meta'-key:
To get a M-A (Meta-A) first type an 'Esc' and then an 'A'.
To get a C-M-A (Control-Meta-A) first type a C-Z and then an 'A'.

.bp
.I Control Characters:

C-@	^R Set/Pop Mark
C-A	^R Beginning of Line
C-B	^R Backward Character
C-C	^R Exit To Shell
C-D	^R Delete Character
C-E	^R End Of Line
C-F	^R Forward Character
C-G	^R Quit
C-H (Backspace)	^R Backward Character
C-I (Tab)	^R Indent According to Mode
C-J (Linefeed)	^R Indent New Line
C-K	^R Kill Line
C-L	^R New Window
C-M	^R New Line
C-N	^R Down Real Line
C-O	^R Open Line
C-P	^R Up Real Line
C-Q	^R Quoted Insert
C-R	^R Reverse Search
C-S	^R Incremental Search
C-T	^R Transpose Characters
C-U	^R Universal Argument	(Must be in the range 0..32767)
C-V	^R Next Screen
C-W	^R Kill Region
C-X	is a prefix character. See below
C-Y	^R Un-Kill
C-Z	^R Prefix Control-Meta
C-[ (Escape)	^R Prefix Meta
C-\\	^R Prefix Meta
C-_	^R Help
C-^	^R Prefix Control
RubOut	^R Backward Delete Character

.bp
C-X is a prefix command with these subcommands:

C-X C-B	List Buffers
C-X C-D	^R Directory Display
C-X C-F	Find File
C-X Tab	^R Indent Rigidly
C-X C-L	^R Lowercase Region
C-X C-O	^R Delete Blank Lines
C-X C-S	^R Save File
C-X C-U	^R Uppercase Region
C-X C-V	^R Visit File
C-X C-W	Write File
C-X C-X	^R Exchange Point and Mark
C-X C-Z	^R Exit To Shell
C-X (	^R Start Kbd Macro
C-X )	^R End Kbd Macro
C-X .	^R Set Fill Prefix
C-X 1	^R One Window
C-X 2	^R Two Windows
C-X ;	^R Set Comment Column
C-X =	What Cursor Position
C-X B	Select Buffer
C-X D	^R Dired
C-X E	^R Execute Kbd Macro
C-X H	^R Mark Whole Buffer
C-X K	Kill Buffer
C-X L	^R Count Lines Page
C-X M	Send Mail
C-X O	^R Other Window
C-X R	Read Mail
C-X Z	^R Exit To Shell
C-X ^	^R Grow Window
.bp
.I Meta Characters:

M-Return	^R Back to Indentation
M-!	^R Shell Command
M-%	^R Query Replace
M-(	^R Make ()
M-+	^R Invoke Inferior Shell
M-0 .. M-9	^R Autoargument
M-;	^R Indent for Comment
M-<	^R Goto Beginning
M-=	^R Count Lines Region
M->	^R Goto End
M-@	^R Mark Word
M-A	^R Backward Sentence
M-B	^R Backward Word
M-C	^R Uppercase Initial
M-D	^R Kill Word
M-E	^R Forward Sentence
M-F	^R Forward Word
M-G	^R Fill Region
M-I	^R Tab to Tab Stop
M-K	^R Kill Sentence
M-L	^R Lowercase Word
M-M	^R Back to Indentation
M-O	is a prefix character (not documented)
M-T	^R Transpose Words
M-U	^R Uppercase Word
M-V	^R Previous Screen
M-W	^R Copy Region
M-X	Instant Extended Command (see below)
M-\\	^R Delete Horizontal Space
M-^	^R Delete Indentation
M-~	^R Buffer Not Modified
M-RubOut	^R Backward Kill Word


.I Control-Meta Characters:

C-M-%	^R Query Replace
C-M-L 	^R Log Out
C-M-M	^R Back to Indentation
C-M-T	^R Display Date
C-M-V	^R Scroll Other Window
C-M-W	^R Append Next Kill
C-M-X	Extended Command (same as M-X)
C-M-Z	^R Exit


Most printable characters, i e non-control non-meta characters,
are self-inserting.
.bp
.ta 30 38
.I Extended commands:
(T means toggle)
M-X Ada Mode	For editing ADA programs
M-X Auto Fill Mode	A minor mode, useful when entering text
M-X C Mode	For editing C programs
M-X CBREAK Mode	Enable signals from kbd. OS dependent.
M-X Change Directory	Change the working directory
M-X Check Mail	Tell if there is new mail
M-X Default Mode	Set mode according to file type.
M-X Delete Matching Lines	Delete all lines containing a pattern.
M-X Dired	Call the Dired program (if available).
M-X Find File	Find the buffer with a certain file in it.
M-X Fundamental Mode	When nothing else applies
M-X Insert Character	Given an argument, inserts the character
		with the corresponding ASCII code
M-X Insert File	Asks for a file to insert at point
M-X Kill Buffer	Remove a buffer and its contents.
M-X Lisp Mode	For editing LisP code
M-X List Buffers	Show a list of existing buffers.
M-X Load Kbd Macro	Read keyboard macro from a file.
M-X Overwrite Mode	A minor mode for overwrite instead of insert.
M-X Pascal Mode	For editing Pascal programs.
M-X Push to Shell	Invokes a (temporary) inferior Shell.
M-X Read Mail	Invoke the mail program.
M-X Replace String	Replace from point to end of buffer
		(not query)
M-X Revert File	Restores file from disk
M-X Rot 13 Region	Encrypt/decrypt offensive text.
M-X Save Kbd Macro	Write keyboard macro to a file.
M-X Select Buffer	Change to another buffer.
M-X Send Mail	Mail current buffer to somebody.
M-X Set Key	Put a function on a key.
M-X Set Variable	Given an argument, will change the value
		of a variable
M-X Sort Buffer	Sort all lines in alphabetical order.
M-X Stop	Stop scame temporarily.
M-X Swedish Mode	For editing swedish text
M-X Tabify	Convert spaces into tabs where possible,
		starting from point.
M-X Undo	Try to undo the last command. Only some
		commands may be undone.
M-X View File	Show a file without creating a new buffer.
M-X View Variable	Show the value of a named variable
M-X View Working Directory	Type out the current working directory
M-X Wall Chart	Make a command chart of current bindings.
M-X What Cursor Position	Show stats on the echo-line.
M-X Write File
M-X Write Region	Write out the region to a file.
	(Does not change the current filename).
.bp
.ta 23 30 38
.I Variables:
 (default values within parentheses, L means local to buffer,
M means dependent on Mode)
Auto Fill Mode	(0 L)	Controls the corresponding minor mode.
Auto Push Point Option	(500)	Controls wether to set mark after search.
Bottom Display Margin	(100)	Don't let cursor past this percentage
			of screen.
Comment Column	(33)	Used by M-; to decide where to start
			a comment.
Display Matching Paren	(M L)
Fill Column	(72 L)	Used by Fill Region and Auto Fill Mode to
				decide where to break lines.
Hackmatic		Will be nonzero if the terminal 
			has a META-key.
Mail Check Interval	(100) How often to check for mail. (0 -> never);
Overwrite Mode	(0 L)	Controls the corresponding minor mode.
Quote Char	(17)	Character to quote next char. (Normally ^Q)
Search Backward	(18)	Backward search character in
			Reverse I-Search. (^R)
Search Exit Char	(27)	Character to exit I-Search and do
			nothing. (Escape)
Search Forward	(19)	Forward search character in I-Search. (^S)
System Output Holding	If nonzero, will make scame ignore ^S
	(0)		and ^Q, using C-] for C-S
			and C-^ for C-Q instead.
Tab Self Insert	(0)	Controls the action of TAB when in 
			Pascal or C Mode.
Top Display Margin	(0)	Don't let cursor in this percentage
			of screen.


.bp
.fi
.I Terminal types:

You can specify what kind of terminal you are using by including
the following line in your file .profile (which is executed
every time you log in):

TERM=<terminal type>; export TERM

where <terminal type> is one of the names listed in the file
/etc/termcap

If you are using the C-shell, i\.e\. the one with the % prompt,
you should have the line "set term=<terminal type>" in
the file \.login instead.


.I Startup scripts
.br
The file .scamerc is executed the first time
.I scame
is started
from a particular shell. This is a file containing a keyboard
macro, i.e. the same command sequences that are used from the
keyboard. It is searched for in the current directory, in the
home directory and finally in the SCAMELIB directory.

The easiest way to create this file is to define a keyboard
macro in
.I scame
and then write it out using M-X Save Kbd
Macro. 


.I Mode Hooks
.br
In the same way, the file .scamerc_<modename> is executed
every time a buffer is set to a major mode with name
<modename>. I.e. the file $HOME/.scamerc_pascal is executed
when entering Pascal Mode.


If you run into any problems with
.I scame,
let me know.
.br
.SH DIAGNOSTICS

.SH FILES
/usr/scame/lib/*
.br
/usr/scame/tmp/Snnnnnnnnnn.x
.br
.SH AUTHOR
Leif Samuelsson 
.br
leif@erisun.UUCP  or  ..decvax!mcvax!enea!erix!erisun!leif
