.TH KEEPNEWS 1 
.UC 4
.SH NAME
keepnews \- selectively archive (keep) news articles in a common location
.SH SYNOPSIS
\fBkeepnews\fP [ -n additional.newsgroups ] [ -t more subject line ]
.SH DESCRIPTION
\fIkeepnews\fP accepts a news article on standard input, analyzes the
headers of the article and stores the article in a file.  Articles
are stored as individual files in a tree structure matching that of
the newsgroup hierarchy.  The Article-I.D. is used to uniquely
identify an article; each article is stored only once.  If an article
is associated with multiple newsgroups, it is linked into all
appropriate directories.
.PP
The directory \fI/usr/spool/keepnews\fP serves as the root of
the \fIkeepnews\fP
tree.  If an article, \fIsomesite.100\fP
for example, is posted to net.general and
subsequently archived, it is stored in
\fI/usr/spool/keepnews/net/general/somesite.100\fP.
Log files which contain
information about articles that have been kept are
maintained in both the root directory and individual group
directories.  Log files do not record any information about who
kept an article.
.TP
.B \-n
The remaining arguments (to the next -n, -t, or newline) will be
taken as additional newsgroups, eg.,
\fB-n\fP
\fInet.additional.group.1 net.additional.group.2\fP.
The additional groups will only be added to the newsgroup field of
the related log files.
.TP
.B \-t
The remaining arguments (to the next -n, -t, or newline) will be
taken as additional information for the article subject, eg.,
\fB-t\fP
\fIadditional subject material\fP.
This will only be added to the subject field of the related log files.
.SH PURPOSE
\fIkeepnews\fP is an attempt to provide a sane way of extracting and
keeping information that comes over Usenet.  The basic idea
is to allow users to designate an article as being of some worth and
then save it in a common place.  Thus, \fIkeepnews\fP provides an
alternative to personal archival of news articles.
.SH USAGE
Because there are a variety of news reading programs available,
the exact usage of \fIkeepnews\fP depends on the program being used.
If \fIreadnews\fP is being used, responding with
.br
.ti 1i
\fBs- |keepnews\fP
.br
to the \fB[ynq]\fP prompt that appears after an article will cause
the article to be kept.  \fIkeepnews\fP produces no messages unless an
error occurs.
.SH "SEE ALSO"
\fIreadnews(1)\fP, \fInews(5)\fP
.SH BUGS
If \fIkeepnews\fP is given something that doesn't appear to be a news
article, a program abort may occur.
.PP
Some news reading programs (including \fIreadnews\fP) will prepend
a summary header line to redirected standard output that is subsequently
included in the archive created by \fIkeepnews\fP.  It is harmless.
