.TH DIAL 1L
.SH NAME
dial \- switch a tty line between incoming and outgoing
.SH SYNOPSIS
.B /etc/dial in|out [ ttyxx ]
.SH DESCRIPTION
.I Dial
switches the designated tty line from an incoming (login) line to an
outgoing (nonlogin) line, or vice versa.  This can useful, for example,
when a single modem must serve both as a login line, and as a dialout
line.
.sp
.I Dial
takes either one or two arguments.  The first argument is either the
word "in" or the word "out", to designate whether the tty line is to be
incoming or outgoing.  The second (optional) argument is the name of the
tty line, such as "ttyd0" or "ttyie".  If given, the tty name is checked
against those in the file "/etc/dial-lines" for permission.  If the
second argument is omitted, the tty given on the first line of that file
is used.
.sp
.I Dial
must be setuid to root for the actions which it must take.  It is
recommended that /etc/dial-lines be owned by root also.
.SH FILES
/etc/dial-lines
.br
This file lists the ttys which can be affected by
.I dial.
The format is one tty name per line.
.SH AUTHORS
.nf
Gertjan Vinkesteyn
.sp
Stephen McConnel
Summer Institute of Linguistics
7500 W. Camp Wisdom Road
Dallas, Texas 75236
.fi
.SH DIAGNOSTICS
.nf
cannot open `/etc/dial-lines'
/etc/dial-lines is empty
invalid tty line requested
/usr/spool/uucp/LCK..ttyxx already exists
root or uucp does not own /dev/ttyxx, somebody might be logged on
.fi
