.\"	Copyright 1987 Jonathan Biggar
.\"
.\"	Permission is given to copy and distribute for non-profit purposes.
.\"
.TH SPACEWAR 6 "16 December 1986"
.SH NAME
spacewar \- multi-user science fiction combat game
.SH SYNOPSIS
.B /usr/games/spacewar
[ \fB-s\fIx\fR ]
.SH DESCRIPTION
.I Spacewar
is an arcade-like game inspired by the original game written for a PDP-1.
Each user controls a single ship on the screen.  The object of the game
is to shoot your opponents with your missiles while avoiding their missiles.
.PP
The display is divided into two areas:  the main window, which shows the
positions of all ships and missiles, and the score window, which shows the
names and scores of all players that are active.  When a player's ship is
destroyed, buttons will pop up in the score window to allow the
user to re-enter the game.
.PP
A ship is represented on the screen by an isosceles triangle, a missile by
a point.  Each user's ship will be highlighted on his screen by a stripe
down the middle of the ship.  Sometimes there will be a sun in the middle
of the screen, with gravity that either attracts or repels all other
objects.
.PP
The player maneuvers his ship with the mouse buttons:
.RS
.IP LEFT 8
rotates the ship counter-clockwise
.IP MIDDLE 8
fires the ship's thrusters
.IP RIGHT 8
rotates the ship counter-clockwise.
.RE
.PP
Striking the carriage return key on the keyboard will activate the ship's
shields.  The shields will protect the ship from destruction for two seconds,
after which the shields may not be re-activated for eight more seconds.
.PP
Striking the escape key will exit the game.
.PP
Striking any other key on the keyboard will fire one missile.  A ship may
only fire five missiles at a time.  A player will receive points for
hitting another ship:  ten percent of the difference in scores between the
target and firing players, but always at least one point.
.PP
A ship is destroyed by being hit by a missile, or running into the star or
another ship.  Running into the star or an asteroid will deduct one point
from the player's score.
.PP
.SH OPTIONS
.IP \fB\-c\fIx\fR
Set the shield activation key to \fIx\fP.
(\en, \er, and \eb are understood).
.SH DIAGNOSTICS
.SH FILES
/usr/games/lib/spaceward		spacewar daemon
.br
/usr/games/lib/spacewar.{dir,pag}	spacewar score file
.SH AUTHOR
Copyright 1987 Jonathan Biggar
.br
<jonab@SDC-CAMARILLO.ARPA> or <sdcrdcf!jonab>
.SH BUGS
Chews up too many cpu cycles--can only run on a sun-3 with a 68881, and
can't reliably run the game and the daemon on the same machine.
.PP
Can only support 3 or 4 users, although there is room for about 20.
.PP
Because it uses udp(4) broadcast packets to find the server ,
the game must run setuid root.
