.TH VMSTAPE 1H
.SH NAME
vmstape \- manipulate tapes in accordance with VAX-VMS standards
.SH SYNOPSIS
vmstape [tcxrvfbdFRHV] [files]
.SH DESCRIPTION
.LP
.I Vmstape
is a program that manipulates the tape format that is the standard for
VMS systems.  The format is based on the ANSI standard for tapes.  The
switches to the
.I vmstape
program are as similar to the switches for
.I tar
as possible.
.SH SWITCHES
.LP
.I c
is used to
.I create
a new tape with the named files on it.
All old information on the tape is overwritten.
.LP
.I r
appends the named files to the end of the tape. All old information
is unchanged on the tape.
.LP
If a directory name is passed as an argument to the 
.I c
or
.I r
switches, all the files in the directory will be written on the tape.
.LP
.I t
reports a directory listing of the files on the tape.
.LP
.I x extracts 
the named files from the tape.  If no individual files are
specified, then all files are extracted from the tape.
.LP
All other switches are modifiers to these basic commands.  Not all modifiers
are applicable to all the commands.
.LP
.I v
causes a
.I verbose
output describing the programs actions on the tape.
.LP
.I f
is used to specify an alternate magtape device.  The default
assumes the tape is 1600 bpi density and will rewind the tape when the
program is done.
.LP
.I d
divides the tape into sections so that the VMS "directory" command will
list the tape in sections.  This is useful when writing subdirectories in
UNIX.
.LP
.I b
is used to change the default block size to the length specified.
.LP
.I V
is used to specify an alternate volume label.
.LP
.I F
is used to indicate that files are NOT textual, and should therefore be 
written in a fixed length format.
.LP
.I R
is used to change the default fixed length record size to the length 
specified.
.LP
.I H
provides a help screen.

.SH SEE ALSO
tar(1), tp(1), mtb(8), retrieve(8)
.SH DIAGNOSTICS
.LP
Improperly formatted tapes, not made in agreement with the VMS standard,
may generate missing tape mark errors.
.LP
Problems with the tape and/or magtape drive will generate messages to the
effect that the program was unable to read or write the tape.
.SH BUGS
.LP
As DEC changes the standard for VAX-VMS tapes,
the program will need alterations.
.LP
If the user attemps to write a non-textual file without the F (or R) switch,
the file will not be completely written.  
