.TH GIVE sd
.SH NAME
give \- change owner and group information for one or more files
.SH SYNOPSIS
.B give
.I file...
.B to
.I user
[\c
.I group\c
]
.SH DESCRIPTION
.B Give
will change ownership and group information for the files specified.
If any of the files is a directory,
.B give
will descend and change the entire directory tree, including the named
directory.
.sp
AS might be expected,
.B give
will only work for the current owner of the named files or root.
.SH DIAGNOSTICS
.B Give
will exit with a descriptive error message if any of the
following occur:
.br
.in +0.5i
access to /etc/passwd (and /etc/group, if applicable) is denied
.br
the named user (group) does not occur in the file
.br
files specified cannot be accessed or modified
.in -0.5i
.SH FILES
/etc/passwd \- user list
.br
/etc/group \- group list
.br
