.TH SPLOT 1 local
.SH NAME
splot \- screen plot
.SH SYNOPSIS
.B splot
[ -wWIDTH ] [ -lLENGTH ] [ name ]
.SH DESCRIPTION
.I Splot
is a cheap and dirty plotting program
to plot out X-Y data pairs on your terminal.
Data can come from named files,
or if there are none,
from the standard input.
Thus,
.I splot
is usable as a filter.
.PP
The data is composed of data pairs,
where each data set has
an X value followed by 1 or more spaces
followed by a Y value,
which is terminated by a newline.
A limit of 500 data pairs in currently in effect.
.PP
The size of the graph generated will just fill the screen
of a 24 by 80 character vidio terminal.
To override the default width or length,
use the
.I -w
or
.I -l
options.
.SH FILES
none
.SH BUGS
Data that has an infinite slope causes a floating point exeption error.
