.TH TALK 1 local
.SH NAME
talk \- talk to other users on the system.
.SH SYNOPSIS
.B talk
[ name ]
.SH DESCRIPTION
.I Talk
allows you to talk through your terminal
to anouther user on the system.
.I
Name
is either the user's login name (e.g. davep),
or the base name of the user's terminal (e.g. ttywc).
.PP
After invoking
.I talk,
a message is printed on the other user's terminal which says
you want to talk.
That person then responds by typing
.I talk
without a name.
You will then get a verification saying you are now talking.
Anything typed from now on by either user
will appear on both terminals as it is typed.
.PP
The ``!'' character has a special meaning when typed at the beginning
of a line.
Much like
.I ed,
it allows you to escape to Unix for 1 command,
then return to talk.
The other user is informed that you are busy when you use ``!''.
.PP
Also special is control A.
This causes the message ``<go ahead>'' to be typed on both terminals.
.PP
To get out of talk,
type control D (for End Of File),
or control C (for interupt).
.SH FILES
/tmp/talk/tty?? for interlock files
.SH DIAGNOSTICS
Many.
All should be understandable.
.SH BUGS
