.ds - -
.TH URAND VII 3/27/80
.SH NAME
urand, erand \*- generate random numbers
.SH SYNOPSIS
.ft B
randomize() ;
.PP
rseed(s1,s2)
.br
int s1 ;
.br
int s2 ;
.PP
urand() ;
.PP
erand(n)
.br
int n ;
.ft R
.SH DESCRIPTION
These routines generate random numbers with two different distributions.
.PP
.I Randomize
initializes the random number generator with a seed which is taken
from the system clock with a call to
.I time
(II).
This serves to start the random number generator at a different point
for each time the program is run.
.PP
.I Rseed
stores the parameters into the seeds of the two random number generation
routines.
.PP
.I Urand
generates uniform random numbers from 0 to 32767.
.PP
.I Erand
generates exponentially distributed random numbers with a mean of 'n'.
.PP
These routines use the algorithm described by D. E. Knuth.
.SH "SEE ALSO"
.I sim
(VII)
.SH BUGS
A parameter to
.I erand
which is greater than 3300 may give unpredictable results.
.PP
.I Erand
returns an integer.
It should return a double.
