.\" @(#)dpr.1 1.1 86/01/05 SMI; from UCB 4.2
.TH DPR 1 "5 February 1986"
.SH NAME
dpr \- general purpose screendump
.SH SYNOPSIS
dpr [-Pprinter] [-#num] [-Cclass] [-Jjob] [-f] [-r] [-m] [-h]
.br
    [-Dalternate_dumpcap]
.SH DESCRIPTION
.PP
Dpr will output screen dumps to the specified printer or to a named file
depending upon information found in the appropriate entry of /etc/dumpcap.
.SH OPTIONS
.TP
-Pprinter
Force output to a named printer. Normally, the default printer
is used (site dependent), or the value of the PRINTER environment
variable is used.
.TP
-#num
Produce multiple copies of output, using num as the number of
copies for each file named.
.TP
-Cclass
Print class as the job classification on the burst page. This
replaces the system name (the name returned by gethostname(2)).
.TP
-Jjob
Print job as the job name on the burst page. Normally dpr uses
the filename specified by the "fn" capability switch in the
/etc/dumpcap file or "Current" if no switch was specified.
.TP
-f
Generate the C code necessary to take a file in standard Sun rasterfile
format on standout program input and produce a filtered output version
on standard program output. This could then be incorporated with the
Unix line printer spooling program lpr to produce furthur raster dumps
directly.
.TP
-r
Remove the screen dump file (if specified by "fn" in /etc/dumpcap)
upon completion of spooling.
.TP
-m
Send mail upon completion.
.TP
-h
Suppress printing the burst page.
.TP
-Dalternate_dumpcap
Name of the alternate dumpcap file to use. Dpr will also use the
value of the DUMPCAP environment variable if present.
.SH FILES
/etc/dumpcap       screen dump capabilities data base
.br
/usr/lib/dpr       screen dump printer program
.SH SEE ALSO
dumpcap(5), termcap(5)
