.\" @(#)dumpcap.5 1.1 86/01/05 SMI; from UCB 4.2
.TH DUMPCAP 5 "5 January 1986"
.SH NAME
dumpcap \- screen dump printer capability data base
.SH SYNOPSIS
/etc/dumpcap
..SH DESCRIPTION
.PP
Dumpcap is a simplified version of the termcap(5) data base for
describing screen dump printers. The screendump program dpr(1)
accesses the dumpcap file every time it is used, allowing dynamic
addition and deletion of printers. Each entry in the database
describes one printer.
.PP
The default printer is normally lp, though the environment variable
PRINTER may be used to override this. Dpr(1) uses a -Pprinter option
to explicitely name a destination printer.
.PP
Each entry in the dumpcap file describes a printer, and is a line
consisting of a number of fields separated by ':' characters. The
first entry for each printer gives the names which are known for the
printer separated by '|' characters. The first name is conventionally
a number. The second name given is the most common abbreviation for
the printer, and the last name given should be a long name fully
identifying the printer. The second name should contain no blanks;
the last name may well contain blanks for readability. Entries may
continue onto multiple lines by giving a \ as the last character of
a line, and empty fields may be included for readibility.
.PP
Capabilities in dumpcap are all introduced by two-character codes,
and are of three types:
.TP
Boolean
capabilities indicate that the printer should use some
particular feature. Boolean capabilities are simply written
between the ':' characters, and are indicated by the word
'bool' in the type column of the capabilities table below.
.TP
Numeric
capabilities supply information such as baud-rates, width of
the screen dump and so on. Numeric capabilities are indicated
by the word 'num' in the type column of the capabilities
table below. Numeric capabilities are given by the two-
character capability code followed by the '#' character,
followed by the numeric value. For example: :br#1200: is a
numeric entry stating that the printer should run at 1200
baud.
.TP
String
capabilities give a sequence which can be used to perform
particular printer operations such as initial escape
sequences. String valued capabilities are indicated by the
word 'str' in the type column of the capabilities table
below. String valued capabilities are given by the two-
character capability code followed by an '=' sign and then
a string ending at the next following ':'. For example,
:lp=/dev/ttya: is a sample entry stating that the screen
dump should be output to /dev/ttya.
.PD
.SH CAPABILITIES
.LP
.sp .5v
.nf
.ta \w'k0-k9xxxx  'u +\w'Typexxxx 'u +\w'``/usr/spool/lpd"xxxx  'u
\fBName    Type    Default       Description\fR
.sp .5v
br      num     9600          set the baud rate.
co      num     1             number of colors in output.
dd      bool    false         screen image should be double sized.
ed      str     NULL          sequence to output at end of dump.
el      str     NULL          sequence to output at end of 'line'.
fn      str     NULL          screen image file to use (defaults to
                              current screen).
ha      num     0             handshake between the Sun and printer.
                              (0=None, 1=XON/XOFF, 2=DTR, 3=CTS, 4=RTS)
hs      num     1             number of horzontal lines printer uses in
                              one pass.
lp      str     "/dev/lp"     device name to open for output.
ma      num     0             mask to be used for preparing output.
nb      num     8             bits per byte for output of image.
ro      bool    false         reverse order of bits in graphics byte.
sd      str     NULL          sequence to output at start of dump.
sh      num     900           height of screen dump.
sl      str     NULL          sequence to output at start of 'line'.
sw      num     1152          width of screen dump.
sx      num     0             X origin of screen dump.
sy      num     0             Y origin of screen dump.
vs      num     1             number of vertical lines printer uses in
                              one pass.
.PP
A Sample Entry
.br
To output a complete image of the current screen at double size to a
Toshiba P1350 printer using a CTS handshake over /dev/ttya at 4800
baud, the following entry in /etc/dumpcap should be used:
.PP
lp|to|Toshiba P1350:\\
.br
        :br#4800:lp=/dev/ttya:ha#2:vs#24:hs#1:nb#6:dd:\\
.br
        :sd=\\E^^\\b:ed=\\E^^\\t:sl=\\E;2304:el=\\r:
.SH SEE ALSO
dpr(1),lpr(1),printcap(5),termcap(5)
