.TH CLIENT 1L 85/10/14
.UC 4
.SH NAME
client \- remote command client
.SH SYNOPSIS
.B client
host command
.SH DESCRIPTION
This is a generic network client program,
which is used to connect to \fIserver\fP(8).
It is useful for remote man servers, phone lists, etc.
.PP
The arguments are the name of a host to connect to and a command to
execute.
The arguments are passed to \fIserver\fP(8) on the given host
as a line of input, and any output from \fIserver\fP is copied
to \fIclient\fP's standard output.
Any verification of the command is done by \fIserver\fP(8),
not \fIclient\fP(1).
.SH DIAGNOSTICS
Should be self-explanatory.
.SH FILES
.SH "SEE ALSO"
server(8),
rsh(1).
