.TH ARCHNEWS 1 local
.SH NAME
archnews \- archive expired news to a floppy
.SH SYNOPSIS
.B archnews
floppy directory
.SH DESCRIPTION
.I Archnews
is a program that takes news which has been expired by the news expire utility
and archives it to a floppy disk.  It should be invoked in the root directory
of the tree which is desired to be archived. 
.I Archnews
will print to standard output the subject and summary of the files which
it archives giving easy index to the floppy archives.  The files are
stored after compression via the news compress utility
in the same tree structure as the tree being archived.
.pp
When the floppy device gets full
.I archnews
will fail and may simply be reissued to continue archiving the remaining
files.
.SH AUTHOR
David Albrecht
