.TH CPDIR 1 LOCAL "USGS Pacific Marine Geology"
.SH NAME
cpdir - copy directory (and subdirectories)
.SH SYNOPSIS
.B cpdir
dir1 dir2
.SH DESCRIPTION
.I Dir1
is copied into
.IR dir2 ,
complete with files and subdirectories.
.I Dir2
is created, if necessary.
.PP
Modify and access times of files are preserved;
modify and access times of
.I dir2
(if created) and any subdirectories are not preserved.
Ownership and access modes are preserved for all files and directories,
except for
.I dir2
if it is created.
.SH "SEE ALSO"
cp(1), mkdir(1), mv(1), tar(1)
.SH AUTHOR
Rex Sanders, U.S. Geological Survey, Pacific Marine Geology
...............................................................................
