.TH RS 1 "3 July 1986"
.ad b
.SH NAME
rs \- reminder system
.SH SYNOPSIS
.B rs
[
.B \-Aacknpv
] [
.B \-s
.I string
] [
.BI \-d \0# \0#-#
]
.SH DESCRIPTION
.I rs
is a personal reminder system.
Reminders can be displayed every time you log into the system
by placing the
.I rs
command in your
.I .login
or
.I .profile
file.
The reminder system includes three reminder files:
.nf


	1.	Reminders  ($HOME/.reminders)
	2.	Notes      ($HOME/.rsnotes)
	3.	User defined by setting the RSALT environment variable.
		(Defaults to $HOME/.phone_numbers)
.fi
.PP
.I Options:
.TP
.I rs
With no options, print reminder list to terminal.
.TP
.B \-A
Work with
.I alternate
reminder file.
The name of the alternate file is user defined by setting the
.I RSALT
environment variable.  (If
.I RSALT
is not set, the alternate file defaults to 'phone_numbers'.)
.TP
.B \-a
Add reminders/notes/alternates.
You are prompted to add reminders/notes/alternates.  Appending a ^G (Control-G)
at the end of a reminder will cause rs to mark it (Highlight) during display.  (See
.I RSINIT
below.)
.TP
.B \-c
Add entries to calendar system.  You are prompted to add calendar entries.
See
.I calendar(1).
.TP
.B \-d
Delete reminders/notes/alternates.  This option, followed by a number or
numbers, causes
.I rs
to delete the specified reminders/notes/alternates.
More than one number may be placed on the same command line separated by
blanks.
A range of numbers may also be specified.
.TP
.B \-e
Edit reminders/notes/alternates file.  If the EDITOR environment variable is
set, the specified EDITOR is used.  If not, vi is used by default. (-v may be
used in place of -e)
.TP
.B \-k
Kill (delete) all reminders/notes/alternates.
.TP
.B \-n
Work on
.I notes
file.
.TP
.B \-p
Print reminders/notes/alternates.
(By default, does an
.I lpr
of reminder file.)
.TP
.B \-s
Search for reminders/notes/alternates that match the given string.
.PP
More than one option may follow a single "\-", for example:
.nf
.RS

rs -na    The command for "add note."
.RE
.fi
.PP
.SH NOTES
To mark a reminder (Highlight), append a ^G (Control-G) to the reminder.
.I rs
will mark the reminder during display using one of the following:
.nf


	Standout
	Underscore.
	Bold
	Asterisk

.fi
as defined in
.I RSINIT.
.PP
.I rs
looks in the environment variable
.I RSINIT
for additional configuration options.  Options are:
.nf


A	Display notes/alternates/calendar after additions.
D	Display notes/alternates/calendar after deletions.
a	Display reminders after additions.
d	Display reminders after deletions.
I	Ignore TERMCAP info during startup.
	(Default number of columns is 80, no mark capability)

Default mark is standout mode.
	('so' and 'se' must be defined in termcap entry.)

U	Use underscore (underline) to mark reminders.
	('us' and 'ue' must be defined in termcap entry.)
B	Use Bold to mark reminders.
	('bo' and 'be' must be defined in termcap entry.)
S	Use '*' to mark reminders.
	(Terminal must have 'bs'.)
.fi
.PP
For example,
if you prefer to view your reminders/notes/alternates after
additions/deletions, the
.I csh
command:
.nf


          setenv RSINIT 'aAdD'

.fi
causes
.I rs
to display your reminders/notes/alternates after additions/deletions.
The above command sequence may be placed in your
.I .login
file.
.PP
Reminders/notes/alternates may be from one to 255 characters long.
If a reminder is longer than one line (As defined in termcap 'co'),
.I rs
does automatic word wrap.
To add a reminder/note/alternate longer than one line,
type in the entire reminder/note/alternate and end with a single carriage
return.
Do
.B not
insert carriage returns before the end of a reminder/note/alternate.
A single carriage return
.B always
indicates the
.B end
of a reminder.
.SH EXAMPLES
.TP
rs -d 1 5 8
Delete reminders 1, 5, 8.
.TP
rs -n -d 1-5 8
Delete notes 1, 2, 3, 4, 5, 8.
.TP
rs -k
Kill all reminders.
.SH EXAMPLE USE OF ALTERNATE REMINDER FILE
.PP
If you would like to have a list of phone numbers that can be accessed by the
reminder system, you can do the following:
.PP
Set the
.I RSALT
environment variable to
.I phone-numbers
by including the following command line in your
.I .login
file:
.TP
.I "     setenv RSALT 'phone-numbers'"
.TP
Use the reminder system command:
.TP
.I "     rs -A [options]"
.TP
to work on the phone-numbers reminder file.
.SH EXAMPLE COMMANDS FOR PHONE-NUMBERS REMINDER FILE
.TP
rs \-A \-a
Add phone numbers to the phone-numbers reminder file.
.TP
rs \-A \-s Joslyn
Search for Joslyn's phone number.
.TP
rs \-A \-e
Edit phone-numbers.
.TP
rs \-A \-p
Print phone-numbers on the line printer.
.TP
rs \-A \-d 1
Delete the first line from phone-numbers.
.SH TIPS
To make use of the notes/alternates easier, the author defines two aliases:
.nf

alias rsn 'rs -n'     Use rsn to work with notes file.
alias rsa 'rs -A'     Use rsa to work with alternate file.
.fi
.SH FILES
.nf

$HOME/.reminders    User's reminders.
$HOME/.rsnotes      User's notes.
/tmp/.rs*           Used during reminder deletion.
$HOME/.?            Other reminder file(s) defined by RSALT.
.fi
.SH SEE ALSO
calendar(1), csh(1), environ(7), lpr(1), vi(1)
.SH AUTHOR
.nf
Don Joslyn, Manager
Nova University Computer Center
3301 College Avenue
Fort Lauderdale, Florida 33314
(305) 475-7678
{codas, allegra, ucf-cs}!novavax!don
.fi
