.TH TALK 1
.SH NAME
talk \- inter-terminal screen-oriented communication program
.SH SYNOPSIS
.B talk user
[
.B tty
]
.SH DESCRIPTION
.I Talk
is a inter-terminal conversation program designed
to allow both parties to type at the same time
and still maintain a readable display.
The
.IR curses (3X)
screen-management library is used to handle the
display so you must set your TERM environment variable.
.PP
When you run
.I talk
you give the login name of who you want to converse with.
If they are logged in more than once,
you must also specify which tty of theirs you wish to talk to.
.I Talk
will inform them that you wish to communicate
with them and wait for their response.
If they are slow,
.I talk
will resend its message every 30 seconds until either
they respond or you get bored and hit INTERRUPT.
.PP
A control-L will force the screen to be
redrawn in case it becomes garbled.
.PP
Although the program emulates to Berkeley program of the
same name, the code is 100% original.
.SH AUTHOR
Edward C. Bennett
.SH DIAGNOSTICS
Hopefully self-explanatory.
.SH BUGS
Because of an apparent bug in the SystemV curses package,
if one person backspaces while the other is typing,
text is lost off at least one screen.
