.TH USR 1 "7 June 1985"
.SH NAME
usr \- who's using what machine in the local network
.SH SYNOPSIS
.B usr
[
.B .. chars- .. username ..
]
.SH DESCRIPTION
.I Usr
shows what machines users are logged in on.  Arguments are usernames,
or username prefixes.  The default is to show who's logged in
on all the machines.
.PP
To check for usernames begining with, say, "foo",
invoke "usr foo-" (note the "\-" wildcard).
"Usr \-" is the same as "usr".
.PP
If no report has been received from a machine for 5 minutes, then 
.I usr
assumes that machine is down.
.SH FILES
.B /usr/spool/rwho/whod.*   
.B 	info about local machines
.SH AUTHOR
.B Don Gworek
.SH BUGS
.B If used in during login, 
.I usr
may or may not show the user invoking the program.
