.TH CHAT 1 
.SH NAME
chat \-  Chat with up to 10 users
.PP
cwho \-  See who\'s logged into Chat.
.SH SYNOPSIS
.B chat
.PP
.B cwho
.SH DESCRIPTION
.I Chat,
is a multi-user communications system
which allows a group of users to join in conversation.
The maximum amount of users in a single
.I Chat
session is 10 by default.
.PP
Upon entering
.I Chat
the users logged into the current
Chat session are displayed, along with their tty, and when they
entered.  No prompt will be given but the various system
functions can be accessed at the touch of a key.
.PP
Chat system functions are as follow
.TP
no input
.PP
Without input from the user's terminal,
.I Chat 
will display all incoming
messages from other users along with notification of when users enter
and exit the current chat session.  All messages from other users are
terminated by "<" and include the sender's name, handle, and tty.  A
standard message would look something like this:

05 joeluser(Handle)= This is a test message.<

As of revision 6.0,
.I Chat
now includes wordwrap along with formatting the incoming messages to line
up with the "="'s.   This gives a much more desirable effect and aleviates the
problem with terminals that do not have linewrap.

User login and logout notification is inclosed in asterisks (*) and describes
the current status.  A sample message would looks something like this:

** joeluser logged in/out on 01 **

A user may give themselves a handle by adding the environment variable
HANDLE and defining it to their preference (up to 10 characters).
From sh(1) this can be done by typing:

$ HANDLE="Your Handle Here"; export HANDLE

From csh(1):

% setenv HANDLE "Your Handle Here"

.TP
.I L
List users logged into host system.
.PP
This command prints a list of users logged into the host system,
including their tty and when they logged in. (Similar to who(1))
.TP
.I P
Page a user to come into Chat.
.PP
This command allows a user to page another user who's logged into the
host system.  Upon typing this command a list of all users users is
displayed along with a Job number.  The user will then be prompted to
enter a Job to be paged.  The page will be sent through mail(1) so
as to not disturb the person being paged.
.TP
.I S
Send a message to all users in Chat.
.PP
After typing "s" the user will be prompted with "TEXT>" at which point
the user is to enter his/her message to be sent out.  A
message may be up to 4 lines of 80 characters each and is terminated
by a carriage return.
.TP
.I W
Display all users logged into Chat.
.PP
This command displays the name, handle, time and tty of all users
currently logged into the Chat system.
.TP
.I Q
Exit chat session.
.PP
Upon receiving an INTERRUPT or QUIT signal, as well as the user typing "q",
Chat will exit the current session.
.TP
.I !
Shell escape.
.PP
The shell escape allows a user to execute a command via sh(1).  Time consuming
commands are not advised due to the fact Chat buffers all incoming
messages which would flood the user's terminal upon re-entry to
command returns control to
.I Chat.
.TP
.I ?
Print a command summary.
.PP
This command will print a brief summary of all current
.I Chat
commands.
.TP
.I cwho(1)
.PP
Cwho is essentially a short program which allows a user who's not in the current
chat session to get a listing of the people in it.
.I Cwho
requires no arguments and exits with "No users logged into Chat" if no-one
is currently in
.I chat.
.I cwho\'s
output is essentially identical to that of the
.I chat
command "W".
.PP
All signals received by
.I Chat
, with the exception of SIGALRM and
SIGKILL, will cause
.I Chat
to exit and remove the user from the current logs.
.SH FILES
/etc/utmp       user's in host system
.br
/tmp/ct.*       message buffers
.br
/lib/CHATLOG    log of user's in current chat session
.SH "SEE ALSO"
mail(1)
.SH BUGS
User's handles are left up to their imagination.

Chat doesn't seem to react well to users logged in as root.
