.TH ALERT 1 "27 April 1987" "InterViews" "InterViews Reference Manual"
.SH NAME
alert \- bring up a dialog box
.SH SYNOPSIS
\fBalert\fP [ \fBfont=\fP\fIfontname\fP ] [ \fBbutton=\fP\fIlabel\fP ]
.SH DESCRIPTION
\fIAlert\fP displays a dialog box containing text read from standard
input on a workstation.
A button dismisses the dialog.
.PP
The font used for the text of the message can be specified on the
command line, as can the text of the label on the dismiss button.
.PP
A common use of \fIalert\fP is to display a reminder message at an
appropriate time, under the control of some other program such as
\fIremind\fP\^(1).
.SH "SEE ALSO"
remind(1)
