.TH ISTAT 1 "17 June 1987" "InterViews" "InterViews Reference Manual"
.SH NAME
istat \- workstation statistics display
.SH SYNOPSIS
\fBistat\fP [ host=\fIname\fP ] [ pos=#,# ] [ size=#,# ] [ delay=# ]
.SH DESCRIPTION
\fIIstat\fP displays a graphical representation of various workstation
performance statistics.
.PP
The displays are (from left) the current disk transfer rate, the current
network package IO rate, a histogram of the recent load average, and a
stacked bar graph of the current user, nice and system CPU usage
fractions. The current load average is also shown in the banner, along with
the host name.
.PP
The window's behaviour and placement can be controlled with the following
options :
.TP 8
\fBhost=\fIname\fP\fP
Show statistics for host name (default is the local host).
.TP
\fBpos=x,y\fP
Position the lower left corner at (x,y) relative to the screen lower left
corner (default is to place with the mouse).
.TP
\fBsize=w,h\fP
Set the width of the window to w and the height to h (default is a standard
size).
.TP
\fBdelay=d\fP
Update the display every d seconds (default is every 5 seconds).
.PP
To exit, type 'q' in the window.
.SH "SEE ALSO"
rstatd(8)
