.TH kb 1 "HFVR"
.SH NAME
.\" name \- one-line description for in permuted index
kba, kbc, kbk, kbq, kbu, kbx, kbr \- to work on knowhow database
.SH SYNOPSIS
.\" bnf on command syntax
kba [-e]
.br
kbc [-d] <query>
.br
kbk [-d] <query>
.br
kbq [-d] <query>
.br
kbr
.br
kbu [-d] <query>
.br
kbx [-d] <query> <command>
.SH DESCRIPTION
.\" semantics
kb (Knowledge Base) is a simple database to store items of
information. The items can then be
retrieved from this database via any key words.
.sp
kba [-e] will prompt for info which is then stored into the knowhow
database. When the -e option is given the $EDITOR is used to enter
the information.
.sp
kbc <query> will give count of items from knowhow database which
are specified by the <query> (see below).
.sp
kbk <query> will print out the keys (filenames)
of the items from the knowhow database
which are specified by the <query>. (See below).
.sp
kbq <query> will print all items from the knowhow database which 
are specified by the <query> (see below).
.sp
kbr will recreate the database from the old format into the current format.
(only needed for old versions).
.sp
kbu <query> will present all items which are specified by <query> (see below)
to the editor one by one. After the edit session the items are updated in the
knowhow database.
.sp
Kbx <query> <command> will execute <command> for each item specified by
<query> (see below). The first argument of the <command> is the name of
the file with the information in it.
.SH QUERY
The <query> can be described in BNF as follows:
.nf
<query> ::= <term> { OR <term> }*

<term> ::= <factor> { AND <factor> }*

<factor> ::=   <key>
                | NOT <factor>
                | ( <query> )

<key> ::= <anything alphanumeric lower case only>

STANDARD        ALTERNATIVES
--------        ------------
NOT             !       ~       not
AND             &       &&      and
OR              |       ||      or
(               [       {       <
)               ]       }       >
.fi
.SH OPTIONS
.tr ^
.in +6
.ti -6
-d^^^^turns on debug mode, to show internal KBCODE. (For experts only).
.in -6
.SH EXAMPLES
.nf
kba      # just follow the prompt
kba -e   # use $EDITOR to input information
kbq test # list all items with keyword 'test'
kbq 'test or trial' # list all item with keywords test or trial
kbq 'sh & not ksh'  # list all items about sh but not about ksh
kbu test # edit and update all items with keyword 'test'
.fi
.SH FILES
$HOME/.knowhow.*
.SH VARABLES
.nf
$EDITOR set to favorite editor (default is /bin/ed)
$KNOWHOW set to knowhow database (directory)
.fi
.SH TRICKS
You can use any directory as knowlegde base try for example:
.nf
         KNOWHOW=/usr/news
         export KNOWHOW
         kbq down

.fi
This will list all news items with the key 'down' in it.
.SH ATTENTION
The knowhow database is implemented as a simple directory. All files
in this directory are scanned for the required keys. It is up to the user to 
keep this directory clean.
.sp
The keys are treated with upper and lowercase folded. So there is
not difference between key and KEY.
