.TH RU 1
.SH NAME
ru - list of users on local network
.SH SYNOPSIS
ru [-t]
.SH DESCRIPTION
.I ru
is a shell script which pipes the output of 
.I rwho(1)
through the filter
.I ruf.
The filter output is a list of local hosts followed by the users logged in on
those hosts.  The format is meant to be similar to the output of
.I users(1).
The 
.B \-t
option causes
.I ru
to print the user's terminal after their name.
.SH AUTHOR
Marc Majka
