.TH NEWSCNT 1 LOCAL
.SH NAME
newscnt \- count unread network news based on user's newsgroup
choices
.SH SYNOPSIS
.B newscnt
[ 
.BR - { sta }
] [
.B -x
] [
.B -f 
alt_.newsrc ] [
.B -n 
newsgrp ...]
.SH DESCRIPTION
.I Newscnt
provides a count of unread network news.  By default, the user's .newsrc 
file is examined to determine a list of newsgroups.  These newsgroups
are then matched against the list of articles that the user has read
and a count of available unread news articles is determined.  The
program writes to stdout either "No news." if there are no unread news
articles, or "\f2nnn\fP news articles." to indicate the number of
unread articles.  Options
are provided for altering the format in which the count(s) are
returned and the inputs the program works from.
.P
The following options are supported:
.TP .5i
\f3-\fP{\f3sta\fP}
These three options, only one of which may be specified at a time,
affect the output format of the program.
.RS .5i
.TP .5i
\f3s\fP
The \f2silent\fP option -- nothing is written to stdout.  Only the
program's normal return codes are provided, e.g. a \f31\fP if there is
no unread news, a \f30\fP if there is unread news, or a \f3-1\fP if
there was an error in the processing.
.TP .5i
\f3t\fP
The \f2terse\fP option -- only the total number of unread news
articles (including zero if there are no unread news articles) is
written to stdout.  No other text is written.
.TP .5i
\f3a\fP
The \f2all\fP option -- in addition to a report of the total number of
unread news articles, the program writes a line of the form
"\f2newsgroup\fP: \f2nnn\fP articles" for each newsgroup having one or
more unread news articles.
.RE
.TP .5i
\f3-x\fP
This flag causes the program to ignore the articles that the user has
already read in each newsgroup and report the total number of articles
available in the newsgroup.  The effect is similar to the \f3-x\fP
flag on most news reading programs.
.TP .5i
\f3-f \f2alt_.newsrc\fP
When this option is specified, the file \f2alt_.newsrc\fP is used
instead of the user's \f2$HOME/.newsrc\fP file.
.TP .5i
\f3-n \f2newsgrps\fP ...
When this option is specified, the \f2newsgrps\fP specified on the
command line are reported on.  By default, the program searches
through the specified or default .newsrc file for a line that begins
with the word \f2options\fP.  This \f2options\fP line is parsed for the
list of \f2newsgrps\fP following a \f3-n\fP argument.  Any
\f2newsgrp\fP, either from the command line or from the .newsrc file,
prefaced with an exclamation point will be specifically excluded from
the computation.  This is useful for excluding "embedded" newsgroups.
(\f3NOTE\fP:  A \f2newsgrp\fP is taken as the "prefix" to a set of
newsgroups and all newsgroups with that prefix are automatically
included in the count.)
.SH FILES
/usr/lib/news/active
.br
$HOME/.newsrc
.SH CAVEATS
This program makes use of the /usr/lib/news/active file to determine
the available news items and not the actual news directory's contents.
Consequently, its answers may be off slightly if the active file does not
accurately track the available news articles.  If you are told
you have unusually large amounts of unread news, use the -a option to
pinpoint the newsgroup(s) with unusual counts
and then check to see if there are unexpired
articles causing an unusually large "range" in the active file.
.P
The .newsrc format is interpreted according to the author's understanding of 
that file's format.  Variations in how this file is interpreted may exist.
.SH AUTHOR
.nf
Glen A. Taylor
AT&T (Consumer Products Divsion)
May 1986
.fi
