.TH ERGOTIME 1  "18 June 1984"
.SH NAME
ergotime \- set time-of-day on ERGO-201 or other terminals
.SH SYNOPSIS
ergotime [-e{seq}] [time]
.SH DESCRIPTION
.I Ergotime 
sets the time-of-day on terminals with a real-time display, most
notably the "ERGO-201" by 
.I microterm.
The time is gotten from the system with 
.I gettimeofday(2)
or from the optional command argument, and sent to the terminal in 
a special form.  The time itself must be preceded by a "load time"
escape sequence.  The sequence defaults to '^[t' and can be changed 
with the -e parameter.  
.PP
The time parameter, if present, must be exactly 4 digits long, and
express a military (24 hr.) time of day.  Times that do not fit this
criteria are ignored.  
.PP
The default sequence is escape-t, this is not anybody's standard, but
the ERGO-201 will not accept ESC-blank (925) as a customization.
.SH "SEE ALSO"
gettimeofday(2), ctime(3), termcap(5)
.br
Microterm inc, "ERGO-201 OPERATING MANUAL", Microterm Inc, St. Louis.
.SH AUTHOR
Neal Ziring at Wash U. in St. Louis.
.SH BUGS
.PP
Does not check termcap to see what kind of terminal is being
used.
.PP
Accuracy is limited to minutes by the terminal itself (only loads
four digits).

