.TH PROGNAME 1 01/29/85
.UC 4
.SH NAME
unshar \- Unpackage one or more shell archive files
.SH SYNOPSIS
unshar [
.I files
]
.SH DESCRIPTION
.PP
.I Unshar
unpackages shell archive files by first removing any leading mail
headers or other junk and then piping the rest of the file through
the
.I sh
command.  Trailing junk is not removed and may caused anomalous
behavior unless the shell archive file has an
.I
exit
command at the end.
.PP
.I Unshar
understands phrases like
.I cut here
and also knows about shell command characters (#) and (:) and
the Unix commands
.I echo,
.I cat,
and
.I sed.
.PP
The 
.I unshar
command is not perfect, but it will correctly unpackage output from
most shell archive generators.
.SH OPTIONS
.PP
None.
.SH SEE ALSO
.PP
packmail(1)
.SH BUGS
None known.
.SH HISTORY
.TP
29-Jan-85  Michael Mauldin (mlm) at CMU
Created.
