.TH UUSH 1-uucpsup
.SH NAME
uush \- remote shell via uucp (uucp shell)
.SH SYNOPSIS
.B uush [uush_opts] [shell_opts] [command_file] [command_args]
.B uush [uush_opts] [shell_opts] [-c remote_command] [command_args]
.SH DESCRIPTION
.B Uush
is the front end processor to a UUCP-shell on some
remotely connected site.
.B Uush
has three types of options:
.nf	
      1) 'uush' options,
      2) remote '/bin/sh' options,
      3) command file options.
.fi
In the first set, options and arguments must appear next
to each other with no space. For example, 'uush -Uusername' and not
\'uush -U username'. Valid 
.B Uush
options are listed below:
.nf
      -Ssystem         Run on 'system'
      -Uuser           Run on 'system' as 'user'
      -Ppath:path...   Run with PATH=path:path...
      -Xxqtdir         Run in 'xqtdir'
      -Mmailbox        Mail output to relative 'mailbox'
      -Fumask          Run with umask set to 'umask'
      -V               set verbose options
.fi
Once a '-c' or non-minus argument is seen on the command line, then
.B Uush
options are no longer scaned for; the rest of the options
are assumed to be intended for /bin/sh or for the commandfile.
.br
.sp
.B Uush
also scans for an explite '-c' option which indicates that
the next argument is a remote command or remote command-file. If
no '-c' option is present, then the command-file name is taken
to be the name of a local bourne-shell script; and if no command-file
name is present, then the commands are taken from standard input.
.br
.sp
.B Uush
will then create a data file and ship if off to the requested
host via uux(1) where the program 
.B uush.uu
will unpack the data and
execute the commands. A mail message will be generated on the remote
system containing a header section followed by the standard output
and standard error of the commands.
.br
.sp
If the file
.B $HOME/.uushrc
is present on the system where the
.B Uush
command was issued, then it is assumed to be a bourne
shell script that can help setup default parameters for each host.
For example:
.nf
	case $R_SYS in
		test1)	R_MBOX=foo@bar;;
		*)	R_SYS=aus3b5
			R_MBOX=`uname -n`!$USER;;
	esac
.fi
When
.B Uush
profiles
.B $HOME/.uushrc,
the variable
.B R_SYS
is set from the
.B -Ssystem
option. If no
.B -Ssystem
option is given, the the above example would
set it to "aus3b5" and set the default remote mail-box as well.
.br
.sp
Variables which may be set in
.B $HOME/.uushrc
include:
.nf
      
                UUSH
      VARIABLE  OPTN DESCRIPTION
      R_UMASK	-F   Remote file creation mask. 
      R_USER	-U   Remote user name (obsolute).
      R_PATH	-P   Remote path to execute commands from.
      R_MBOX	-M   Name of the remote mailbox.
      R_XQT	-X   Remore directory to execute commands on.
      R_SYS	-S   Name of remote system
.fi      
.br
.sp
.B Uush
options always have presidence over variables set/reset in
.B $HOME/.uushrc
because the options are scaned before and after
the reading of this file.
.SH EXAMPLES
.nf
      egg mkdir . /tmp | uush -Saussjo -F0 -X/tmp
            executes commands generated by 'egg' on !aussjo,
            in /tmp directory, with umask set to 0000.

      uush -V -Saussjo file.sh
            reads local file.sh and runs on !aussjo.

      uush -V -Saussjo -c 'file.sh'
            runs the command 'sh -c file.sh' on !aussjo
.fi
.SH FILES
$HOME/.uushrc 	-- bourne shell init script
system!/usr/local/uubin/uush.uu -- remotely executed shell script
.SH BUGS
This program breaks all of the security rules. It might be wise
to make a front end set-uid program that is executed instead of
"uush.uu". Eg:  uush -> uux -> set_uid -> sh uush.uu. For this reason,
it is recommended that it be installed only on internal sites.
.br
The
.B -c
option doesn't work as expected (will be fixed later), only the
first option after '-c' is recognized remotely. Eg: "uush -c echo 1 2 3"
really becomes "uush -c echo". It is better to simply "echo echo 1 2 3 | uush".

