.TH AT 1 "December 15, 1986"
.UC 4
.SH NAME
display \- repeat a command through curses for minimal update
.SH SYNOPSIS
display [-<delay>] <command>
.SH DESCRIPTION
.I Display
repeatedly executes a shell command, sending the output through
.IR curses (3X)
to cause only the portions of the output which have changed from
one execution to the next to be redrawn.
.I command
must be quoted if it contains blanks or other special characters.
.I delay
is the number of seconds to suspend between updates; the default is 5.
.SH EXAMPLES
.sp 1
display -10 "date; echo ' '; uusnap; echo ' '; mailq"
.PP
This provides a dynamic 'UUCP status watch' for BSD systems.  If anyone
figures out a non-nightmarish csh alias for something with both kinds of
quotes in it, please send mail.
.fi
.SH "SEE ALSO"
popen(3),
curses(3X),
sh(1)
.SH DIAGNOSTICS
Fairly informative usage message if you run it with a bad command line.
.SH BUGS
.IR Popen (3)
always executes the command through
.IR sh (1)
.SH AUTHOR
.nf
Paul Vixie
{ptsfa,qantel,crash,winfree}!vixie!paul
