.tr ~
.de Na
.br
\\$1
..
.de Ex
.IP "" 5
.B \\$1 \\$2 \$3 \\$4 \\$5 \\$6 \\$7 \\$8 \\$9
.P
..
.de Es
.IP "\\$1" 5
.B \\$2 \\$3 \\$4 \\$5 \\$6 \\$7 \\$8 \\$9 
..
.de Ee
.br
.B \\$1 \\$2 \\$3 \\$4 \\$5 \\$6 \\$7 \\$8 \\$9 
..
.de Ez
.P
..
.tr ~
.TH reverse lman "Pics System Test"
.SH NAME
reverse - c program to reverse files.
.SH SYNOPSIS
.Na "reverse files"
.SH DESCRIPTION
.B reverse
is a filter to reverse files.
It is used in a manner similar to cat (see cat(1)).
.B reverse
will process each of its arguments in turn, reading the files backwards.
If any file has 
.B -
for its name, 
.B reverse
will create a temporary file, read standard input into that temporary file
and then reverse the temporary file.
.SH EXAMPLES
.Es "To reverse input from terminal" reverse -
.Ez
.Es "To create a confusing listing" ps -ef |reverse -
.Ez
.Es  "To reverse the date" date |reverse -
.Ez
.Es "To reverse a file" who >file
.Ee reverse file
.Ez
.SH "SEE ALSO"
cat(1)
.SH AUTHOR
Kurt Gluck, SPL 1c273a x2023
