.TH SHORT L 3/6/86
.UC 4
.SH NAME
short -\ Creates a define table for compilers with short identifiers
.SH SYNOPSIS
.B short
file
.SH DESCRIPTION
.PP
.I short
goes out and looks at a piece of C code and finds all identifiers that
are longer then 8 characters long.  Then it will create a header
file that will use the #define command to re-define all the
identifers to short names. The output file is "ident.h".  You
can load this into the code or use the #include command.
.SH FILES
 ident
 idents.h
.SH AUTHOR
Josh Siegel
.SH BUGS
Who me?  write something with a bug?

It has not been tested on any machine with short identifiers. (Thats a bug?)
