.TH GENEAL LOCAL 8/28/85
.SH NAME
geneal \- genealogy program
.SH SYNOPSIS
.B Geneal
[ option ] ...
[ file ] 
.SH DESCRIPTION
.I Geneal
is a program to read a database of family relations in the named
.I file
and print the information out in various formats.  
.PP
If no
.I file
argument is present, the default file,
.I genealogy.dat
, is read.
.PP
It deals with
families and individuals, each identified by a unique integer.
The database contains information such as 
.I birth
, 
.I death 
and
.I marriage 
dates and places (if you know them!), relations between
people (i.e. what children belong to X, are you my mother),
and miscellaneous information of general interest.
The program can read the information for a specified individual
and output it in a specified format.  At the moment there are two
formats (only one of which is "real"): the tree, and the family
page.  The tree format is only a tiny bit implemented, so it's
not very useful yet.  The family page gives information about
an entire family (one generation), i.e. parents, children, and
childrens's spouses.  More formats can easily be added (and will
be in the future!).

Geneal expects one argument on the command line, which is the index
number of the person or family to center the data search/output on.
.PP
The options available are:
.TP "w'\f3\-F\f1name 'u"
.BI \-f   
produce a family information page
.TP
.BI \-h   
give this help message (try this in case this man page is wrong!)
.TP
.BI \-i   
produce information about an individual
.TP
.BI \-s   
use a short form of output
.TP
.BI \-t   
produce a tree (not implemented very far!)
.TP
.BI \-D   
debug data routines
.TP
.BI \-F file   
use the specified file as datafile
.TP
.BI \-I   
debug index routines
.TP
.BI \-N   
output internal index numbers with all names
.PP
If no format switches (-f, -i, -t) are given, browse mode is entered.
The two debug switches (-D and -I) will probably not be useful to you
unless you are familiar with the dataman and index routines which they
apply to.

.SH EXAMPLE
Individuals or families are specified by index number.  Thus the
command to output the family data page for a particular family
would be
.IP
.nf
    geneal -f 1025
.fi
where 1025 is the index number for that family.
.SH NOTES
There is some flexibility in the data file as to what numbers you
use as index numbers.  The authors have adopted the convention that individuals
are numbered starting at 1 and families starting at 1000 (when I get
1000 individuals, I will start the next group at 10000).  You may
want to use different conventions, e.g. odd numbers for males, even
for females; families starting at a higher number; or whatever.
.SH FILES
.nf
   genealogy.dat 	The database file. This is a sample 
			file for you to use as a template
			for creating your own data file.

   family.1003 		Sample output file produced by 
			"geneal -f 1003".

   pgmr.doc 		Programmer's documentation. Gives 
			more details about some of the source 
			files. Read this if you need to look 
			for bugs.
.fi
.SH AUTHOR
Jim McBeath (original author)
.br
Terry L. Ridder (ported geneal to Version 7 and SYS V)
