.TH EXTRACT 1R
.SH NAME
extract \- extract troff definitions from macro packages
.SH SYNOPSIS
.B extract 
[
.I options
]
.B macro_name
.SH DESCRIPTION
.I extract
is intended to be useful for writers and testers of troff macros.
It attempts to find the definition[s] of the macros given as arguments in
the appropriate places -- /usr/lib/tmac/tmac.s is the default file,
containing the ms macros.
.PP
Options are -f\c
.I file
which looks in the named file, and -m\fIpackage\fP, which behaves as the
troff -m flag.
.SH EXAMPLE
.PP
extract -man PP
.br
\&	.de SH
.br
\&	.}X 0
.br
\&	.nr )E 2
.br
\&	\e&\e\e$1 \e|\e\e$2 \e|\e\e$3 \e|\e\e$4 \e|\e\e$5 \e|\e\e$6
.br
\&	..
.br
.sp
.SH "BUGS"
Doesn't cope with input like
.br
.ft 3
\&.de XXy
.ft
.br
which is legal
.I troff
input but is better written as
.br
.ft 3
\&.de XX y
.ft
.br
.SH "SEE ALSO"
troff(1), soelim(1), man(7), ms(7)
