.TH WHICH 1 LOCAL
.SH NAME
which \- show full path of commands
.SH SYNOPSIS
.B which
progname ...
.SH DESCRIPTION
.I Which
takes a series of program names, and prints
out the full pathname of the program that the shell would call to
execute it.
It does this by simulating the shells searching of the
.B $PATH
environment variable.
.SH "SEE ALSO"
The exec(2,3) family.
