.TH CHECKMAIL "1" "February 1986" 
.SH NAME
checkmail \- check for the existence of email 
.SH USAGE
\fIcheckmail\fB [-b [-n\fIn\fB] [-s\fIn\fB] ] [-h] [-l\fIname\fB]
.SH OPTIONS
The following options are recognized:
.de OP\" option-letter [optional value]
.TP
.BI \\$1 \\$2
..
.OP -b 
Background mode: checkmail is placed in background for continuous
email checking.
.OP -n  n
Checkmail is invoked with a nice value of \fIn\fR.  The default
for \fIn\fR is 4.
.OP -s  n 
Checkmail is invoked with a sleep interval of \fIn\fR seconds.  
The default for \fIn\fR is 300 seconds.
.OP -l name 
The mailbox of an alternate login \fIname\fR will be checked.
The default is the current user's logname.
.OP -h 
A simple help/usage screen is displayed
.SH DESCRIPTION
.PP
.I checkmail
checks for the arrival of mail.  
By default 
the current user's mailbox is scanned for the existence of \fIany\fR mail. 
Options allow for the checking of an alternate user's mailbox and/or
continuously checking in the background for new email.
.SH SEE ALSO
getopt(1)
.SH DIAGNOSTICS
.I Checkmail
prints an error message on \fIstderr\fR if it can not get the current
\fIlogname\fR or change to the appropriate \fImail\fR directory.
.SH EXAMPLE
.nf
Continuously check \fIjohnd\fR's mailbox every 5 minutes:
	checkmail -l johnd -b -s 600 
.fi
.SH HISTORY
Written by Marc Ries.  Based upon a program of similar name presented 
by Brian Kernighan and Rob Pike in "The UNIX Programming Environment".
