.TH TTY 1 "HFVR"
.SH NAME
.\" name \- one-line description for in permuted index
tty \- to print full tty name of user
.SH SYNOPSIS
.\" bnf on command syntax
tty [user]
.SH DESCRIPTION
.\" semantics
Tty will print the full tty device name of the user given as
argument. If no argument is given then tty prints the tty name of
the person running the tool (just like tty(1)).
If the user is not logged in then nothing is printed and return
code is 1. If found the return code is 0.
.SH EXAMPLES
.nf
tty          prints /dev/tty*** for $LOGNAME
tty hvrietsc prints /dev/tty*** for user hvrietsc
,fi
