.TH SXTALLOC 7 "Edinburgh Univ, June 6 1986"
.SH NAME
sxtalloc - allocate/deallocate sxt channels
.SH SYNOPSIS
.B /usr/lib/ssh/sxtalloc
.br
.B /usr/lib/ssh/sxtalloc \fIttyname status\fx
.SH DESCRIPTION
When called with no parameters,
.I sxtalloc
finds a non-busy sxt channel-zero in /dev/sxt
and chowns all its subchannels to the real user-id of the caller
so that the sxt is then available for use by that user.
It replaces the users original terminal name in the
.I utmp
file with the new sxt device.
It prints the name of the original terminal on the standard output.
.PP
If called with two parameters, it attempts to undo the damage caused by
allocating the device. It replaces the sxt name in the
.I utmp
file with the
.I ttyname
parameter, and exits with exit-status
.IR status .
Checks are made that you are entitled to have
.I ttyname
as your terminal.
.PP
The use of
.I sxtalloc
may be restricted to certain usernames by creating files
.I sxt.allow
or
.I sxt.deny
in the directory
.IR /usr/lib/ssh .
If an
.I allow
file exists, then only those people whose name occurs in this file
are permitted to allocate sxt channels;
if a
.I deny
file exists, then everyone execept the people named in this file
may allocate sxt's.
If neither exist, then no restrictions on use are in force.
.SH "STATUS RETURNS"
When allocating an sxt device, it returns status of 0 if it succeeds,
otherwise 1.
When deallocating, it exits with the given exit-status, unless it fails
for some reason (in which case it exits with status 1).
.SH "SEE ALSO"
ssh(1), sxt(7), utmp(4).
.SH "FILES"
/usr/lib/ssh/sxtalloc - binary
.br
/dev/sxt/??? - sxt devices
.br
/etc/utmp - utmp file
.br
/usr/lib/ssh/sxt.allow, /usr/lib/ssh/sxt.deny
.SH BUGS
It has to be set-user-id root.
.SH AUTHOR
Simon Brown
