.TH MACLASER local "31 March 1987"
.UC 4
.SH NAME
maclaser - Spool Macintosh PostScript files to the LaserWriter printers
.SH SYNOPSIS
.B maclaser
[
.BI \-P<printer>
]
file
.SH DESCRIPTION
.I Maclaser
is a program which spools Macintosh-generated PostScript files to any of the
LaserWriters.  It defines function definitions that the
Macintosh PostScript file uses.
.PP
The -P option is used to specify the output device.  If the option is
omitted, the default LaserWriter (-Plw) is used.
.PP
For MacPaint pictures, PostScript files may be generated using paintps
(local) or using the method described below.
.PP
For other output, you must (currently) use the procedure described below
to get the Macintosh to create the PostScript file.
.SH GENERATING\ MACINTOSH\ POSTSCRIPT\ FILES
This section describes how to generate PostScript files on the Macintosh
for uploading and eventual printing.  Most programs need at least 200K of
memory to produce PostScript.  (In other words, 128K Mac owners can give up
now.)
.PP
Make sure the LaserWriter printer driver file is installed on your system
disk.  You may use the "Chooser" desk accessory to select the
LaserWriter driver.  You may have to turn on AppleTalk first.  "Chooser" will
give you instructions.
.PP
Use the Page Setup menu item to specify whether you want the
LaserWriter to substitute its built-in fonts for the Macintosh fonts,
whether you want smoothing, and so forth.
.PP
Open the document with the required application and choose the "Print..."
menu item.  In most applications (such as MacWrite) a dialog box will
appear.  Answer the questions and click OK.  After you click OK, hold down
the command key (cloverleaf) and hold down the "f" key.  When a box
appears saying "Creating PostScript File", you may
release the cmd-F keys.  If instead a box appears saying "Looking for
LaserWriter", you did not press cmd-F at the right time.
.PP
NOTE:  MacPaint is slightly different.  "Print Draft" prints without
smoothing, and "Print Final" prints with smoothing.  Also, no dialog
box appears when you choose "Print ..", so hold down cmd-F right after
you choose one of the print commands.
.PP
A file called PostScript will appear on your disk.  This file is a plain text
file readable by MacWrite and most other editors and word processors.
This file is often extremely large (> 100K), so you might make sure you
have lots of room on the disk before creating it.
You will not be warned if you run out of space.
.PP
Now upload the PostScript file to your favorite UNIX machine.  Several file
transfer programs exist.  For instance,
using MacTerminal connected to a UNIX machine, you can give the UNIX command
.PP
% macget -u
.PP
Then choose "Send File" in MacTerminal and select PostScript.  This will
leave a file in your current UNIX directory called "PostScript.text".
.PP
Another common file transfer program is Kermit.  While running MacKermit,
issue the UNIX command
.PP
% kermit -x
.PP
Then choose "Send File" in MacKermit and select PostScript.  When it finishes,
choose "Finish".  This should leave a file in your current UNIX directory
called "postscript".
.PP
Now you may finally give UNIX the command:
.PP
% maclaser PostScript.text
.PP
to print the file "PostScript.text" on the default LaserWriter.
.SH COMPATIBILITY
I try to support as many versions of the Macintosh LaserWriter driver as
possible.  The current version of maclaser supports version 1.1 (distributed
with Finder 4.1), version 3.1 (with Finder 5.3), and version 3.3 (with Finder
5.4).
.SH BUGS
Certain characters in the Zapf Dingbats font don't print correctly when using
the 3.1 LaserWriter driver.  I probably won't ever fix this bug since it works
in the newer version of the driver.  (And we don't use Dingbats much anyway.)
.SH FILES
/usr/local/lib/allfonts/postscript/laser-prep-12.pro
.br
	LaserPrep version 12, for LaserWriter version 1.1
.PP
/usr/local/lib/allfonts/postscript/laser-prep-40.pro
.br
	LaserPrep version 40, for LaserWriter version 3.1
.PP
/usr/local/lib/allfonts/postscript/laser-prep-49.pro
.br
	LaserPrep version 49, for LaserWriter version 3.3
.SH SEE\ ALSO
paintps(local), macget(local), kermit(1C), lpr(1), printers(4L)
