.TH PAINTPS local "31 March 1987"
.UC 4
.SH NAME
paintps - Convert MacPaint document into PostScript
.SH SYNOPSIS
.B paintps
file
.br
.B paintps
[
.B \-d
] [
.BI \-#<n>
] [
.BI \-P<printer>
] file
.SH DESCRIPTION
.I Paintps
translates a MacPaint document, uploaded from a Macintosh,
into the PostScript language.  It can also spool output to maclaser (local)
for printing on a LaserWriter or other PostScript device.
.PP
If the output of paintps hasn't been redirected or piped, then paintps
automatically spools the output to the printer specified with the -P option.
.PP
Note that the resulting PostScript file requires certain function
definitions that aren't normally present on the LaserWriter.  Therefore,
the output of paintps must eventually be printed using "maclaser" instead of,
for example, "lpr -Plw".
.PP
The order of command line arguments is not important, except that the options
must precede the filename.  The available command line options are:
.TP
.B -d
Specifies Draft Mode.  This turns off the smoothing function for graphics.
This option is of dubious usefulness since the smoothing overhead is small.
.TP
.BI -#<n>
Specifies the number (n) of copies to be printed.
.TP
.BI -P<printer>
Specifies the printer to be used as the output device.  This option is ignored
if the output of paintps has been redirected to a file or piped to another
process.
.SH UPLOADING\ MACPAINT\ FILES\ TO\ UNIX
There are several ways to upload MacPaint files to a UNIX machine.
For example, you may use the command
.PP
% macget -d
.PP
to upload MacPaint files from the Macintosh to UNIX with MacTerminal.  See
macget(local) for more information.  Other file transfer programs are also
available, such as Kermit.
.SH BUGS
This version of paintps generates output intended to be very similar to the
output that would be created by the version 1.1 Macintosh LaserWriter driver.
This
driver is now outdated, as far as Macintosh system software is concerned.
Maclaser must support the version 1.1 driver for paintps to work.
.SH DIAGNOSTICS
If the LaserWriter produces an error page saying "/md undefined", this
probably means you spooled the output with lpr instead of maclaser.
.SH AUTHOR
Brian H. Powell, The University of Texas at Austin
.SH SEE\ ALSO
maclaser(local), macget(local), kermit(1C)
