.TH PATH 1 "25 March 1987"
.UC 4
.SH NAME
path \- find the best path to a UUCP site
.SH SYNOPSIS
.B path
site [site...]
.PP
.B path
-s pattern
.PP
.B path
-h <mail-header
.PP
.B path
-r path [path...]
.SH DESCRIPTION
This is a handy program to have when you're trying to find a path to a
machine, when all you have is its name. Also nice for finding cheap paths
to a 
.I very
remote machine, like
.I ihnp4.
.PP
.I path
understands domains, and will generate paths to the correct domain gateway
if no more direct path was found.
.I path
also understands the special case of the
.I .UUCP
domain, and will try to route the path directly to the destination site
before it tries for the gateway.
.TP 5
.B  \-s
This searches for paths to all sites matching the regular expression
.I pattern.
.TP 5
.B  \-r
Takes the full path to a user at another site, and finds a shorter or
cheaper path to it. If the destination site is unknown,
.I path
tries to find a path to the previous site on the list, and so on, until
it reaches the beginning of the list. If it still hasn't found a correct
path, it will assume the one given is correct and return that.
.TP 5
.B  \-h
Takes a standard mail or news header from standard input, and replaces
each path in a
.B To:
line with a shorter one, as in the
.I \-r
option.
This allows
.I Rnmail
(with a little modification) to automatically find shorter and
more reliable sites through
which to return mail than the ones given by default.
.TP 5
.I  site
Any valid UUCP site name.
.SH AUTHOR
Bruce Holloway (holloway@drivax.UUCP)
