#!/bin/sh
MAKEFILE=Makefile

case "$1" in
"")
	echo "Usage: $0 <machinetype>"
	exit 1
	;;
M68)
	MAKEFILE=M68
	;;
esac

if [ ! -f make.base.$1 ]
then
	echo No machine type $1 supported.
	exit 1
fi

cat make.base.$1 make.base > $MAKEFILE
