.TH SAC LOCALTOOLS "August 21 1986"
.UC 4
.SH NAME
sac \- login accounting
.SH SYNOPSIS
.B sac
[
.B \-w
wtmp ] [
.B \-p
] [
.B \-d
] [
.B \-n
] [ people ] ...
.SH DESCRIPTION
.I Sac
produces a printout giving
connect time
for each user who has logged in and out
during the life of the current
.I wtmp
file.
Only logged-out processes are accounted.
A total is also produced.
.B \-w
is used to specify an alternate
.IR wtmp ""
file.
.B \-p
prints individual totals; without this option,
only totals are printed.
.B \-n
will attempt to recreate the wtmp file, so that all logged-out processes
are discarded.
Any
.I people
will limit the
printout to only the specified login names.
If no
.IR wtmp ""
file is given,
.I /usr/adm/wtmp
is used.
.PP
The accounting file
.I /usr/adm/wtmp
is maintained by
.I init
and
.I login.
Neither of these programs creates the file,
so if it does not exist
no connect-time accounting is done.
To start accounting, it should be created with length 0.
On the other hand if the file is left undisturbed it will
grow without bound, so periodically any information
desired should be collected and the file truncated
using the '-n' option.
.PP
Sac's format is very similar to that of ac(8).
.PP
.SH AUTHOR
Grenville Whelan, (gdw@uk.co.ssl-macc).
.SH BUGS
None, (I hope).
.SH FILES
/usr/adm/wtmp
.SH "SEE ALSO"
init(8), sa(8), login(1), utmp(5), ac(8).
