.TH NUMBER 6 "August 11, 1987"
.AT 3
.SH NAME
number \- convert Arabic numerals to natural language
.SH SYNOPSIS
.B number
.I "[language]"
.SH DESCRIPTION
.I Number
copies the standard input to the standard output,
changing each decimal number to a fully spelled out version.
It works with a lot of languages, among which are English,
French, Chinese, Vietnamese...  If it is given a language
that it doesn't know, it prints out the list of languages
that it does know.  Some languages are listed under more
than one name, such as Gaellic and Irish.
.SH BUGS
It currently doesn't handle very large numbers.  It
could be made to do so, and maybe it will someday.
.SH AUTHOR
Scott Deerwester
