
.TH search 1 "HFVR"
.SH NAME
.\" name \- one-line description for in permuted index
search \- a fast(er than grep/fgrep) searcher for string
.SH SYNOPSIS
.\" bnf on command syntax
search <string> <file>*
.SH DESCRIPTION
.\" semantics
Search will search <string> in <file>*. If no file is given then stdin
is assumed. Lines which contain the <string> as displayed, proceeded by the
filename if more than file is given.
.sp
The return code is TRUE if something was found, FALSE otherwise.
.SH EXAMPLES
search hello                 # to read from stdin
.br
search hello /etc/password   # to search /etc/profile
.SH SEE ALSO
fgrep(1)
