.TH ZONK 1 "U of W"
.SH NAME
zonk \- Kill all processes owned by a user fast
.SH SYNOPSIS
.nf
.B
zonk [ \-sig ] name
.B
zonk [ \-sig ] \-u uid
.fi
.SH DESCRIPTION
.I Zonk
sends a signal to all processes owned by
user \fIname\fP.
The signal sent is SIGKILL (kill utterly); this can be changed by
supplying the desired signal in the style of
.IR kill (1).
In the second form, the signal is sent
to all processes with the given effective \fIuid\fP.
If no arguments are given, the invoking user is zonked.
.PP
The purpose of this process is to help confused operating system students
who leave all kinds of processes running get rid quickly of ALL processes
which they have anything to do with; and to do this while the system
is incredibly slow.
Also to help consultants get rid of confused users who are clogging up
the system.
.SH "SEE ALSO"
kill(1), zonk(2).
.SH BUGS
This gets rid of everything.  Perhaps it should only do it for things
on a given terminal, or not the controlling shell.
