.\" @(#)sudo.8	1.4 (SUNYAB CS) 12/14/85
.\" This document uses the troff(1) -man macros
.TH SUDO 8 "14 December 1985" "" "Local UNIX Programmer's Manual"
.SH NAME
sudo \- do a command as the superuser
.SH SYNOPSIS
.B sudo
[
command
]
.SH DESCRIPTION
.I Sudo
looks for your username and your
.I sudo
permission in the file /usr/local/adm/sudoers.
If you are permitted, 
.I sudo
executes
.I command
as the superuser.
.I Sudo
with no command arguments just shows your 
.I sudo
permission.
.PP
Individual entries in /usr/local/adm/sudoers are a username
followed by the user's 
.I sudo
permission, \-- either: "all"; a list of permitted commands; an
enviornment PATH variable; or a PATH followed by a list
of permitted commands.
.PP
For readability, permission entries may span several lines
\-- each line following the first line should start with
white space.  Comment lines are blank lines or lines
starting with a "#".
.PP
An example sudoers file is:
.PP
.br
# comment
.br
root all
.br
user1 all
.br
user2 command1 command2
.br
user3 PATH=/workingdir1:/workingdir2
.br
user4 PATH=/workingdir1 command1 command2 command3
.br
user5 PATH=/workingdir1:/workingdir2
.br
	command1
.br
	command2
.PP
.SH NOTES
A working directory for a 
.I sudo
enviornment PATH could be /usr/local/restrict-bin.
.PP
.I Sudo csh
can be used as a substitute for logging in as root.
.PP
When a user is restricted to commands or a PATH,
if any of those commands have shell escape,
the user has access to 
.I sudo
"all".
.SH FILES
/usr/local/adm/sudoers \- list of superusers
.br
/usr/local/adm/sudo.log \- record of 
.I sudo
usage
.br
/usr/local/adm/sudo.log.failures \- record of attempts to use 
.I sudo
by non-superusers
.SH SEE ALSO
su(1)
.SH AUTHORS
Phil Betchel
.br
Cliff Spencer
.br
Gretchen Phillips
.br
John LoVerso
.br
Don Gworek
