.TH FTIMES 1
.SH NAME
ftimes \- display access, change and modify times of a file
newer, older \- compare access, change and modify times of a file
.SH SYNOPSIS
.B ftimes
[
\fB\-acmvf\fIformat\fR
] [\fB+\fIformat\fR] file
.br
.B newer|older
[
\fB\-acmntvwf\fIformat\fR
] [\fB+\fIformat\fR] file1 file2
.SH DESCRIPTION
.I Ftimes
displays the access, change and modify times of a file in seconds
past the epoch (1 January 1970).
.PP
.I Newer|older
exit with
.I true
status if
.B "file1 relation file2"
is true.
.PP
The format of the time displayed may be controlled by either the \fB-f\fP
or the \fB+\fP options.
The display format is similar to that of the first argument of the \fIprintf\fP
(3S) subroutine or the \fIdate\fP(1) command.
All output fields are of fixed size and are zero padded if necessary.
.SH COMMAND LINE OPTIONS
.TP 8
.B \-a,c,m
Display the access, change or modify times of the file.
If none of the above are given, the default is modify time.
.TP
.B \-v
Display in human readable format.
.TP
.B "\-f, +"
Display the selected times in the format which follows this option.
All output fields are of fixed size (zero padded if necessary).
Each field descriptor is preceded by ``%'' and will be replaced
in the output by its corresponding value.
A single ``%'' is encoded by ``%%''.
All other characters are copied to the output without change.
The string is always terminated with a newline.
.sp
Field descriptors:
.nf
       \fBn\fR     insert a new-line character
       \fBt\fR     insert a tab character
       \fBm\fR     month of year \- 01 to 12
       \fBd\fR     day of month \- 01 to 31
       \fBy\fR     last 2 digits of year \- 00 to 99
       \fBD\fR     date as in mm/dd/yy
       \fBH\fR     hour \- 00 to 23
       \fBM\fR     minute \- 00 to 59
       \fBS\fR     second \- 00 to 59
       \fBT\fR     time as HH:MM:SS
       \fBj\fR     day of year \- 001 to 366
       \fBw\fR     day of week \- Sunday = 0
       \fBa\fR     abbreviated weekday \- Sun to Sat
       \fBh\fR     abbreviated month \- Jan to Dec
.fi
.sp
The default field descriptor is:
.nf
       +%a %h %d %H:%M:%S 19%y
.fi
.PP
The following options apply to
.I newer|older
only:
.TP
.B \-n
Display the name of the first file if the relation was true.
.TP
.B \-t
Display the times of the first file if the relation was true.
The
.B a,c,m
flags can be used to choose a subset as for
.I ftimes
and the same default applies. The first type of
time specified is used in the comparison.
.TP
.B \-w
When used with the
.B "n or t"
flags, displays the winner of the comparison regardless
of the truth value of the relation.
.SH EXAMPLES
.br
.nf
.sp 1
.in +5
	ftimes -v foo.c
.in -5
.sp 1
.fi
displays the last modify time of foo.c.
.br
.nf
.sp 1
.in +5
	newer -cnw filea fileb
.in -5
.sp 1
.fi
prinss the file that was created more recently.
.sp 1
.nf
       ftimes '+DATE:%m/%d/%y%nTIME: %H:%M:%S' file
would have generated as output:
       DATE: 08/01/76
       TIME: 14:45:05
.fi
.SH USEFUL FOR
\fBftimes\fR is usefule for adding the last modification date to
printouts of databases etc.
.SH SEE ALSO
\fIstat\fP(3), \fIdate\fP(1), \fIprintf\fP(3S)
.SH DIAGNOSTICS
An error message is displayed if a file cannot be \fIstat\fP'ed.
.SH AUTHORS
Ken Yap (University of Rochester)
.br
Rich Salz
.br
R. O. Domitz (Concurrent Computer Corporation)
