.TH REVERSI 6 17/1/79
.SH NAME
reversi \- the game of Reversi (or Othello)
.SH SYNOPSIS
/usr/games/reversi
.SH DESCRIPTION
.I Reversi
is a computerised version of the game sold in
shops as Othello. It is played on a 8x8 board with
pieces which are white on one side and black on the
other (or X and O in our case). The games starts with
the players placing
two pieces of each colour in the centre of the board.
Subsequent moves are made by adding a piece to the board so that
it brackets one or more of your opponents pieces between
itself and another of your pieces. All such bracketed
pieces are then reversed and become your pieces. The
object of the game is to have more pieces than the computer
when the board is full.
.PP
Moves are specified by board positions. Other commands
are "h" for help, "p" to print the board,
and "q" to quit; there are various parameters governing
the standard of play - the info provided when you run
the program gives full details
.SH AUTHOR
C.D.F. Miller
