.TH COBWEBS 1 "21 June 1985"
.SH NAME
cobwebs
\- check for unusually large or old mailboxes
.SH SYNOPSIS
.B cobwebs
[
-agq
]
[
-d days
]
[
-s size
]
[
username ...
]
.PP
.SH DESCRIPTION
.I Cobwebs
reports the size and age of mailboxes in /usr/spool/mail,
plus the last login of the mailbox owners.  The default
is to report mailboxes which are quite large -- larger than
the default size, 20000 bytes.
.PP
With the -d option, 
.I cobwebs 
reports mailboxes that are unusually old --
the default time is 30 days.
.I Cobwebs
also reports the mailbox status for usernames (command line
or piped).  And the program makes a general report of all
mailboxes, with the -g option.
.SH OPTIONS
.PP
-a   Sort alphabetically.  Use this option with -d or -s.
.PP
-d   Sort and/or search by age in days.  The default is
30 days, or the number argument is used.
.PP
-g   General report \-- status of all mailboxes.  By
default, this report is alphabetic.  -d or -s will allow
sort by age or size.
.PP
-q   Quiet option \-- no top banner.
.PP
-s   Sort and/or search by size in bytes.  Default is 
20000 bytes, or the number argument is used.
.SH FILES
/usr/spool/mail /etc/passwd /usr/adm/lastlog
.SH AUTHOR
Don Gworek
