.TH UW local "13 November 1985"
.UC 4
.SH NAME
uw \- unix windowing system for Macintosh
.SH SYNOPSIS
.B uw
.br
.B uwtool
[ process ] [ arg1 arg2 ...  ]
.SH DESCRIPTION
.I Uw
is a server program on unix that works with the program 
.I uw
on the Macintosh.  It creates a pseudo-terminal for each window,
giving the user up to seven `terminals' to work with.  The host
program multiplexes the output onto one RS\-232 line.
.PP
.I Uw
(on the unix system) with 
.I uw 
on the Macintosh emulate a Lear Siegler ADM-31 terminal (tset adm31), a 
Tektronix 4010, and a DEC VT52.  
Each window (on the Macintosh) has its own terminal emulation and can be 
resized at will; the program
keeps an 80x24 line display in memory for each window, but only shows the 
lower left portion possible.
.PP
.I Uwtool
can be executed from unix while running 
.I uw
to create a new window/`terminal.'  If no arguments are given, it creates
a new `terminal' running csh.  If a process is named, it will create a new
window with that process running in it, and when that process is terminated
the window will disappear.  (i.e. `uwtool vi foo' will create a new window
with vi, editing the file foo, but the window will go away when vi is exited)  
Any arguements after the process name are passed as arguements to that process.
.SH LIMITATIONS
.I Uw 
and 
.I uwtool 
are of no use on unix unless 
.I uw
is being run on the Macintosh.  
.br
If there is a stream of output in one window there will be lag in 
recognizing characters typed in another.
.SH SEE ALSO
.I uw
documentation distributed with the Macintosh program.
.SH AUTHOR
Program written by John Bruner, Lawrence Livermore Laboratories 7/85
.br
Document edited by Chris Borton, UC San Diego 11/13/85
