#!/bin/csh -f
#
# dolink - Move and link files for GR.
#
# **** Do NOT edit this file - it is automatically generated ****
#
cd GAMEDIR
foreach i ($*)
	echo Doing $i...
	mv $i HIDEDIR
	ln -s NAME $i
end
