.\"
.\" $Header: gr.8,v 1.1 86/12/17 19:31:25 mcooper Exp $
.\"
.TH GR 8 12/17/86
.ds ]W USC Computing Services
.SH NAME
gr \- Game Regulator
.SH SYNOPSIS
ln -s
.B GR
.I game	
\- To install the
.B GR
.SH DESCRIPTION
.I GR
is a program used to regulate game playing.
When invoked, 
.I GR
looks at the name it was called by (argv[0]) and assumes that is the name
of the game that is to be played.
The actual binaries are located in a ``hidden'' directory (usually
.B /usr/games/.hide).
Before an actual game is started, 
.I GR
determines several system facts.
.PP
The file
.B /usr/games/lib/gr.conf
is the configuration and control file for
the
.I GR.
It
is checked to determine: 1) the maximum load average, 2) the maximum
number of users, for game playing to be allowed, and 3)
the priority (see 
.I setpriority(2))
the game will run at.
There are also some configuration parameters that you may set.
See the manual on
.I gr.conf(5)
for details.
.PP
If the initial system conditions are satisfactory, then the requested game
is forked (via 
.I fork(2))
and  the
.I GR
goes into a loop where it sleeps for an interval and
then wakes up 
and checks the current time, number of users, the load average and
if the 
.I nogames
file is present (see below).  If any of these conditions is unsatisfactory, an
appropriate message is printed and the user is warned to end their game.
The user is given a total of three warnings (with an appropriate interval 
in-between warnings to act) before the game is actually killed.
.PP
The file
.B /usr/games/nogames
can be used to ``turn off'' game playing.  The first line of the file is
used as part of a message that is displayed to the user.
Useful for turning off game playing for one reason or another.
.SH AUTHOR
Michael A. Cooper (mcooper@oberon.USC.EDU)
.br
USC Computing Services
.SH FILES
.nf
.ta \w'/usr/games/lib/gr.conf 'u
/usr/games/lib/gr.conf	- Master configuration file
/usr/games/lib/gr.log	- Log file 
/usr/games/.hide	- Directory of ``real'' binaries
/usr/games/nogames	- Turn off game playing
.SH SEE ALSO
gr.conf(5), fork(2), kill(2), setpriority(2),
.br
Section 6 of the UNIX Programmer's Manual.
.SH DIAGNOSTICS
.IP "Game playing is not permitted on tty?? at any time."
The installer of the 
.I GR
specified tty ``??'' as a tty on which game playing is 
.I never
permitted.
.IP "The system load is greater than \fIN\fR."
The load average exceeds the limit of ``\fIN\fR'' for the requested
game.
.IP "There are more than \fIN\fR users logged in."
The number of users exceeds the limit of ``\fIN\fR'' for the requested
game.
.IP "Game playing is not permitted between \fIM\fR and \fIN\fR hours on weekdays."
The installer of the
.I GR
has specified that game playing is not permitted between the hours of
.I M
and 
.I N
during weekdays.
.IP "There are not \fIN\fR \fIspecial\fR ttys available."
The installer of the
.I GR
has specified that there must be at least 
.I N
spare 
.I special
ttys available for game playing to be permitted.
.SH BUGS
There are several ways to play games on  
.I special
ttys no matter the number of
.I special
ttys in use.
