.\"
.\" $Header: gr.conf.5,v 1.1 86/12/17 19:29:15 mcooper Exp $
.\"
.TH GR.CONF 5 12/17/86
.ds ]W USC Computing Services
.SH NAME
gr.conf \- Game Regulator control and configuration file
.SH DESCRIPTION
.I Gr.conf
is 
the configuration and control file for
.I GR.
It is split into two major parts.
The first part contains information on the system conditions on a
per game basis with a provision for a default.
These parameters may need tuning from time to time as system loading
and resources change over a long period of time.
The second part contains configuration
information for enabling/disabling certain features of
.I GR.
This part should rarely need updating.
The two parts of the control file are seperated by the word
.I CONFIGURE
appearing on a line by itself.
.PP
The syntax of the first section is as follows:
the first field is a
game name (string), 
the second field is the
maximum load average (floating point), 
the third field is the
maximum users (integer), and
the fourth and final field is the
priority (integer) the game should run at (see 
.I setpriority(2)).
Each field should be seperated
by white space (spaces and/or tabs).  Lines beginning with ``#'' are 
ignored.
If the game name (first field) is called 
.I default,
then the other three fields are taken as the default parameters for any
game not specifically listed.
The
.I default
should be the last game listed.
Thus, you may specify specific values for a
few games, with a default for all others.
.PP
The second part of the control and configuration file can be used
to set 
.I GR
options.
Each 
.I GR
option is enabled/set with a keyword followed by a set of parameters:
.IP "hidedir \fIdirectory\fR"
.I directory
is the name of the directory containing the real (hiden) game binaries.
The default is
.I /usr/games/.hide
.IP "freettys \fIttynames N\fR"
.I ttynames
is a list of ttys (last 2 characters only) that there are to be at least
.I N
avialable for game playing to be allowed.
Useful if you have a limited number of dialup modem ports or such
that you don't
want monopolized by game players.
.IP "spname \fIname\fR"
Use 
.I name
to describe what
.I freettys
are when printing a message to a user.
i.e. ``Dialup'', ``Micom'', ``Special'', etc.
.IP "badttys \fIttynames\fR"
.I ttynames
is a list of ttys (last 2 characters only) on which game playing is
.B never
permitted.
.IP "tod \fIN M\fR"
Game playing is 
.B never
permitted between the hours of
.I N
and
.I M
(24 hour clock format).
.IP "logfile \fIfile\fR"
Log information concerning game playing to
.I file.
The default is
.I /usr/games/lib/gr.log.
.IP "nogames \fIfile\fR"
If
.I file
is present, game playing is not permitted.  The first line of
the file is used to print a message to the user.
Used to turn game playing on and off.
The default is
.I /usr/games/nogames.
.PP
Below is a sample file:
.nf
.sp 1
.KS
    #
    # Game Regulator Control File
    #
    #
    # Control Section
    #                   Maximum
    # Name            Load    Users      Priority
    #\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
    rogue             4.0      8            0
    hack              4.0      8            5
    sail              4.0      8            0
    empire            4.0      8            0
    default           5.0      8            0
    
    CONFIGURE
    #
    # Configuration section
    #
    
    # should always be at least 1 of ttyd[0125] avialable
    freettys        d0d1d2d5        1
    spname          Dialup
    
    # no games ever on ttyh[01]
    badttys	        h0h1
    
    # no games from 800 hours to 1900 hours
    tod             8       19
    
    hidedir	        /usr/games/.hide
    logfile	        /usr/games/lib/gr.log
    nogames	        /usr/games/nogames
.KE
.fi
.SH AUTHOR
Michael A. Cooper (mcooper@oberon.USC.EDU)
.br
USC Computing Services
.SH FILES
/usr/games/lib/gr.conf
.SH SEE ALSO
gr(8), setpriority(2),
.br
Section 6 of the UNIX Programmer's Manual.
