.TH RDATE 1 3/24/85
.CM 1
.SH "NAME"
rdate \- get the date and time via the network
.SH "SYNOPSIS"
.B rdate
[
host ...
]
.SH "DESCRIPTION"
.B Rdate
uses TCP to retrieve the current time of another machine using
using the protocol described in RFC 868.
The time for each system is returned in
ctime(3) format. The following is an example:
.nf
.IP ""
% rdate uci mc
[uci-icsa.arpa]	Sun Mar 24 20:35:41 1985
[mit-mc.arpa]	Sun Mar 24 20:36:19 1985
.fi
.SH FILES
.nf
/etc/services	map service name to socket number
/etc/hosts	map host name to internet address
.fi
.SH HISTORY
.TP
24-Mar-85  Lee Moore at University of Rochester
Created.
