.TH CASSLABEL 1 PUBLIC 
.SH NAME
casslabel \- make cassette labels using PostScript.
.SH SYNOPSIS
.B casslabel
[1234]
.SH DESCRIPTION
.I Casslabel
prompts you for a tape title ( artist ), subtitle ( album title )
and songs ( up to 14 songs ). The "|" in the prompt means the rightmost
limit of text ( this is variable, because of the variable-width font,
Helvetica, but the "|" is the minimum amount of letters you can use.
.I Casslabel
generates device independent PostScript code.
( PostScript is a trademark of Adobe Systems, Inc. )
.I Casslabel
will print from 1 to 4 labels per page.
The following options is required.
.TP
.B \1-4.
print from 1 to 4 labels per page. There is no default.
.SH DIAGNOSTICS
Exit status is 1 if the user forgets to type the option #.
Exit status is 0 when the labeling is successful.
.SH AUTHOR
Scott Anderson (sanders3@ub.D.UMN.EDU)
.SH BUGS
none that I know of
.SH RESTRICTIONS
Currently, there is only one font possible. (Helvetica-Bold for titles,
standard Helvetica for the songs).
.br
