.TH WC 1
.SH NAME
wc \- word count
.SH SYNOPSIS
.B wc
[
.B \-lwcp
] 
[
.B \-s\c
.I pagesize
] 
[
.B \-v
] 
[ name ... ]
.SH DESCRIPTION
.PP
.I Wc
counts lines, words, characters and (optionally) pages
in the named files, or in the standard input if no name appears.
A word is a maximal string of characters delimited by spaces, tabs or newlines.
.PP
If an argument beginning with one of ``lwcp'' is present,
the specified counts (lines, words, characters, or pages)
are selected by the letters
.BR l ,
.BR w ,
.BR c ,
or
.BR p .
The default is
.B \-lwc
unless
.B \-v
is specified.
.PP
The
.B \-s
option specifies that pages are
.I pagesize
lines long instead of the defaut 66.
.PP
The
.B \-v
option asks for a verbose output format, with column headers and
including pages by default.

.SH BUGS
