.TH LB 1 "8 Nov 1985" Local
.SH NAME
lb \- lisp program beautifier
.SH SYNOPSIS
.B lb
file
.SH DESCRIPTION
.I Lb
is a shell script that
reads lisp source code from a file
and pretty-prints it to the standard output.
.SH FILES
/usr/tmp/$$ \- temporary output file
.br
/usr/ucb/lisp \- the lisp system
.SH BUGS
Comments in an object are collected and printed before it.
.PP
The script does not clean up when interrupted.
.PP
The atoms _0, _1, _2, _3, _4, and _5 are reserved for use by
.I lb.
.PP
All lisp error messages are suppressed.
Heaven help you if the input file contains syntax errors or loose NILs.
.SH AUTHOR
Col. Sicherman
