.TH GALAXY 6 MRDCH&AMNNON
.SH NAME
galaxy, okgalaxy \- A two player duel in space
.SH SYNOPSIS
.B /usr/games/galaxy
[ \-t \-a \-m user ]
.br
.B /usr/games/okgalaxy
.SH DESCRIPTION
.I Galaxy
is a game of strategy and cunning for two players.
It is played on two different CRT terminals, which must be
from among those supported by vi(1). The game displays a map of a remote
part of the universe, with two identical galaxies on each terminal.
Each player owns one galaxy. The aim of the game is to conquer the
opponent's Capital, which is the center of his galaxy.
.I Both players
give commands simultaneously, without knowing the enemy's position
and intentions.
.br
There are quite a few commands, that enable each player
to perform various tasks. Refer to the
.I Galaxy's
document for specification. The "help" command enables online
review of major parts from that document.
.PP
To play the
.I
galaxy
game, run /usr/games/galaxy.
You will be asked
who do you want to play with.  You should specify a logged in user name.
That user will receive a message asking him to accept the challenge.
If he accepts, he should run /usr/games/okgalaxy
within some reasonable time. Only then the game starts.
.PP
If you wish to practice
.I
galaxy
you can enter "-null" instead of a real user name. You then have
the ability to see and/or command the "other" side by giving the
"cp" (change player) command. You can switch back easily
by the same command.
.PP
To see the scores obtained so far, run /usr/games/galaxy with the following options:
.br
\-t     \- show the top 10 players and related statistics.
.br
\-a     \- show all games played so far.
.br
\-m     \- show all the games played by you.
.br
user    \- show all games played by 'user'.
.br
Further documentation may be found in
.I
Galaxy's
document.
.SH FILES
/usr/games/lib/galaxy           library directory.
.SH SEE ALSO
M. Chachamu and A. Horowits
.I Galactical War
.SH BUGS
Infinity is a good approximtion.
The document is lengthy and lacks humor.
.br
.I Please
mail any bugs or comments to the authors at taurus.
.SH AUTHORS
Mordechai Chachamu
.br
Amnon Horowits.
