SOURCES=src
SOURCES1=src1

all:
	@echo 'Making the galaxy game'
	@cd $(SOURCES)	;	make galaxy

	@echo 'Making the utility files'
	@cd $(SOURCES1)	;	make all

clean:
	@cd $(SOURCES)	;	make clean
	@cd $(SOURCES1)	;	make clean
