#	Makefile for Battleship
#
#	If you're compiling this under BSD Unix, use the following CC line:
#
#	cc -o battle -DBSD battle.c -lcurses -ltermcap
#
#	Otherwise, just leave it as it is.
#
battle: battle.c
	cc -o battle battle.c -lcurses

