.TH REP 1 local 
.SH NAME
rep - repeatedly execute a command
.SH SYNOPSIS
rep [-n] command
.SH DESCRIPTION
.I Rep
repeatedly executes a command and prints out the
output in the same place each time.  (It uses
cursor optimization routines to only update chars
that have changed.)
.PP
The -n option specifies the number of seconds between
repetitions.
.SH EXAMPLES
.B rep ps -ef
.PP
prints out a display of system activity.
.PP
.B rep -1 date
.PP
puts a digital clock on the screen.
.SH "SEE ALSO"
.SH BUGS
