.TH LC 1 UW
.SH NAME
lc \- list directory and file names in columns
.SH SYNOPSIS
.B lc
[
.B \-fdbcspan1
]
[ directory ... ]
.SH DESCRIPTION
.I Lc
lists the elements of the given directories.
The elements are
divided into the five basic types (files, directories, character
special files, block special files, and pipes)
and are printed in alphabetical order.
They are normally printed 5 to a line,
preceeded by a title indicating the type,
but the
.B \-1
option can be used to force single-column untitled output.
.PP
If the argument list contains more than one name, the contents of the
directories named in the list are displayed and all other names
are ignored.
If no directory is specified the current working directory is listed
by default.
The special entries ``.'' and ``..''
are normally not listed;
the
.B \-a
option causes them to be listed as well.
.PP
The
.B \-n
option turns off all output; this is useful when only the exit status is
wanted.
(The exit status is 0 if something would have been printed,
1 otherwise.)
.PP
If any of the following option arguments are given,
.I lc
lists only those types of entries;
otherwise, all entries are listed.
The options and their meanings are:
.PP
.RS 5n
.TP
.B f
list ordinary files
.TP
.B d
list directories
.TP
.B b
list block special files
.TP
.B c
list character special files
.TP
.B s
list all special files
.TP
.B p
list permanent pipes
.RE
.PP
.I Lc
may be used with the substitution features of the Shell
to select particular kinds of files (eg, directories) to
take part in some processing,
for example:
.PP
.RS
.B "ls \-l \`lc -1d\`"
.RE
.PP
This lists the contents of all sub-directories of the current directory.
.SH DIAGNOSTICS
Symbolic links are normally followed, and each prints under the category
of the type of thing to which it is linked.
If the symbolic link points to a nonexistent pathname, or if you do
not have permission to resolve the pathname,
.I lc
will list the link under the category
.IR "Unresolved Symbolic Links" .
