.TH SUZY 1 "Choate Rosemary Hall"
.UC 4
.SH NAME
suzy \- word-for-word Latin-to-English "translator"

.SH SYNOPSIS
.B suzy

.SH DESCRIPTION
.I Suzy
is intended as a demonstration artificial intelligence program. 
.I Suzy
is named after a semi-mythical Latin student who translated Latin into English
word-for-word, paying no attention to English contructs or word order; this
program follows this method.
Given a
Latin sentence,
.I suzy
prints out information about each word's type and meaning.
Several options are supported, which determine exactly what information
is printed:

.B debug
- print word's internal representation
.br
.B sentence
- print word translations strung together
.br
.B ident
- print word's part of speech, case, tense, etc.

If an option is prefixed with "no," that information will not be
printed; i.e.,
.B nodebug
causes the suppression of debugging information. 
The default options are: 
.B "nodebug, nosentence, ident. "

To leave
.I suzy,
type either
.B "quit"
or
.B "exit,"
or press Control-D.

.SH AUTHOR
Jan T. Miksovsky '86

.SH SEE ALSO
lisp(1), liszt(1)

.SH BUGS
Many aspects of Latin grammar are not covered, among them: infinitive
and imperative forms of verbs, deponent and semi-deponent verbs, third
declension adjectives, comparative and superlative adjectives, gerunds and
gerundives, neuter nouns, and the vocative case.

Since
.I suzy
tries to use the largest ending it can match on a word, it will find the
"-erum" ending on "puerum," rather than the "-um" ending.

Words which have the same root will not be parsed correctly, such as the
noun "dux, ducis" and the verb "duco, ducere, duxi, ductum."

As of yet, all of the several hundred Latin suffixes have not been
entered.  Also, more irregular forms of verbs such as "sum, esse, fui, futurum"
need to be entered.
