.TH ALERT VAX-4.2BSD 
.SU
.SH NAME
alert \- a program to watch your friends, and set reminders
.SH SYNOPSIS
.B alert
[ -uiwfsdtCFSAD ] 
.SH DESCRIPTION
.I alert 
is a program that can be used amongst friends to watch one another and set
reminders that will go off at a specified time. It uses a daemon (alertd)
that gets run periodically. The granularity of how often this daemon runs
is controllable. Users make requests to this alert daemon, requesting to
watch other users, or to set an alarm to go off at a specified time
with a specified message. The daemon handles logins on multiple
terminals, so if you are watching user "x" you will be informed
(on all the terminals you are logged in) whenever user "x" logs in on
or out of the system. The daemon also flashes a notice whenever the
user goes idle and whenever he becomes active again. You can control
how long an idle time should pass before the daemon should bother you
with its notices. 
The program takes a number of options. If you dont specify any, it goes
into an interactive mode, prompting for commands. This mode has to be
used if you want to set an alarm. This mode is also a good way to see
if things are working.
To use the uppercased options you have to be root.
.PP
The options are:
.TP
.BI \-u " user1,time1,user2,time2 ..."
Specifies a list of users to watch. The times that come after each
username specifies how long an idle time is to be considered
significant for that user. The times are optional and can be omitted,
for a default value of three minutes.
.TP
.BI \-i " user1,user2,user3 ..."
Stops messages about the list of users. 
.TP
.BI \-t " time msg"
Sets an alarm for the specified time. The specified message will be
written to your terminal at that time. At this time, this command can
be invoked only from the interactive mode.
.TP
.BI \-w 
Show status of alert daemon.
.TP
.BI \-f
Shows all acceptable formats for timestrings.
.TP
.BI \-s
Shows all alerts that you have set to go off.
.TP
.BI \-d " alert id"
Deletes alert with the specified id.
.TP
.BI \-C " time in seconds "
Changes the daemon's granularity or how often it gets run. The time in
seconds specifies how long it sleeps between successive invocations.
.TP
.BI \-F " user1,user2,user3 ..."
Flushes the users specified by a comma separated list from the list of
people who are watching others.
.TP
.BI \-S 
Shows the status of the alert daemon. (including who's watching who).
.TP
.BI \-A
Shows all the time alarms that have been set to go off.
.TP
.BI \-D " alarm id "
Deletes the alarm with the specified id.
.TP
.SH FILES
/usr/src/local/alert/alert.log
.SH SEE ALSO 
alertd
.SH ACKNOWLEDGEMENTS
The gdate routine used for parsing time strings was first written by
Barry Shein, Boston University.
.SH BUGS
Should be more like TOPS20 alert. Should use something like rstat
for users on other hosts. Should be able to watch files.
It should be possible to set an alarm from the command line.

