.TH PFSET 1
.SH NAME
pfset \- set programable function keys
.SH SYNOPSIS
.B pfset
.SH DESCRIPTION
.I Pfset
is used to easily configure a terminal's programable function keys.
.PP
.I Pfset
looks at the file
.I .pf${TERM}
in the user's HOME directory for key definitions.
The environmental variable TERM is used to build the actual name of the file.
e.g. if TERM=4425 then the definition file .pf4425 will be used.
Each line of the definition file is composed of four fields,
seperated by colons, corresponding to the elements described in
the following structure.
.sp 1
.RS
.nf
struct	pfent {
	char	*pf_key;
	int	pf_action;
	char	*pf_label;
	char	*pf_command;
};
.ad
.fi
.RE
.PP
The
.I pf_key
field defines the key to be set.
For 4425 terminals,
the keys avialable are f1-f8, the USER PF keys,
and s1-s8, the SYS PF keys.
.PP
The
.I pf_action
field defines the action of the key.
On 4425 terminals the recognized values are
.I
keyed, local
and
.I
send.
.PP
The
.I pf_label
field contains the label to appear the screen.
.PP
The
.I pf_command
field contains the actual string to be sent by the function key.
Embedded newlines in the command are represented in the
usual fashion by `\\n's.
A \\n must be included if a NL is desired at the end of the command.
.SH FILES
~/.pf${TERM}	function definition file
.SH AUTHOR
Edward C. Bennett
.SH BUGS
This program was written to be used with Teletype 4425 terminals.
Modification for other terminal types should be fairly easy.
