#define NLINES	175
#define MAXLINE	128
#define	BWORD	10
#define	CWORD	BWORD
#define CLEN	160
#define PLEN	10
#define VNUM	50
#define VLEN	6
#define OS	0
#define USE	1
#define FRE	2
#define FNB	3
#define FWE	4
#define IFTH	5
#define PPF	6
