.\" @(#)vt100tool.1 1.9 86/04/15 MITRE Corp; from UCB 4.2
.TH VT100TOOL 1 "15 APRIL 1986"
.SH NAME
vt100tool \- Dec VT100 terminal emulator tool
.SH SYNOPSIS
.B vt100tool
.SH DESCRIPTION
.LP
\fBvt100tool\fR emulates a DEC VT100 terminal with a  graphic
module.  It does this in much the same way as
shelltool (see
.IR suntools (1))
emulates a regular glass tty.
When \fBvt100tool\fR is invoked, a  shell is started up,
its output and input are connected to the emulator, and a new
window is formed.  The window is run  as a job from the calling window.
When the emulator is running the function keys take on the same
significance as VT100 function keys and keypad. Buttons R1-R15 
are the VT100 buttons:
.LP
 PF1,PF2,PF3,7,8,9,4,5,6,1,2,3,0,.,Enter 
.LP
from
the keypad. Buttons F3-F6 are the arrow keys: Up, Down, Left, and
Right, respectively, and F7-F9 are PF4,-,and  ",".
It should be noted that these are only the markings on the keys. The
control codes sent to the host are as described in the VT100 manual
and change depending on the setting of certain mode flags.
.LP
Every effort has been made to make the emulator as faithful to the 
VT100 as the Sun Workstation will allow. Exceptions are listed at the end 
of this page. All sizes of characters are handled: regular, double and 
double-height and width as well as 132 character screen and all these
sizes scaled down to the small type of the 132 character screen. All
vt100 attributes are also handled: bold, reverse video. (I don't know how
to do blink on a Sun.) The emulator assumes that the graphics option
is installed and the graphics is activated by the \fBEscape-)\fR and 
\fBEscape-(\fR sequences as on a vt100. Vt52 mode is also handled correctly.
.LP
The Setup panel at the bottom of the window can be used to alter certain
vt100 modes. (All have not been allowed as yet.) The 
.IR local/on-line, wrap,and newline modes 
can be altered from the panel. Clicking the mouse on the 
.IR Setup Button
shows the options and clicking on an option changes the mode
in the emulator. The 
.IR answerback 
message can be set from the Setup Panel
by typing it into the line containing the Sun caret. Only 20 characters
are allowed in the 
.IR answerback 
message as in the VT100.
.LP
There is also a keyboard on the panel, which is obtained by clicking
the mouse on the 
.IR Keyboard
label. This displays a keypad and a set of arrow keys as on a vt100.
These perform the exact same action as the actual Sun-2 keyboard keys
when in the emulator, but they can be labelled on the panel as the
user prefers. The current set of labels are for a vanilla vt100, a
DECMATE or Word-11 keypad, a version of the Rand editor called MRED
and an IBM 3270 emulator on a vt100. The labels will change as the
mouse is clicked on the appropriate label. 
.LP
Typing control-D to vt100tool causes it to die. 
.SH CAVEATS
Like all VT100 emulators, this probably doesn't duplicate every nuance of the
VT100.  In cases where the Sun environment prevents emulation of a feature
then some reasonable thing is done on receipt of the escape code 
requesting the feature. Generally, this is to ignore it. (Xon-Xoff is an
example of this). 
.LP
The vt100tool window may be treated just like other windows; it can be overlaid,
moved, reshaped etc.
However, when the window is reshaped, the contents will not scale.
.LP
.SH FILES
../vtfonts/*
.SH "SEE ALSO"
suntools(1)
.br
Digital VT100  Computer Display Terminal User's Manual
.SH BUGS
.IP (1)
Only wrap, newline, answerback, local are altered by the Setup Panel even
though other features appear there.
.IP (2)
The fonts need help. There are probably some minor glitches here and
there. They had to be created with fonttool which has a few problems
of its own.
.IP (3)
Full reverse screen is erratic. This seems to be caused by a "feature" deep
down in the Sun code which resets the reverse video automatically. I
will try to fix this if I have time and if anyone cares. 
.IP (4)
Smooth scroll does not work.
.IP (5)
You tell me. <Ed Lafferty, MITRE Corp, ell@mitre-bedford.ARPA,
ell@linus.UUCP>




