.TH WATCH 1 ""
.SH NAME
watch \- watch files or directories

.SH SYNOPSIS
.B watch 
[
.I flags
]
.I file ...

.SH DESCRIPTION
.B Watch
is a program for monitoring files or directories.
It accepts a list of files as arguments
and allocates a window on the screen to display
each file.
.P
The top line of each window is reserved for a label
containing the name of the file.
If the file is a directory a slash "/" is appended to the name.
The 
.B -l
flag dispenses with the labels and gives you an extra line
per window (but you'll quickly forget what you were watching).
.P
For an 
.I ordinary file
it functions like
.B
"tail -f".
The window displays the lines at the end of the file and includes
new characters as they are appended.
.P
If the file is a
.I directory
it functions like 
.B
"ls -lrt".
The window displays the directory entries sorted by
modification time with the most recently added files at the
bottom.
The display is updated if a new file is added to the directory
or if the modification time of an existing file is updated.
For each entry the modification time, owner, file size
and file name are displayed.
.P
.B Watch
allocates equal window space to each file argument.
You can control the allocation by giving the window
size after the file name.
.P
.RS
watch iqueue OPTRACE 15 oqueue
.RE
.P
assigns a 15 line window to OPTRACE.
The other two files get what's left, on a 24 line screen
one would get 4 lines and the other 5 lines.
.P
Once watch is running, you can refresh the screen with
ctrl-L or quit by typing a "q" ctrl-d or "del" (interrupt).
.P
You can set alarms in any or all of the windows to wake
you up when something happens.
To set an alarm just hit a digit corresponding to the window.
For the first (top) window just hit "1".
You'll see a star appear just to the right of the label to
remind you that the alarm is set. If the screen gets some
output the terminal bell will go off to wake you up and
the star will disappear.
You can set alarms in all windows by hitting "0".

.SH BUGS
Can't handle all-numeric file names.
