.\"
.\"	Be forwarned -- This manual page requires tbl !!!
.\"
.TH INTEREST 1 MOTOWN
.SH NAME
interest \- calculate interest for IRS
.SH SYNOPSIS
.B interest
.SH DESCRIPTION
.I Interest\^
will calculate interest on dollar amounts based on the Internal
Revenue Service rate table. The table (below) only includes
periods up to June 30, 1987.
.PP
You are prompted to enter in \fImm/dd/yy\fP format a starting
date and an ending date. You must also enter a principle dollar
amount with optional decimal point. Interest is then calculated
and the result displayed. The starting date must be less than
the ending date.
.PP
The following table is used to calculate rates. Rates before June
30, 1975 are all 6%.
.TS
center doublebox;
c | c | c
n | n | l.
\s+2\fIPeriod	Annual Rate	Calculation\fP\s-2
=
06/30/75	6	simple
01/31/76	9	simple
01/31/78	7	simple
01/31/80	6	simple
01/31/82	12	simple
12/31/82	20	simple
06/30/83	16	compound
12/31/84	11	compound
06/30/85	13	compound
12/31/85	11	compound
06/30/86	10	compound
06/30/87	9	compound
.TE
.SH EXAMPLE
Corporation \fIX\fP, which files on a calendar year basis, filed Form
1120, U.S. Corporation Income Tax Return, for 1980 on March 15, 1981,
showing tax of $100,000.00, paying all tax due. On June 1, 1982,
\fIX\fP filed form 1120X, Amended U.S. Corporation Income Tax Return,
for 1980 claiming a refund of $10,000.00. Following an examination,
the Service allows the claim in full on March 9, 1983. To determine
the amount of interest due on that date, enter the following
information:
.TS
center;
r l l.
Enter start date (mm/dd/yy):	3/15/81	\s-2\fB<ENTER>\fP\s+2
Enter end date (mm/dd/yy):	3/9/83	\s-2\fB<ENTER>\fP\s+2
Enter principle:	10000	\s-2\fB<ENTER>\fP\s+2
.TE
The result is printed:
.TS
center;
c s
r l.
Calculating interest for 724 days.
principle =	$10000.00
interest =	$3278.65
total =	$13278.65
.TE
.PP
Interest is calculated from March 15, 1981 to January 31, 1982 (322
days) at 12%, and from February 1, 1982 to December 31, 1982 (334
days) at 20%. This amount is then subject to the 16% compound rate for
68 days to determine the amount of interest accruing between January
1, 1983 and March 9, 1983. Thus, \fIX\fP is entitled to total interest
as of March 9, 1983 of $3,278.65.
.SH AUTHOR
John M. Ritter (motown!jmr)
.br
Allied-Signal, Inc.
.\"	@(#)interest.1	1.0 12/16/86
