.TH ROBOMATIC 6 10/14/85
.UC 4
.SH NAME
robomatic \- Automatically Playing a Game of Logic
.SH SYNOPSIS
.I robomatic
[
.I -d
]
.SH DESCRIPTION
.PP
.I Rob-O-Matic
Plays the "Robots" game written by 
Allan Black of Strathclyde University, Glasgow.
.SH OPTIONS
.TP
.B -d
Turns on debugging.
.SH FILES
.PP
Looks for the Robots executable in the current directory, then in two
places specified at compile-time (one of which is /usr/games).
.SH SEE ALSO
.PP
robots(6)
.SH BUGS
.PP
Doesn't play an optimum game.
.SH HISTORY
.TP
14-Oct-85 Michael Mauldin (mlm) at Carnegie-Mellon University
Created.
