.TH OFILES 8 BBN
.UC 
.SH NAME
ofiles \- who has a file open
.SH SYNOPSIS
.B /systools/ofiles
[
.B \-p
] 
files . . .
.br
.SH DESCRIPTION
.I Ofiles
displays the owner and id of any process accessing a specified device.
The type of access is defined by the 
.I type 
field which can contain:
.IP
.TP 8
.B p 
if 
.I device 
is a mounted file system and the 
proccess has a current directory there.
.br
.TP 8 
.B f
if the proccess has a file on
.I device
open.
.br
.TP 8
.B r
if 
.I device
contains a mounted file system and the proccess has
it's root directory there.
.LP
In the case of special files,
.I device
can be specified by device or file system. i.e.
.IP
.I ofiles 
/dev/disk07 
.br
.I ofiles 
/usr
.LP
If
.I ofiles
is invoked with the
.B \-p 
option, only the process id will be output, 
so that the output of 
.I ofiles
may be piped to
.I "kill(1)" .
.SH "SEE ALSO"
mount(1) kill(1)
.SH DIAGNOSTICS
\*(OQcannot stat . . .\*(CQ when a file cannot be accessed.
.br
