.TH "bpatch" "1" "Benetics Local"
.if t .nr LL 7i
.if t .nr IN .8i
.if n .nr LL 70
.if n .nr IN 8
.fi
.ad b
.SH NAME
bpatch - binary patch and dump file utility
.SH SYNOPSIS
bpatch [ -b blksize ] [ -d ] [ -D pagecnt ] [ -e ] [ -p ] [ -r reclen ] [ -s ] [ -x ] file...
.SH DESCRIPTION
\fIBpatch\fR allows the viewing and/or modification of files, independent of
file type (text, executable, data file, and so forth).  \fIBpatch\fR
allows the data to either be examined at the terminal, dumped to a print
device or file, or edited in the general manner of \fIvi(1)\fR.  The
data in the file is dumped or displayed in \fIpages\fR of 256 bytes.
.SS Options
.IP "-b blksize" 12
The \fI-b\fR option specifies the blocksize of the data file.  This is used
primarily with tapes, and is allowed only with one of the dump (\fI-d\fR
or \fI-D\fR) options.  When this option is specified, the file is opened
in readonly mode.
.IP "-d" 12
The \fI-d\fR option indicates that a dump (no terminal manipulation) is
to be performed.  The entire file will be dumped to standard output.  No
editing of the data is allowed and the file is opened in readonly mode.
.IP "-D pagecnt" 12
The \fI-D\fR option is similar to the \fI-d\fR option, with the
following exception: the pagecnt argument limits the dump to the
specified number of \fIpages\fR.
.IP "-e" 12
The \fI-e\fR option indicates that the file contains EBCDIC data and
should be converted in the character portion of the dump.
.IP "-p" 12
Used with one of the \fIdump\fR options, this option causes the program
to pause between \fIpages\fR.  The program will then wait for the user
to press either the \fIreturn\fR key to continue, or the \fIDEL\fR (or
\fIrubout\fR) key to stop the dump.
.IP "-r reclen" 12
The \fI-r\fR option indicates the record length of the data within the
dump.  When specified, this option causes \fIbpatch\fR to place a colon
(:) between the last byte of one record and the first byte of the next.
.IP "-s" 12
This option turns on the byte swap option.  It may be toggled dynamically
during execution (see \fI-x\fP under Commands below).
.IP "-x" 12
This option specifies the suppression of pages that contain only NUL
characters.  The result is that only the page header (name and page
number) will appear for such a page.  This option may only be used with
one of the dump options.
.SS Arguments
.IP file 12
Any number of files may be specified.
.SS Commands
All commands are valid only in the non-dump, interactive mode.  Commands
may be entered in either upper or lower case.  Commands of the form '^x'
indicate that the control character \fIx\fR is to be entered.
.P
All commands that request movement within a file or between files cannot
be executed if any changes have been made.  To proceed in this case, the
user must either enter the \fIw\fR command, the \fIu\fR command, or the
\fIr\fR command.
.P
Requesting a next or previous file when there is no such will cause the
issuance of an error message.
.P
Note that certain commands allow/require either some text or numeric
value.  In those cases, the user should type in characters and end the
string with either a <cr> or <DEL>.
.IP ? 6
Display the help screen.  The help screen will remain until the user
either redraws the screen (see \fI^r\fR) or changes pages or files.
.IP ! 6
Execute the following command in the shell.
.IP backslash 6
Display the previous page.
.IP <cr> 6
Display the next page.
.IP DEL 6
Quit the program if no changes have been made.
.IP / 6
This command initiates an ASCII search.  The text entered on the command
line will be used as a search string, and the file will be searched
starting with the current page.  When the string is found, the page
containing the string will be displayed.  If the string is not found, an
apapropriate message will be displayed.
.IP ^f 6
Open a named file whose name will be entered on the command line and
followed either by <cr> or DEL.
.IP ^n 6
Open the next file and display the first page.
.IP ^p 6
Open the previous file and display the first page.
.IP ^q 6
Quit without writing current changes.
.IP ^r 6
Redraw the screen.
.IP NNN 6
Entering a numeric value requests that the specified page be displayed.
.IP -x 6
Toggle the command line option represented by \fIx\fR:
.RS 12
.IP a 6
Toggle display to ascii (assume data is ascii).
.IP e 6
Toggle display to dbcdic (assume data is ebcdic).
.IP s 6
Toggle byte swap.
.RE
.IP a 6
Edit the ASCII display.  End edits by pressing the DEL key.  All other
characters will be treated as valid input.  Cursor movement keys (arrows
and home) allow movement within the edit window.  Nonprinting
characters are displayed as dot (.) in this window.
.IP f 6
Display the first page in the current file.
.IP g 6
Display the page containing the byte address typed in following the command.
.IP h 6
Edit the HEXADECIMAL display.  End edits by pressing DEL key.  Cursor
movement keys (arrows and home) allow movement within the edit window.
Two keystrokes are required to modify a byte, and both must be valid
hexadecimal values (0-9 and a-f).  To cancel a change after typing one
character, press DEL.
.IP l 6
Display the last page in the current file.
.IP q 6
Quit the file.  A warning will be issued if any changes have been made
but not written out.
.IP r 6
Reread the current page.
.IP u 6
Undo all changes to the current page.
.IP w 6
Write out the current page.
.SH "SEE ALSO"
od(1)
