.TH TARG 1 local
.DA 23 July 1986
.SH NAME
targ, tarl \- recover files from damaged tar-format archives
.SH SYNOPSIS
\fBtarg\fR file ...
.PP
\fBtarl\fR
.SH DESCRIPTION
\fITarg\fR and \fItarl\fR are used to list and recover files from a
damaged \fItar\fR(1) archive.
They use a simplistic pattern-matching
approach to identify \fItar\fR header blocks.
Both will cheerfully ignore all sorts of bad things about the archive
(such as wrong checksums, read errors, and scraped-off magnetic surface...),
up to a maximum of twenty hard errors in a row.
They report on such things as apparent end-of-file.
Both programs read the \fItar\fR archive from standard input.
.PP
\fITarl\fR lists the file names it sees in the archive.
It is particularly useful for 
preparing a file of names for use with \fItarg\fR.
.PP
\fITarg\fR takes file or directory names as arguments
and attempts to extract them from the archive.
\fITarg\fR is not willing to create directories, however,
so these must be made manually beforehand if they do not already exist.
Files are owned by the user, and have his default permissions.
.SH EXAMPLE
``tarl < /dev/rmt8 > filelist'' lists all files on the tape
mounted on /dev/rmt8 and places the results in ``filelist''.
.PP
``targ joe/precious < /dev/rmt0'' restores the file
``joe/precious'' from the tape mounted on /dev/rmt0.
The directory ``joe'' must already exist.
.SH SEE ALSO
tar(1)
.SH HISTORY
Written by Henry Spencer, Univ. of Toronto Zoology.
This software is public domain.
Manual page by Chris Robertson.
.SH BUGS
\fITarg\fR should be smarter about directories and permissions.
.PP
They really should use the \fItar\fR header-block checksum,
instead of the slightly-arcane pattern matcher, to identify header blocks.
