.TH RVI 1 
.UC 4
.SH NAME
rvi \- remote screen editor based on vi
.SH SYNOPSIS
\fBrvi infd outfd "files"\fR
.br
.SH DESCRIPTION
.I Rvi\^
is a screen editor based on
.IR vi .
It generates
.I ed\^
commands for execution on a remote machine.  The parameters \fBinfd\fR and \fBoutfd\fR are
pipe descriptors connecting
.I rvi\^
to a remote
.I ed\^
program.
.PP
.SH INVOCATION
.I Rvi
is invoked via an escape sequence from within a network terminal program.
The actual sequence varies depending on the terminal program used.  For example,
the escape sequence for
.I cxint
is \fB~v files\fR, while the escape sequence for
.I telnet
is \fB^]v files\fR.
.PP
.SH DIFFERENCES
Entering the command \fBQ\fR allows the user to communicate directly with
.I ed
bypassing the
.I rvi
program.
(To pass control back to
.IR rvi ,
simply type the escape sequence again.)
.br
.sp
Pressing the interrupt key is synoymous with \fBQ\fR.
.br
.sp
The option \fB:set fortran\fR places
.I rvi
in a mode suitable for editing Fortran source files.  Tabs are expanded
to spaces, and the first tabstop is set to column 6.  (Fortran mode is set
implicitly when editing files ending in \fB.f\fR)
.br
.sp
Commands found in the environment variable RVINIT are executed at
initialization time.
.br
.sp
.I Rvi
does not support the following command keystrokes:
\fBz `` = % ( ) { }\fR.
.br
.sp
Macros and tags are not supported.
.PP
.SH "SEE ALSO"
vi (1).
.br
.sp
\f2Vi Quick Reference Card\fR.
.br
\f2An Introduction to Display Editing with Vi\fR,
and
\f2Ex Reference Manual\fR
in the \f2\s-1UNIX\s+1 System Documentation Workbench\fR.
