.TH SHOW 1 "30 May 1985"
.SH NAME
show \- show arguments
.SH SYNOPSIS
.B show
[
.B \-nqr
]
[ arg ] ...
.SH DESCRIPTION
.I Show
writes its arguments separated by blanks and terminated by
a newline on the standard output.  If the flag
.B \-n
is used then the output is not terminated by a newline.
If the flag
.B \-q
is used, then
.I show
runs quietly (arguments are not showed).
.B \-r
is used to show arguments randomly.
.B \-\-
causes the rest of the arguments to be showed, allows arguments
beginning with a
.B \-
to be showed.
.PP
.I Show
understands C-like escape conventions. These are
\\b for backspace,
\\a for bell,
\\f for form feed,
\\n for new line,
\\r for a return,
\\t for tab,
\\v for vertical tab,
\\x followed by one or two hex digits,
\\ followed by string of from one to three octal digits.
\\c causes
.I show
to exit.
Beware of conflicts with the shell's use of \\.
.PP
.I Show
is useful for producing diagnostics in
shell programs and for writing constant data on pipes.
Note that
.I show
will write a new line even if no arguments are given. This
differs from the
.I echo
command.
.I Show
with the 
.B \-q
or
.B \-r
option is not useful.
.SH BUGS
probably!
