.TH XM 1 "10 June 1985"
.UC 4
.SH NAME
xm \- UNIX XMODEM File Transfer Tool
.SH SYNOPSIS
.B xm
[sSrRfF] filename
.SH DESCRIPTION
.I Xm
is a file transfer tool which runs under UNIX.	It, in conjunction
with a CP/M MODEM communications program or other communications
program using the Ward Christensen XMODEM tranfer protocol, allows the
transfer of both binary and text files between UNIX and other systems.
.I Xm
is based on UC 1.2, a more comprehensive file transfer program,
but supports only XMODEM protocol transfers.
.SH USAGE
xm c [filename], where \'c\' MUST be one of the following:
.TP 8
.B f
produce a display of the File Status, including file length, and
number of blocks to transfer.
.TP
.B R
Receive a binary file. If the filename specified already exists, the
user is prompted before the existing file is overwritten.
.TP
.B r
Receive a text file.  CR/LF combinations in the transmitted file are
converted to simple LFs, and the CP/M end\-of\-file mark is deleted.  If
the filename specified already exists, the user is prompted before the
existing file is overwritten.
.TP
.B S
Send a binary file.
.TP
.B s
Send a text file.  Any LF characters in the file are converted to CR/LF
pairs, and the file is terminated with CP/M end\-of\-file characters
(control\-Z).
.sp 1
All descriptions refer to the UNIX system, and all commands require
that a filename be specified.
.SH EXAMPLES
.TP 16
.B xm S myfile
Send binary file \'myfile\' from UNIX
.TP
.B xm r myfile
Receive text file \'myfile\' from remote
.SH BUGS
Because of the lack of file size information, a binary file sent from a
remote system may not be an exact duplicate of the original file. Likewise,
a binary file sent to the remote system will also not be a duplicate, but
will be padded with \'\\0\' characters.
.SH AUTHOR
Michael Farren	(well!farren)
.sp 1
.I Xm
is based on UC 1.2, written by Richard Conn, which was in turn based
on UMODEM 3.5. UMODEM was originally written
by Lauren Weinstein, and was mutated by Richard Conn, Bennett Marks,
Michael Rubenstein, Ben Goldfarb, David Hinnant, and Lauren Weinstein
into version 3.5.
