.TH GETNUMBER 1 "Local"
.SH NAME
getnumber \- generate a series of numbers with a history file
.SH SYNOPSIS
.B getnumber
[ -f filename ]
[ -n count ]
[ -i initial ]
.SH DESCRIPTION
\fIGetnumber\fP generates the next number in a sequence that is remembered in
the file \fI.COUNTER.\fP
The returned values are printed to \fIstdout\fP, one to a line.
The numbers are printed with leading blanks in a field of 5 characters.
.sp
If the history file does not exist, you are asked whether it should be created.
If the initial letter of the reply is \fBy, Y,\fP or \fBnewline\fP,
the file is created.
(A line is read from the \fIstdin\fP so pressing \fIenter\fP
is required.)
If the file does not exist and is not created, the numbers are still
generated to \fIstdout.\fP
Options are:
.sp
.TP 8
\fB\-f \fP\fIfilename\fP
File to be used instead of the default \fI.COUNTER\fP.
.TP 8
\fB-n \fP\fInumber\fP
Number of numbers to be returned.
.TP 8
\fB\-i \fP\fIinitial
Initial value to be returned.  The history file is updated
appropriately.
.sp
.SH FILES
Unless overridden with the \fB\-f\fP option, the file \fB.COUNTER\fP
in the current directory is used.
.SH DIAGNOSTICS
Should be self-explanatory.
.SH BUGS
Uses integers so only the values 1 through 32768 are valid
(on a 16-bit machine.)
.SH HISTORY
Written by Glenn R. Sogge of Datamension Corporation.
