.TH POSTLINT "1" "Friday 3 October 1986" "Wang Institute" "UNIX Programmers's Manual" 
.SH NAME
postlint \- postprocessing filter for lint messages
.SH USAGE
.B postlint 
[number-of-context-lines] < lint-output
.SH DESCRIPTION
The input to
.I postlint
is the output from the
.I lint(1)
C program checker.
.I postlint
reads the
.I lint
output and prints the flagged lines in the files
.I lint
was working on.
.I postlint
simply looks for numbers in parentheses to find line numbers,
and it prints those lines,
preceded by a controllable number of context lines.
These context lines are often where the error occurred,
not on the line mentioned.
By default, the number of context lines is two.
When printing lines from system
.I lint
files,
only one line is printed.
.I postlint
determines the current file by looking for a name
before the parenthesized line number or by looking
for lines with just one field.
For example, when
.I lint
is working on postlint.c,
it prints
.ti +.5i
postlint.c:
.br
.SH FILES
.nf
.ta 1.5i
/usr/lib/lint	Berkeley directory of standard function type declarations
/usr/lib	System V directory of standard function type declarations
.fi
.SH "SEE ALSO"
lint(1)
.SH AUTHOR
Gary Perlman 
.SH STATUS
new, probably not smart enough
