.TH TRW 1
.SH NAME
trw \- Process ANSII or Standard Label tapes.
.SH SYNOPSIS
.B trw
option [parameters]
.SH DESCRIPTION
This program processes a single volume multi-file ANSI or IBM
standard label tape according to one of the user-specified
options listed below.
Trw fully supports 'F', 'FB', 'V', and 'VB' record formats.
When other record formats are encountered on an existing tape
(D, S, U), the records are simply copied as is.
.PP
Options:
.IP d
produces a directory listing of all tape file names and their
corresponding record formats; (Required parameters: "dev=",
"vol=", "tf=ansi" or "tf=stdl")
.IP r
reads user-specified tape files and writes them to the current
directory; (Required parameters: "dev=", "vol=", "tf=ansi" or
"tf=stdl")
.IP w
writes user-specified UNIX files to tape; (Required parameters:
"dev=", "vol=", "tf=ansi" or "tf=stdl", "fn=")
.PP
Parameters:
.IP blklen=
output tape file block length; if specified all tape files written
will have the same block length, otherwise the user will be
prompted. Default for 'F' and 'FB' is 80.
.IP dev=
tape device filename; (Required for all options)
.IP files=
the file numbers of the tape files to be read; Files may be 
individually listed, separated by commas as in 1,3,5 or
a range may be supplied, such as 3-5.  Any combination
of these forms may be used.  Default: all files.
Valid file numbers are from 1 to 32, inclusive.
.IP fn=
file names of UNIX files to be written to tape, specified
as a blank separated list; (Required by 'w' option)
If wild card characters are used, "fn=" must be followed
by at least one blank.
.IP keep=
option to keep the same file names when reading or writing;
(n/N or y/Y) Default: y.
.IP pad=
option to pad records with blanks up to specified record length
(n/N or y/Y) Default: n.
.IP recfm=
output tape file record format: 'F', 'FB', 'V', 'VB'.
If specified all files will have the same record format,
otherwise user will be prompted.
.IP reclen=
output tape file record length; If specified, all tape files
written will have the same record length, otherwise
the user will be prompted.  Default for 'F' and 'FB'
is 80.
.IP tf=ansi/stdl
tape format is ANSI Standard Label if ansi;
if stdl, tape format is IBM Standard Label.
(Required for all options)
.IP vol=
tape volume id; (Required for all options)
If an incorrect id is given, the error message
will return the correct one..
.SH SEE ALSO
mtio(4)
.SH AUTHORS
Karen Cross
.br
Rosemarie Maruskin
.br
University of Kentucky
.SH BUGS
'V' and 'VB' record formats have not been fully tested.
They have only been tested on files that were written
using
.B
trw.
