.TH SHRINK 1 "Edinburgh University" "December 1986"
.SH NAME
shrink \- generate short filenames from extended ones
.SH SYNOPSIS
.B shrink
[ -vnSm ] [ -s\fIseparators\fR ] [ -\fIn\fR ] \fIfilename\fR ...
.SH DESCRIPTION
.I Shrink
converts a filename to a shrunken form, suitable for transportation
to another system with less generous filename length limits.
It takes each
.I filename
given, and applies certain rules to shorten it, if necessary.
In particular, it tries to leave suffixes unchanged, and,
to a less extent, to keep the initial component as close to the
original as possible. Of course, very long suffixes do have to be
truncated.
.PP
The following options are recognized:
.TP
.B -v
Verbose mode. Normally
.I shrink
does its work silently, but under the verbose option it chats about
what decisions its making.
.TP
.B -n
Normally the new filename is generated so as to not clash with an
existing file, to prevent several long-named files folding into the
same shortened form. This behaviour can be revoked by use of the
.B -n
option.
.TP
.B -s
Normally the new filename is printed on the standard output.
The
.B -s
option causes 
.I shrink
to be silent.
This is useful only in conjunction with the
.B -m
option.
.TP
.B -m
This causes the files to be physically renamed;
normally, just the ``suggested'' change is printed but nothing
actually done.
.TP
.B "-s \fIseparators\fB"
This can be used to change the set of
.I separators
that 
.I shrink
recognizes.
These are the characters that are used to delimit filename components.
.I Shrink
operates by shrinking characters out of each component
(though it is loath to modify the first or last components unless
it has no choice), while leaving the delimiters unchanged.
However, if a filename contains a vast number of delimiter characters
(such as
.I this_file_contains_quite_a_lot_of_stuff_and_useful_stuff_at_that
), then some components (and their associated delimiters)
will have to be deleted totally.
The default delimiter set is
.BR + ,
.BR - ,
.BR . ,
.BR _ ,
.BR ~ 
and
.BR , .
.TP
.B "-\fIn\fB"
A numerical flag \fIn\fR may be given to specify a maximum length
that the resultant filename is allowed to be.
The default is 14 (which is the maximum file length under all unix
systems without the Berkeley modified filesystem).
.SH DIAGNOSTICS
Under the
.B -v
option, lots of diagnostics can be produced.
Those preceded by the word
.B "``warning:''"
can probably be ignored.
.PP
Under certain circumstances, 
.I shrink
may refuse totally to deal with some filenames,
though this is not very likely to occur unless a very small
maximum length flag is specified.
.SH BUGS
If the file begins with a delimiter character,
then 
.I shrink
sometimes causes the shortened filename to be shorter than it
need be.
This is not too serious a bug.
.SH AUTHOR
Simon Brown.
