.TH PMAN 1WI "May 27, 1985" "Wang Institute" "UNIX User's Manual"
.SH NAME
pman \- extract selected parts of an on-line manual page
.SH SYNTAX
.B pman
[-abcdehknosvwx] [-+ name] [section] [-] names
.SH DESCRIPTION
.I pman
is used to print one or more parts of a
.I man
page, such as the NAME or EXAMPLE section.
The program allows quick reference to the on-line manual,
showing only parts of interest.
Synonyms are used to avoid overlooking topics.
A part begins with a section name,
and ends with a new part.
A new part is a line beginning with at least with two upper case letters
(except for \fInroff\fR page breaks that may contain the upper case
name of the entry).
Sections are printed in the order they appear in the manual entry,
not in the order requested.
Blank lines are suppressed, and there is an option for extra-compact
output, making pagination by programs like
.I more
unnecessary.
.SH OPTIONS
.PP
The section of the manual (1-8) can be supplied after all the flag options
and before the names.
Otherwise, all sections are searched until an entry is found.
The manual entry can be read from the standard where a single - is placed
instead of a name.
.de OP\"option
.TP
.B -\\$1 \\$2 \\$3
..
.PP
Most option letters correspond to a man page section.
With no options, the -n, -s, and -e options are assumed.
.OP a
Print all entries in a requested section or all sections
of the given name.
This allows searching for more than one version of an entry,
which can happen with local implementations.
This option implies the -h option so that the section is printed.
.OP b
Non-redundant blank lines are printed.
By default, these are removed to compress the output.
.OP c
Compacted output.
With this option,
.I pman
tries to put parts on one line.
This option assumes that text is indented five spaces
and may be upset by tabs in the formatted entry.
.OP h
Print a header with the entry's name and source section.
.SS Sections
.PP
The following options print parts of manual entries
or types of manual entries (such as all sections with warnings).
.OP + name
Add \fBname\fR to the list of printed parts.
This allows access to sections not anticipated by
.I pman,
or using
.I pman
without having to know the options.
.OP d
DESCRIPTION, OPTIONS, NOTES, COMMENTS, COMMANDS
(detail about the entry)
.OP e
EXAMPLES or HINTS
.OP k
KEYWORDS, NAME, or SEE ALSO
.OP n
NAME
(name and purpose of the entry)
.OP o
OPTIONS
(unfortunately, few files use a separate section expressly for
option descriptions)
.OP s
SYNTAX, SYNOPSIS, or USAGE
.OP v
VARIABLES, ENVIRONMENT, or FILES
(special variables or files used by the entry)
.OP w
WARNINGS, BUGS, LIMITATIONS, RESTRICTIONS, DIAGNOSTICS, CAVEATS, NOTES,
and STATUS
.OP x
SEE ALSO, REFERENCES, ALGORITHM, and AUTHOR (cross-references)
.SH EXAMPLES
.de EX
.nf
.ta 2.5i
\fB\\$1	\fR# \\$2
.fi
..
.EX "pman -s echo"                   "SYNTAX from \fIman echo"
.EX "pman -vw 1 man"                 "VARIABLES & WARNINGS from \fIman 1 man\fR"
.EX "pman -+ 7 REQ man"              "REQUESTS section on \fIman\fR macros"
.EX "pman -hd w | sed 's/.^H//g'"    "header & detail unhighlighted"
.fi
.SH FILE
/usr/man/cat?/* (formatted manual entries searched for here)
.SH "SEE ALSO
man(1)
.SH KEYWORDS
help, documentation
.SH AUTHOR
Gary \fIP\fPerl\fPman\fP (based on a shell script by Bob Marcus)
.SH BUGS
.PP
The compacted output may have problems when there are tabs in
the formatted text.
.SH RESTRICTIONS
.PP
.I pman
will not work if sections headings are indented or contain
overstriking to embolden.
The filter: \fBsed 's/.^H//g'\fR can be used with the standard input
option to help with this problem.
.SH STATUS
.PP
I am open to suggestions for enhancements.
Bug fixes and new features are appreciated and will be acknowledged.
.PP
The program has been tested on 4.2 BSD UNIX and System V.
