'\" Revision Level 
'\" Last Delta     12-07-85
.TH SB 1 OMEN
.SH NAME
sb \- X/YMODEM Batch file Send
.SH SYNOPSIS
.B sb
[
.B \-1dfkquv
]
.I file ...
.br
.B "sb -X"
[
.B \-1kquv
]
.I file
.SH DESCRIPTION
.B Sb
uses the XMODEM and YMODEM error correcting protocols to send
files over a serial port to a variety of programs running under
PC-DOS, CP/M, *nix, and other operating systems.

The first form of
.B sb
sends one or more files with YMODEM batch protocol.
Normally, only the file name part of the pathname is transmitted.
On
.SM Unix
systems, additional information about the file is transmitted.
If the receiving program uses this information,
the transmitted file length controls the exact number of bytes written to
the output dataset,
and the modify time and file mode
are set accordingly.

The second form of
.B sb
uses the
.B -X
flag to send a single
.I file
with XMODEM protocol.
The user must supply the file name to both sending and receiving programs.

If sb is invoked with stdout and stderr to different datasets,
Verbose is set to 2, causing frame by frame progress reports
to stderr.
This may be disabled with the
.B q
option.

Iff sb is invoked with $SHELL set and iff that variable contains the
string
.I "rsh"
or
.I "rksh"
(restricted shell), sb operates in restricted mode.
Restricted mode restricts pathnames to the current directory and
PUBDIR (conventionally, /usr/spool/uucppublic) and/or subdirectories
thereof.

Unix
.B sb
supports YMODEM-g
with "cbreak" tty mode, XON/XOFF flow control,
and the interrupt character set to CAN.
YMODEM-g
(Pro-YAM
.B g
option)
increases throughput over error free channels
(direct connection, X.PC, etc.)
by not acknowledging each transmitted sector.
.PP
The meanings of the available options are:
.PP
.PD 0
.TP
.B 1
Use file descriptor 1 for ioctls and reads (Unix only).
By default, file descriptor 0 is used.
This option allows
.B sb
to be used with the
.I cu
^$
command.
.TP
.B X
(XMODEM protocol)
Send a single file without the filename packet.
.TP
.B d
Change all instances of "." to "/" in the transmitted pathname.
Thus, C.omenB0000 (which is unacceptable to MSDOS or CP/M)
is transmitted as C/omenB0000.
If the resultant filename has more than 8 characters in the stem,
a "." in inserted to allow a total of eleven.
.TP
.B f
Send Full pathnname.
Normally directory prefices are stripped from the transmitted
filename.
.TP
.B k
Send files using 1024 byte blocks
rather than the default 128 byte blocks.
1024 byte packets speed file transfers at high bit rates.
.TP
.B q
Quiet suppresses verbosity.
.TP
.B u
Unlink the file after successful transmission.
.TP
.B v
.IR Verbose
causes a list of file
names to be appended to
/tmp/sblog .
More v's generate more output.
.PD
.SH EXAMPLES
.ne 7
(Unix command)
.RS
$
.I "sb -k *.c"
.br
.RE
(Pro-YAM command)
.RS
.I "<F3>"
.br
.RE
(8-bit YAM Commands)
.br
.RS
.I "^E"
.br
>>>c:
.I "rt"
.br
.RE
.SH SEE ALSO
rb(omen),
YMODEM.DOC,
Professional-YAM manual,
IMP(CP/M),
cu(1),
sq(omen),
todos(omen),
tocpm(omen),
tomac(omen)

Compile time options required for various operating systems are described in
the rbsb.c source file.
.SH BUGS
On VMS,
some of the #includes with file names enclosed with angle brackets <>
may need to have the angle brackets removed, or vice versa.

The VMS version does not transmit the file date.

The VMS version does not recognize YMODEM-g.

The VMS version calculates the file length by reading the file
and counting the bytes.

When VMS is lightly loaded, the response time may be too quick for MODEM7
unless the MODEM7
.B "q"
modifier is used.

The VMS C standard i/o package and RMS sometimes interact to modify
file contents unexpectedly.
